import { test, expect } from '@playwright/test';
import { initialState } from '../../src/game/state/initialState';
import { gameConfig as c } from '../../src/config/gameConfig';
import { createTodo } from '../../src/game/work/todoManager';
import { startWork, interruptWithFood } from '../../src/game/targets/targetManager';
async function seed(page:import('@playwright/test').Page,s:ReturnType<typeof initialState>){await page.clock.install({time:new Date('2026-10-05T00:00:00Z')});await page.clock.pauseAt(new Date('2026-10-05T00:00:01Z'));await page.addInitScript(({key,value})=>{value.offline.lastSeenAt=Date.now();localStorage.setItem(key,JSON.stringify(value));},{key:c.save.key,value:s});await page.goto('/');}
test('promotion UI counts queued current and suspended overdue with clear lock reason',async({page})=>{
 await page.setViewportSize({width:390,height:844});const s=initialState(42);s.player.money=10000;s.world.totalWorldTime=24;s.world.timeOfDay=24;s.world.nextEventAt=1e8;s.needs.phase='MORNING';s.needs.satietyUntil=1e8;s.needs.projectRollProcessedRoutineId=0;
 const work=()=>{const t=createTodo(s,c.work.templates[0]);t.assignmentWorkdayIndex=-1;t.deadlineWorkdays=0;t.dueWorkdayIndex=-1;return t;};s.todoQueue=Array.from({length:4},work);startWork(s,s.todoQueue.shift()!);interruptWithFood(s);await seed(page,s);
 await page.getByRole('navigation').getByRole('button',{name:'升級'}).click();const card=page.locator('.promotion-card');await expect(card).toContainText('已逾期工作：4 / 最多 3');await expect(card).toContainText('目前仍有過多逾期工作');await expect(card.getByRole('button',{name:/升職/})).toHaveCount(0);await expect(page.getByLabel('待辦數量')).toContainText('已逾期 3');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await page.screenshot({path:'tests/artifacts/age-promotion-lock.png'});
});
test('age product UI shows live compensation and disables it without removing workload pressure',async({page})=>{
 await page.setViewportSize({width:390,height:844});const s=initialState(42);s.player.money=10000;s.player.age=50;s.player.ageProgressDays=28*c.age.daysPerYear;await seed(page,s);await page.getByRole('navigation').getByRole('button',{name:'產品'}).click();const card=page.getByRole('region',{name:'時光緩衝組'});await expect(card).toContainText('人生工作負擔 ×1.45');await expect(card).toContainText('目前產品效率補償 +0%');await expect(card).toContainText('離線年齡進度 ×0.50');await card.getByRole('button',{name:/啟用/}).click();await expect(card).toContainText('目前產品效率補償 +22.5%');await card.getByRole('button',{name:'停用',exact:true}).click();await expect(card).toContainText('目前產品效率補償 +0%');await expect(card).toContainText('人生工作負擔 ×1.45');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await card.screenshot({path:'tests/artifacts/age-product-effects.png'});
 await page.getByRole('button',{name:'Debug',exact:true}).click();await expect(page.getByRole('button',{name:'年齡 22 歲',exact:true})).toBeVisible();await page.getByRole('button',{name:'Enable Age Product',exact:true}).click();await expect(page.getByText(/Product Age Efficiency Bonus/)).toContainText('+22.5%');await page.getByRole('button',{name:'Disable Age Product',exact:true}).click();await expect(page.getByText(/Product Age Efficiency Bonus/)).toContainText('+0.0%');
});
