import {test,expect} from '@playwright/test';
import {initialState} from '../../src/game/state/initialState';
import {gameConfig as c} from '../../src/config/gameConfig';
import {createTodo} from '../../src/game/work/todoManager';
import {startWork} from '../../src/game/targets/targetManager';
import {syncWorld} from '../../src/game/time/worldTime';
import {TEST_PRODUCT_A,TEST_PRODUCT_B} from '../product-fixtures';
import type {State} from '../../src/game/types';
async function seed(page:import('@playwright/test').Page,s:State){await page.clock.install({time:new Date('2026-10-07T00:00:00Z')});await page.clock.pauseAt(new Date('2026-10-07T00:00:01Z'));await page.addInitScript(({key,value})=>{if(!localStorage.getItem(key)){value.offline.lastSeenAt=Date.now();localStorage.setItem(key,JSON.stringify(value));}},{key:c.save.key,value:s});await page.goto('/');await page.clock.runFor(50);}
test('Config-only synthetic A/B UI, additive old Save, activation/effect/cycle/expiry and reload',async({page})=>{
 const override=structuredClone(c);override.products.definitions.push(structuredClone(TEST_PRODUCT_A),structuredClone(TEST_PRODUCT_B));
 await page.route('**/config/generated/game_config.json*',route=>route.fulfill({status:200,contentType:'application/javascript',body:`export default ${JSON.stringify(override)};`}));
 const s=initialState(42);s.player.money=40;s.player.age=50;s.player.ageProgressDays=28*c.age.daysPerYear;s.world.totalWorldTime=24;syncWorld(s);s.world.nextEventAt=1e9;s.world.lastDeadlineNoticeWorkday=0;s.meetings.lastScheduledWorkday=0;s.promotion.lastCheckedWorkday=0;s.needs.phase='MORNING';s.needs.projectRollProcessedRoutineId=0;s.needs.satietyUntil=1e9;startWork(s,createTodo(s,{...c.work.templates[0],workload:1e9},'EVENT'));
 await seed(page,s);await page.getByRole('navigation').getByRole('button',{name:'產品'}).click();
 const a=page.getByRole('region',{name:TEST_PRODUCT_A.name,exact:true}),b=page.getByRole('region',{name:TEST_PRODUCT_B.name,exact:true});await expect(a).toBeVisible();await expect(b).toContainText('$23／2 遊戲日');await a.getByRole('button',{name:'啟用 $17',exact:true}).click();await b.getByRole('button',{name:'啟用 $23',exact:true}).click();
 const active=await page.evaluate(key=>JSON.parse(localStorage.getItem(key)!),c.save.key);expect(active.products.TEST_PRODUCT_A.active).toBe(true);expect(active.products.TEST_PRODUCT_B.active).toBe(true);expect(active.player.money).toBe(0);expect(active.stats.workSpeed).toBeCloseTo(11.125);await expect(a).toContainText('有效中');await expect(b).toContainText('目前產品效率補償 +11.2%');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await page.screenshot({path:'tests/artifacts/product-framework-synthetic.png'});
 await page.reload();await page.getByRole('navigation').getByRole('button',{name:'產品'}).click();await expect(a).toContainText('有效中');const saved=await page.evaluate(key=>JSON.parse(localStorage.getItem(key)!),c.save.key);expect(saved.products.TEST_PRODUCT_B.nextBillingWorldTime).toBe(active.products.TEST_PRODUCT_B.nextBillingWorldTime);expect(saved.products.TEST_PRODUCT_A.contributionStats.billingSpent).toBe(17);
 await page.clock.runFor(361000);await expect(a).toContainText('已停用');await expect(b).toContainText('已停用');await page.clock.runFor(3100);const expired=await page.evaluate(key=>JSON.parse(localStorage.getItem(key)!),c.save.key);expect(expired.currentTarget.type).toBe('WORK');expect(expired.currentTarget.progress).toBeGreaterThan(active.currentTarget.progress);expect(expired.products.TEST_PRODUCT_A.active).toBe(false);expect(expired.products.TEST_PRODUCT_B.active).toBe(false);expect(expired.stats.workSpeed).toBeCloseTo(7); // zero-sleep modifier retained; product bonus gone.
});
test('existing product UI disable/re-enable retains paid expiry and current Work progress',async({page})=>{const s=initialState(42);s.player.money=1000;s.player.age=50;s.player.ageProgressDays=28*c.age.daysPerYear;s.world.totalWorldTime=24;syncWorld(s);s.world.nextEventAt=1e9;s.meetings.lastScheduledWorkday=0;s.promotion.lastCheckedWorkday=0;s.needs.phase='MORNING';s.needs.projectRollProcessedRoutineId=0;s.needs.satietyUntil=1e9;startWork(s,createTodo(s,{...c.work.templates[0],workload:1e9},'EVENT'));await seed(page,s);await page.getByRole('navigation').getByRole('button',{name:'產品'}).click();const card=page.getByRole('region',{name:'時光緩衝組',exact:true});await card.getByRole('button',{name:'啟用 $120',exact:true}).click();await page.clock.runFor(1000);const before=await page.evaluate(key=>JSON.parse(localStorage.getItem(key)!),c.save.key);await card.getByRole('button',{name:'停用',exact:true}).click();const off=await page.evaluate(key=>JSON.parse(localStorage.getItem(key)!),c.save.key);expect(off.currentTarget.progress).toBeGreaterThanOrEqual(before.currentTarget.progress);expect(off.stats.workSpeed).toBe(10);await card.getByRole('button',{name:'恢復啟用',exact:true}).click();const on=await page.evaluate(key=>JSON.parse(localStorage.getItem(key)!),c.save.key);expect(on.player.money).toBe(before.player.money);expect(on.products.agecare.nextBillingWorldTime).toBe(before.products.agecare.nextBillingWorldTime);expect(on.stats.workSpeed).toBeCloseTo(12.25);expect(on.currentTarget.progress).toBe(off.currentTarget.progress);});
