import {test,expect} from '@playwright/test';
import {initialState} from '../../src/game/state/initialState';
import {gameConfig as c} from '../../src/config/gameConfig';
import {checkPromotionWorkStart} from '../../src/game/career/promotionAssignment';
import {syncWorld} from '../../src/game/time/worldTime';
import type {State} from '../../src/game/types';
async function seed(page:import('@playwright/test').Page,s:State){await page.clock.install({time:new Date('2026-10-08T00:00:00Z')});await page.clock.pauseAt(new Date('2026-10-08T00:00:01Z'));await page.addInitScript(({key,value})=>{if(!localStorage.getItem(key)){value.offline.lastSeenAt=Date.now();localStorage.setItem(key,JSON.stringify(value));}},{key:c.save.key,value:s});await page.goto('/');await page.clock.runFor(50);}
function ready(multiplier=1){const s=initialState(42);s.player.money=10000;s.player.upgrades.efficiency=20*multiplier-10;s.player.upgrades.quality=12*multiplier-6;s.world.totalWorldTime=24;syncWorld(s);s.world.nextEventAt=1e9;s.needs.projectRollProcessedRoutineId=0;s.needs.satietyUntil=1e9;s.needs.breakfastState='COMPLETED';s.needs.phase='MORNING';s.meetings.lastScheduledWorkday=0;return s;}
test('qualification and low profile show base stats; mobile no overflow',async({page})=>{const s=ready();s.player.upgrades.efficiency=40;s.player.upgrades.quality=30;s.promotion.lastCheckedWorkday=0;await seed(page,s);await page.getByRole('navigation').getByRole('button',{name:'升級'}).click();const card=page.locator('.promotion-card');await expect(card).toContainText('穩定效率 50');await expect(card).not.toContainText('需要資金');await expect(card).toContainText('升職不收費');await card.getByRole('checkbox',{name:'低調摸魚'}).check();await expect(card).toContainText('資格判定效率 40');await expect(card).toContainText('不影響實際工作');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await page.reload();await page.getByRole('navigation').getByRole('button',{name:'升級'}).click();await expect(page.getByRole('checkbox',{name:'低調摸魚'})).toBeChecked();});
test('morning assignment skips lunch; deadline fails into Dinner then same overtime; reload preserves',async({page})=>{const s=ready();checkPromotionWorkStart(s);const id=s.currentTarget!.id;await seed(page,s);const card=page.getByRole('region',{name:'中央目標'});await expect(card).toHaveAttribute('data-kind','promotion');await expect(card).toContainText('下班／晚餐錨點');await page.clock.runFor(65000);await expect(card).toHaveAttribute('data-kind','promotion');await page.reload();await expect(card).toHaveAttribute('data-kind','promotion');await page.clock.runFor(31000);await expect(card).toContainText('晚餐食物怪');await page.clock.runFor(4100);await expect(card).toHaveAttribute('data-kind','promotion');await expect(card).toContainText('考核已失敗');await expect(card).toHaveAttribute('data-target-key',`0:${id}`);await page.clock.runFor(20000);const done=await page.evaluate(key=>JSON.parse(localStorage.getItem(key)!),c.save.key);expect(done.career.rank).toBe(0);expect(done.promotion.status).toBe('COOLDOWN');});
test('high ability first assignment succeeds at Dinner and is saved',async({page})=>{const s=ready(2);s.player.money=0;checkPromotionWorkStart(s);await seed(page,s);await page.clock.runFor(100000);let saved=await page.evaluate(key=>JSON.parse(localStorage.getItem(key)!),c.save.key);expect(saved.career.rank).toBe(1);});
test('sleep displays60x and resumes normal after workstart',async({page})=>{const sleeping=initialState(42);sleeping.world.totalWorldTime=150;syncWorld(sleeping);sleeping.world.nextEventAt=1e9;sleeping.needs.phase='SLEEP';sleeping.currentTarget={id:'sleep',type:'SLEEP',name:'Sleep',createdAt:150,requirement:54,progress:0};await seed(page,sleeping);await expect(page.getByRole('region',{name:'中央目標'})).toContainText('睡眠中 ×60');await page.clock.runFor(1000);await expect(page.getByRole('region',{name:'中央目標'})).toContainText('早餐食物怪');await page.clock.runFor(3100);const saved=await page.evaluate(key=>JSON.parse(localStorage.getItem(key)!),c.save.key);expect(saved.world.totalWorldTime).toBeGreaterThanOrEqual(204);expect(saved.world.totalWorldTime).toBeLessThan(210);expect(saved.needs.sleep.lastRatio).toBe(1);});
