import {test,expect} from '@playwright/test';
import {initialState} from '../../src/game/state/initialState';
import {gameConfig as c} from '../../src/config/gameConfig';
import {checkPromotionWorkStart,startPromotionAssignment} from '../../src/game/career/promotionAssignment';
import {syncWorld} from '../../src/game/time/worldTime';
import type {State} from '../../src/game/types';
async function seed(page:import('@playwright/test').Page,s:State){await page.clock.install({time:new Date('2026-10-07T00:00:00Z')});await page.clock.pauseAt(new Date('2026-10-07T00:00:01Z'));await page.addInitScript(({key,value})=>{if(!localStorage.getItem(key)){value.offline.lastSeenAt=Date.now();localStorage.setItem(key,JSON.stringify(value));}},{key:c.save.key,value:s});await page.goto('/');await page.clock.runFor(50);}
function ready(){const s=initialState(42);s.player.money=10000;s.player.upgrades.efficiency=6;s.player.upgrades.quality=6;s.world.totalWorldTime=8;syncWorld(s);s.world.nextEventAt=1e9;s.needs.projectRollProcessedRoutineId=0;s.needs.phase='MORNING';return s;}
test('normal UI has qualification and Low Profile, no direct Promote; mobile no overflow',async({page})=>{const s=ready();s.player.upgrades.efficiency=40;s.player.upgrades.quality=30;s.promotion.lastCheckedWorkday=0;await seed(page,s);await page.getByRole('navigation').getByRole('button',{name:'升級'}).click();const card=page.locator('.promotion-card');await expect(card.getByRole('button',{name:/升職/})).toHaveCount(0);await expect(card).toContainText('穩定效率 60');await card.getByRole('checkbox',{name:'低調摸魚'}).check();await expect(card).toContainText('資格判定效率 48');await expect(card).toContainText('不影響實際工作');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await page.screenshot({path:'tests/artifacts/promotion-qualification.png'});await page.reload();await page.getByRole('navigation').getByRole('button',{name:'升級'}).click();await expect(page.getByRole('checkbox',{name:'低調摸魚'})).toBeChecked();});
test('assessment central card shows dedicated identity speed ETA deadline; persists and succeeds',async({page})=>{const s=ready();checkPromotionWorkStart(s);s.promotion.pending=true;s.world.totalWorldTime=44;syncWorld(s);startPromotionAssignment(s);await seed(page,s);const card=page.getByRole('region',{name:'中央目標'});await expect(card).toHaveAttribute('data-kind','promotion');await expect(card).toContainText('獨立需求處理');await expect(card).toContainText('完成即可升職');await expect(card).toContainText('預估剩餘');await expect(card).toContainText('下一個 WorkStart');await page.clock.runFor(3100);const before=await page.evaluate(key=>JSON.parse(localStorage.getItem(key)!),c.save.key);await page.reload();await expect(card).toHaveAttribute('data-kind','promotion');const after=await page.evaluate(key=>JSON.parse(localStorage.getItem(key)!),c.save.key);expect(after.promotion.progress).toBeGreaterThanOrEqual(before.promotion.progress);expect(after.promotion.deadlineWorldTime).toBe(before.promotion.deadlineWorldTime);await page.screenshot({path:'tests/artifacts/promotion-active.png'});await page.clock.runFor(5000);const done=await page.evaluate(key=>JSON.parse(localStorage.getItem(key)!),c.save.key);expect(done.career.rank).toBe(1);expect(done.promotion.assignmentId).toBeNull();});
test('scheduled assessment Dinner first and Low Profile does not cancel',async({page})=>{const s=ready();checkPromotionWorkStart(s);s.world.totalWorldTime=40;syncWorld(s);s.needs.phase='AFTERNOON';await seed(page,s);await expect(page.getByRole('region',{name:'中央目標'})).toContainText('晚餐食物怪');await page.getByRole('navigation').getByRole('button',{name:'升級'}).click();await page.getByRole('checkbox',{name:'低調摸魚'}).check();await page.getByRole('navigation').getByRole('button',{name:'日常'}).click();await page.clock.runFor(4200);await expect(page.getByRole('region',{name:'中央目標'})).toHaveAttribute('data-kind','promotion');});
