import test from 'node:test';
import assert from 'node:assert/strict';
import { gameConfig as c } from '../src/config/gameConfig';
import { initialState } from '../src/game/state/initialState';
import { createTodo } from '../src/game/work/todoManager';
import { createFollowUp, releasePending } from '../src/game/work/followUpManager';
import { getAgeWorkloadMultiplier, ageProductEfficiencyBonus } from '../src/game/work/ageWorkload';
import { effectiveWorkSpeed, effectiveWorkQuality, workReward } from '../src/game/work/workStats';
import { createProject, completeProjectSubtask } from '../src/game/projects/projectManager';
import { resolveBoss, catchChance, escapeChance } from '../src/game/career/bossEvents';
import { followUpChance, followUpCount } from '../src/game/work/workQuality';
import { canPromote, getUnresolvedOverdueWorkCount } from '../src/game/career/promotion';
import { toggleProduct } from '../src/game/products/productManager';
import { renewProduct } from '../src/game/products/billingManager';
import { startWork, interruptWithFood } from '../src/game/targets/targetManager';
import { applyAction } from '../src/game/engine/actions';
import { advance } from '../src/game/engine/SimulationLoop';
import { settleOfflineMinutes } from '../src/game/time/offlineSimulation';
import { prestigeReset } from '../src/game/prestige/prestigeManager';
import { getDeadlineStatus } from '../src/game/work/deadline';
import { loadGame, saveGame, validateSave } from '../src/game/save/saveGame';
function state(age=22,time=8){const s=initialState(42,0);s.world.totalWorldTime=time;s.world.dayIndex=Math.floor(time/60);s.world.timeOfDay=time%60;s.world.nextEventAt=1e8;s.needs.phase='MORNING';s.needs.projectRollProcessedRoutineId=0;s.needs.satietyUntil=1e8;setAge(s,age);return s;}
function setAge(s:ReturnType<typeof state>,age:number){s.player.age=age;s.player.ageProgressDays=(age-c.age.start)*c.age.daysPerYear;}
function todo(s=state(),overdue=false){const t=createTodo(s,c.work.templates[0]);if(overdue){t.assignmentWorkdayIndex=-1;t.deadlineWorkdays=0;t.dueWorkdayIndex=-1;}return t;}
function overdue(s:ReturnType<typeof state>,count:number){s.todoQueue=Array.from({length:count},()=>todo(s,true));}
const close=(a:number,b:number)=>assert.ok(Math.abs(a-b)<1e-8,`${a} != ${b}`);
for(const age of [22,30,40,50,60])test(`age ${age} uses configured workload multiplier`,()=>assert.equal(getAgeWorkloadMultiplier(age),c.age.workloadCurve.find(p=>p.age===age)!.multiplier));
test('06 normal work snapshots age workload',()=>{const s=state(50),t=todo(s);close(t.workload,t.baseWorkload*1.45);assert.equal(t.ageWorkloadMultiplierAtCreation,1.45);});
for(const type of ['REWORK','CLIENT_REPLY','NEW_REQUEST','CORRECTION','MISSING_INFO','PROJECT_NEXT_STEP'] as const)test(`${type} derives unscaled parent base then applies age once`,()=>{const s=state(50),root=todo(s);const [t]=createFollowUp(s,root,type,1,0);const factor=c.followUps.types.find(f=>f.type===type)!.workloadFactor;close(t.baseWorkload,root.baseWorkload*factor);close(t.workload,root.baseWorkload*factor*1.45);});
test('10 project subtask applies age when unlocked not when parent formed',()=>{const s=state(50),p=createProject(s)!;const first=s.todoQueue.shift()!;close(first.workload,first.baseWorkload*1.45);setAge(s,60);completeProjectSubtask(s,first);assert.ok(s.todoQueue.every(t=>t.ageWorkloadMultiplierAtCreation===1.7));assert.equal(first.ageWorkloadMultiplierAtCreation,1.45);});
test('11 boss uses base one game hour with rank and age exactly once',()=>{const s=state(50);s.career.rank=2;resolveBoss(s,true,false);const t=s.todoQueue[0];close(t.workload,c.work.bossWorkHours*c.time.dayDuration/c.time.hoursPerDay*c.economy.baseWorkSpeed*c.ranks[2].workloadMultiplier*1.45);});
test('12 deep followups never compound age multiplier',()=>{const s=state(60),root=todo(s),a=createFollowUp(s,root,'REWORK',1,0)[0],b=createFollowUp(s,a,'REWORK',1,0)[0];close(b.workload,b.baseWorkload*b.rankWorkloadMultiplierAtCreation*1.7);});
test('13 existing 39 year work remains fixed after turning40',()=>{const s=state(39),t=todo(s),before=t.workload;startWork(s,t);setAge(s,40);assert.equal(t.workload,before);assert.equal(s.currentTarget?.type==='WORK'?s.currentTarget.requirement:null,before);});
test('14 new work after40 uses new multiplier',()=>{const s=state(39),a=todo(s);setAge(s,40);const b=todo(s);assert.equal(a.ageWorkloadMultiplierAtCreation,1.1);assert.equal(b.ageWorkloadMultiplierAtCreation,1.25);});
test('15 age never lowers quality or baseline efficiency',()=>{const a=state(22),b=state(60);assert.equal(effectiveWorkQuality(a),effectiveWorkQuality(b));assert.equal(effectiveWorkSpeed(a),effectiveWorkSpeed(b));});
test('16 age never changes rework chance',()=>{const a=state(22),b=state(60),t=todo(a),rule=c.followUps.types[0];assert.equal(followUpChance(a,t,rule),followUpChance(b,t,rule));});
test('17 age never changes followup counts',()=>{const a=state(22),b=state(60),t=todo(a);for(const rule of c.followUps.types)assert.equal(followUpCount(a,t,rule,.5),followUpCount(b,t,rule,.5));});
test('18 age does not change project spawn rules or seeded selection',()=>{const a=state(22),b=state(60);assert.equal(c.ranks[a.career.rank].projectChance,c.ranks[b.career.rank].projectChance);assert.equal(a.world.rng,b.world.rng);});
test('19 age never changes boss catch or escape',()=>{const a=state(22),b=state(60);assert.equal(catchChance(a),catchChance(b));assert.equal(escapeChance(a),escapeChance(b));});
test('20 age product22 gives zero bonus',()=>{const s=state();s.player.money=1e6;toggleProduct(s,'agecare');assert.equal(ageProductEfficiencyBonus(s),0);});
test('21 age product50 bonus is current excess times configured rate',()=>{const s=state(50);s.player.money=1e6;toggleProduct(s,'agecare');close(ageProductEfficiencyBonus(s),.45*c.products.definitions.find(p=>p.id==='agecare')!.ageEfficiencyCompensationRate);});
test('22 age product60 bonus exceeds50 and only partially compensates',()=>{const s=state(50);s.player.money=1e6;toggleProduct(s,'agecare');const younger=ageProductEfficiencyBonus(s);setAge(s,60);assert.ok(ageProductEfficiencyBonus(s)>younger);assert.ok(1+ageProductEfficiencyBonus(s)<getAgeWorkloadMultiplier(60));});
test('23 manual disable immediately removes speed bonus',()=>{const s=state(50);s.player.money=1e6;toggleProduct(s,'agecare');assert.ok(effectiveWorkSpeed(s)>20);toggleProduct(s,'agecare');assert.equal(effectiveWorkSpeed(s),20);});
test('24 renewal failure removes bonus',()=>{const s=state(50);s.player.money=1e6;toggleProduct(s,'agecare');s.player.money=0;renewProduct(s,'agecare');assert.equal(effectiveWorkSpeed(s),20);});
test('25 product expiry during active work preserves progress and changes next interval rate',()=>{const s=state(50);s.player.money=1e6;toggleProduct(s,'agecare');s.products.agecare.nextBillingWorldTime=9;s.player.money=0;const t=todo(s);t.workload=1000;startWork(s,t);advance(s,1);const target=s.currentTarget!;assert.equal(target.type,'WORK');if(target.type==='WORK'){close(target.progress,24.5);advance(s,1);close(target.progress,44.5);assert.equal(target.requirement,1000);}});
test('26 offline crossing40 preserves old work and snapshots released new work at40',()=>{const old=c.age.daysPerYear;try{c.age.daysPerYear=1;const s=state(39.999),root=todo(s);root.workload=1e8;startWork(s,root);const [pending]=createFollowUp(s,root,'CLIENT_REPLY',1,.12);const before=root.workload;settleOfflineMinutes(s,30);assert.ok(s.player.age>40);assert.equal(root.workload,before);assert.equal(root.ageWorkloadMultiplierAtCreation,1.1);assert.equal(pending.ageWorkloadMultiplierAtCreation,1.25);}finally{c.age.daysPerYear=old;}});
test('27 money and overdue within limit permit promotion',()=>{const s=state();s.player.money=10000;overdue(s,3);assert.ok(canPromote(s));assert.ok(applyAction(s,{type:'promote'}));});
test('28 overdue above limit rejects action without spending',()=>{const s=state();s.player.money=10000;overdue(s,4);assert.equal(canPromote(s),false);assert.equal(applyAction(s,{type:'promote'}),false);assert.equal(s.player.money,10000);});
test('29 insufficient money rejects despite clean work',()=>{const s=state();s.player.money=0;assert.equal(canPromote(s),false);});
test('30 current overdue counts and queue removal cannot unlock promotion',()=>{const s=state();s.player.money=1e6;overdue(s,4);startWork(s,s.todoQueue.shift()!);assert.equal(getUnresolvedOverdueWorkCount(s),4);assert.equal(canPromote(s),false);});
test('31 suspended overdue counts through food interruption',()=>{const s=state();s.player.money=1e6;overdue(s,4);startWork(s,s.todoQueue.shift()!);interruptWithFood(s);assert.equal(getUnresolvedOverdueWorkCount(s),4);assert.equal(canPromote(s),false);});
test('32 pending and project parents never count as overdue work',()=>{const s=state();createFollowUp(s,todo(s),'CLIENT_REPLY',1,20);createProject(s);assert.equal(getUnresolvedOverdueWorkCount(s),0);});
test('33 completion reduces overdue count',()=>{const s=state();overdue(s,4);const t=s.todoQueue.shift()!;t.workload=20;t.followUpDepth=2;startWork(s,t);advance(s,1);assert.equal(getUnresolvedOverdueWorkCount(s),3);});
test('34 completion down to threshold immediately unlocks promotion',()=>{const s=state();s.player.money=1e6;overdue(s,4);const t=s.todoQueue.shift()!;t.workload=20;t.followUpDepth=2;startWork(s,t);advance(s,1);assert.ok(canPromote(s));});
test('35 promotion retains work identities and current progress',()=>{const s=state();s.player.money=1e6;overdue(s,3);startWork(s,s.todoQueue.shift()!);const target=s.currentTarget,ids=s.todoQueue.map(t=>t.id);assert.ok(applyAction(s,{type:'promote'}));assert.equal(s.currentTarget,target);assert.deepEqual(s.todoQueue.map(t=>t.id),ids);});
test('36 promotion never refreshes due indices',()=>{const s=state();s.player.money=1e6;overdue(s,3);const before=s.todoQueue.map(t=>t.dueWorkdayIndex);applyAction(s,{type:'promote'});assert.deepEqual(s.todoQueue.map(t=>t.dueWorkdayIndex),before);});
test('37 duplicates of one work id cannot inflate overdue count',()=>{const s=state(),t=todo(s,true);s.todoQueue=[t];startWork(s,t);assert.equal(getUnresolvedOverdueWorkCount(s),1);});
test('38 due today and large clean queue do not restrict promotion',()=>{const s=state();s.player.money=1e6;s.todoQueue=Array.from({length:100},()=>todo(s));assert.ok(canPromote(s));});
test('39 aging changes workload neither reward nor deadline',()=>{const a=state(22),b=state(60),ta=todo(a),tb=todo(b);assert.equal(ta.deadlineWorkdays,tb.deadlineWorkdays);assert.equal(workReward(a,ta),workReward(b,tb));});
test('40 long simulation22 to61 has finite workloads and valid deadlines products promotion offline',()=>{const old=c.age.daysPerYear;try{c.age.daysPerYear=1;const s=state();s.player.money=1e6;toggleProduct(s,'agecare');s.player.upgrades.efficiency=5;s.player.upgrades.quality=5;advance(s,39*c.time.dayDuration);assert.ok(s.player.age>=61-1e-8);assert.ok(validateSave(s));assert.ok(s.runStatistics.completedWork>0);for(const t of [...s.todoQueue,...s.pendingFollowUps.flatMap(p=>p.tasksToCreate)]){assert.ok(Number.isFinite(t.workload)&&t.workload>0);close(t.workload,t.baseWorkload*t.ageWorkloadMultiplierAtCreation*t.rankWorkloadMultiplierAtCreation);assert.ok(['NORMAL','DUE_TODAY','OVERDUE','NO_DEADLINE'].includes(getDeadlineStatus(t,s)));}assert.ok(Number.isFinite(effectiveWorkSpeed(s)));assert.ok(Number.isFinite(ageProductEfficiencyBonus(s)));if(canPromote(s))assert.ok(applyAction(s,{type:'promote'}));const before=s.player.age;settleOfflineMinutes(s,30);assert.ok(s.player.age>before);assert.ok(validateSave(s));}finally{c.age.daysPerYear=old;}});

test('41 product40 shows twelve point five percent compensation',()=>{const s=state(40);s.player.money=1e6;toggleProduct(s,'agecare');close(ageProductEfficiencyBonus(s),.125);});
test('42 all work types share the same product processing modifier',()=>{const s=state(50);s.player.money=1e6;toggleProduct(s,'agecare');for(const source of ['NORMAL','BOSS','PROJECT','FOLLOW_UP','EVENT'] as const){const t=createTodo(s,c.work.templates[0],source);startWork(s,t);assert.equal(effectiveWorkSpeed(s),24.5);}const urgent=createTodo(s,c.work.templates.find(t=>t.id==='urgent')!);startWork(s,urgent);assert.equal(effectiveWorkSpeed(s),24.5);});
test('43 prestige removes age efficiency compensation',()=>{const s=state(60);s.player.money=1e6;toggleProduct(s,'agecare');assert.ok(ageProductEfficiencyBonus(s)>0);prestigeReset(s,true);assert.equal(ageProductEfficiencyBonus(s),0);});
test('44 old save gains workload metadata without changing workload requirement or progress',()=>{const s=state(50),t=todo(s);s.todoQueue=[t];startWork(s,structuredClone(t));if(s.currentTarget?.type==='WORK')s.currentTarget.progress=10;const raw=JSON.parse(JSON.stringify(s));for(const item of [raw.todoQueue[0],raw.currentTarget.todo])for(const key of ['baseWorkload','ageWorkloadMultiplierAtCreation','rankWorkloadMultiplierAtCreation'])delete item[key];const map=new Map([[c.save.key,JSON.stringify(raw)]]),storage={getItem:(k:string)=>map.get(k)??null,setItem:(k:string,v:string)=>{map.set(k,v);},removeItem:(k:string)=>{map.delete(k);}};const loaded=loadGame(storage,0);assert.equal(loaded.error,null);assert.equal(loaded.state.todoQueue[0].workload,t.workload);assert.equal(loaded.state.currentTarget?.type==='WORK'?loaded.state.currentTarget.progress:null,10);saveGame(loaded.state,storage,0);assert.equal(loadGame(storage,0).state.todoQueue[0].workload,t.workload);});
test('45 parent rank and age do not compound in followup',()=>{const s=state(50);s.career.rank=2;const root=todo(s),child=createFollowUp(s,root,'CLIENT_REPLY',1,0)[0];close(child.workload,root.baseWorkload*c.followUps.types.find(f=>f.type==='CLIENT_REPLY')!.workloadFactor*c.ranks[2].workloadMultiplier*1.45);});
test('46 active product age breakpoint is deterministic for large and small ticks',()=>{const old=c.age.daysPerYear;try{c.age.daysPerYear=1;const a=state(39.999);a.player.money=1e6;toggleProduct(a,'agecare');const root=todo(a);root.workload=10000;startWork(a,root);const b=structuredClone(a);advance(a,2);for(let i=0;i<20;i++)advance(b,.1);const pa=a.currentTarget?.type==='WORK'?a.currentTarget.progress:0,pb=b.currentTarget?.type==='WORK'?b.currentTarget.progress:0;close(pa,pb);close(a.player.age,b.player.age);assert.equal(a.world.rng,b.world.rng);}finally{c.age.daysPerYear=old;}});

// Legacy Boss Work regression: isolate the original Work outcome.
c.meeting.bossMeetingChanceOnEscapeFail=0;

