import test from 'node:test';
import assert from 'node:assert/strict';
import { gameConfig as c } from '../src/config/gameConfig';
import { initialState } from '../src/game/state/initialState';
import type { State, Target } from '../src/game/types';
import { advance } from '../src/game/engine/SimulationLoop';
import { syncWorld, routineAnchor } from '../src/game/time/worldTime';
import { startWork, startFood, ensureTarget, interruptWithFood, resumeSuspended, breakfastStart, breakfastCutoff, lunchStart, lunchEnd } from '../src/game/targets/targetManager';
import { createTodo } from '../src/game/work/todoManager';
import { createFollowUp, releasePending } from '../src/game/work/followUpManager';
import { followUpChance, followUpCount } from '../src/game/work/workQuality';
import { createProject, completeProjectSubtask, updateProjectClosures } from '../src/game/projects/projectManager';
import { toggleProduct } from '../src/game/products/productManager';
import { triggerEvent, eventEligible } from '../src/game/events/eventManager';
import { resolveBoss } from '../src/game/career/bossEvents';
import { settleOfflineMinutes } from '../src/game/time/offlineSimulation';
import { prestigeReset } from '../src/game/prestige/prestigeManager';
import { loadGame, saveGame } from '../src/game/save/saveGame';
const close=(a:number,b:number)=>assert.ok(Math.abs(a-b)<1e-6,`${a} != ${b}`);
function state(time=0) { const s=initialState(42,0);s.world.totalWorldTime=time;syncWorld(s);s.world.nextEventAt=1e8;s.needs.phase='MORNING';s.needs.projectRollProcessedRoutineId=0;s.needs.satietyUntil=1e8;return s; }
function work(s:State,duration:number,reward=100) { const todo=createTodo(s,c.work.templates[0]);todo.workload=duration*20;todo.baseReward=reward;todo.followUpDepth=c.followUps.maxFollowUpDepth;startWork(s,todo);return s.currentTarget!; }
function sleep(s:State,requirement:number) { s.needs.phase='SLEEP';s.currentTarget={id:'sleep',type:'SLEEP',name:'睡眠',requirement,progress:0,createdAt:s.world.totalWorldTime}; }
function buy(s:State,id:string) { s.player.money=10000;toggleProduct(s,id); }
function store() { const m=new Map<string,string>();return {getItem:(k:string)=>m.get(k)??null,setItem:(k:string,v:string)=>{m.set(k,v);},removeItem:(k:string)=>{m.delete(k);}}; }

test('01 WORK exact lunchStart completes before schedule with no delay',()=>{const s=state(19);work(s,1);advance(s,1);close(s.world.totalWorldTime,20);assert.equal(s.runStatistics.completedWork,1);assert.equal(s.currentTarget?.type,'FOOD');assert.equal(s.needs.phase,'LUNCH_FOOD');const logs=s.eventLog;assert.ok(logs.findIndex(n=>n.type==='工作')<logs.findIndex(n=>n.type==='飲食'));});
test('02 SLEEP stays until workStart rather than midnight',()=>{const s=state(59);sleep(s,1);advance(s,1);assert.equal(s.world.dayIndex,1);assert.equal(s.currentTarget?.type,'SLEEP');assert.equal('oversleepSeconds' in s.needs,false);advance(s,8);assert.notEqual(s.currentTarget?.type,'SLEEP');});
test('03 one advance crosses pending billing lunch and day boundaries deterministically',()=>{const a=state(19);buy(a,'eyes');a.products.eyes.nextBillingWorldTime=20;work(a,1);const root=createTodo(a,c.work.templates[0]);createFollowUp(a,root,'CLIENT_REPLY',1,1);const b=structuredClone(a);advance(a,42);for(let i=0;i<420;i++)advance(b,.1);assert.equal(a.world.dayIndex,1);close(a.player.money,b.player.money);assert.deepEqual(a.eventLog.map(n=>n.text),b.eventLog.map(n=>n.text));const texts=a.eventLog.map(n=>n.text);const done=texts.findIndex(t=>t.includes('完成，+$100'));const pending=texts.findIndex(t=>t.includes('客戶回信，待辦'));const billing=texts.findIndex(t=>t.includes('已續購'));assert.ok(done<pending&&pending<billing);});
test('04 same timestamp income pays renewal before billing fails',()=>{const s=state(59);buy(s,'eyes');s.products.eyes.nextBillingWorldTime=60;s.player.money=0;work(s,1,100);advance(s,1);assert.equal(s.products.eyes.active,true);close(s.player.money,15);assert.ok(s.eventLog.findIndex(n=>n.type==='工作')<s.eventLog.findIndex(n=>n.text.includes('已續購')));});
test('05 WORK crosses entire lunch window then still eats lunch',()=>{const s=state(18);work(s,12);advance(s,12);assert.equal(s.needs.lunchSettled,true);close(s.needs.lunchRest,0);assert.equal(s.needs.phase,'LUNCH_FOOD');advance(s,4);assert.equal(s.needs.phase,'AFTERNOON');});
test('06 lunch FOOD crosses lunchEnd and finishes without replacement rest',()=>{const s=state(26);startFood(s,'LUNCH');const id=s.currentTarget!.id;advance(s,2);assert.equal(s.currentTarget?.id,id);advance(s,2);assert.equal(s.needs.phase,'AFTERNOON');close(s.needs.lunchRest,0);assert.ok(s.needs.satietyUntil>30);});
test('07 WORK FOOD PROBLEM FOOD WORK preserves every progress',()=>{const s=state();buy(s,'wound');const original=work(s,20);advance(s,1);interruptWithFood(s);const food=s.currentTarget!.id;advance(s,1);triggerEvent(s,'wound',true);ensureTarget(s);advance(s,4);assert.equal(s.currentTarget?.id,food);close((s.currentTarget as {progress:number}).progress,30);advance(s,3);assert.equal(s.currentTarget?.id,original.id);close((s.currentTarget as {progress:number}).progress,20);});
test('08 resume discards all invalid problem layers until paid FOOD then WORK',()=>{const s=state();buy(s,'itch');buy(s,'wound');const original=work(s,20);interruptWithFood(s);const food=s.currentTarget!.id;triggerEvent(s,'itch',true);ensureTarget(s);triggerEvent(s,'wound',true);ensureTarget(s);s.debuffs=[];s.products.itch.active=false;s.products.wound.active=false;ensureTarget(s);assert.equal(s.currentTarget?.id,food);assert.equal(s.suspendedTargets.length,1);advance(s,4);assert.equal(s.currentTarget?.id,original.id);});
test('09 breakfast starts before cutoff and completes after cutoff',()=>{const s=state(7);s.needs.phase='BREAKFAST';s.needs.breakfastState='PENDING';ensureTarget(s);const id=s.currentTarget!.id;advance(s,1);assert.equal(s.currentTarget?.id,id);advance(s,3);assert.equal(s.needs.breakfastState,'COMPLETED');close(s.needs.satietyUntil,29);});
test('10 fixed window wakes at cutoff without artificial meal penalty',()=>{const s=state(59);sleep(s,10);advance(s,10);assert.equal(s.needs.breakfastState,'STARTED');assert.equal(s.currentTarget?.type,'FOOD');assert.ok(!s.debuffs.some(d=>d.type==='breakfast'));assert.equal(s.needs.satietyUntil,1e8);});
test('11 previous target delays unstarted breakfast beyond cutoff',()=>{const s=state(7);s.needs.phase='BREAKFAST';s.needs.breakfastState='PENDING';buy(s,'wound');triggerEvent(s,'wound',true);ensureTarget(s);advance(s,1);assert.equal(s.needs.breakfastState,'MISSED');assert.equal(s.currentTarget?.type,'PROBLEM');advance(s,3);assert.ok(s.eventLog.some(n=>n.text==='早餐時間已經過了。'));});
test('12 missed breakfast still rolls one project per routine independent of queue',()=>{const old=c.ranks[0].projectChance;try{c.ranks[0].projectChance=1;const s=state(9);s.needs.phase='BREAKFAST';s.needs.projectRollProcessedRoutineId=null;ensureTarget(s);assert.equal(s.projects.length,1);for(let i=0;i<10;i++)ensureTarget(s);assert.equal(s.projects.length,1);assert.equal(s.needs.projectRollProcessedRoutineId,0);}finally{c.ranks[0].projectChance=old;}});
test('13 A B/C D/E share a whole root tree reservation limit',()=>{const s=state();const a=createTodo(s,c.work.templates[0]);const [b,cc]=createFollowUp(s,a,'CLIENT_REPLY',2,0);const d=createFollowUp(s,b,'REWORK',2,0);const e=createFollowUp(s,cc,'MISSING_INFO',10,8);assert.equal(d.length,2);assert.equal(e.length,2);assert.equal(s.runStatistics.rootExtraTasks[a.rootId],6);assert.ok([...s.todoQueue,...s.pendingFollowUps.flatMap(p=>p.tasksToCreate)].every(t=>t.rootId===a.id));assert.equal(createFollowUp(s,a,'NEW_REQUEST',1,0).length,0);});
test('14 quality changes rework chance and conditional count but not business count',()=>{const low=state(),high=state();high.player.upgrades.quality=30;const t=createTodo(low,c.work.templates[2]);const bad=c.followUps.types[0],business=c.followUps.types[3];assert.ok(followUpChance(low,t,bad)>followUpChance(high,t,bad));assert.equal(followUpCount(low,t,bad,.99),3);assert.equal(followUpCount(high,t,bad,.99),1);assert.equal(followUpCount(low,t,business,.99),followUpCount(high,t,business,.99));});
test('15 project delivers once with pending current suspended extras then closes',()=>{const s=state();const p=createProject(s)!;const root=s.todoQueue[0];const extras=createFollowUp(s,root,'CLIENT_REPLY',1,20);while(p.status==='ACTIVE'){const todo=s.todoQueue.find(t=>t.subtaskId&&t.projectId===p.id)!;s.todoQueue=s.todoQueue.filter(t=>t.id!==todo.id);completeProjectSubtask(s,todo);}const money=s.player.money;updateProjectClosures(s);assert.equal(p.status,'DELIVERED');releasePending(s,true);const todo=s.todoQueue.find(t=>t.id===extras[0].id)!;s.todoQueue=s.todoQueue.filter(t=>t.id!==todo.id);startWork(s,todo);updateProjectClosures(s);assert.equal(p.status,'DELIVERED');interruptWithFood(s);updateProjectClosures(s);assert.equal(p.status,'DELIVERED');s.currentTarget=null;s.suspendedTargets=[];updateProjectClosures(s);assert.equal(p.status,'CLOSED');close(s.player.money,money);});
test('16 activation Day10/59 renews after exactly thirty complete days',()=>{const s=state(599);buy(s,'eyes');assert.equal(s.products.eyes.nextBillingWorldTime,2399);s.needs.phase='SLEEP';sleep(s,1e6);const spent=s.products.eyes.contributionStats.totalSpent;advance(s,1799);assert.equal(s.products.eyes.contributionStats.totalSpent,spent);advance(s,1);assert.equal(s.products.eyes.contributionStats.totalSpent,spent+85);assert.equal(s.products.eyes.nextBillingWorldTime,4199);});
test('17 dayDuration180 scales breakfast lunch offwork sleep anchors',()=>{const old=c.time.dayDuration;try{c.time.dayDuration=180;const s=state();close(breakfastStart(s),0);close(breakfastCutoff(s),24);close(lunchStart(s),60);close(lunchEnd(s),84);close(routineAnchor(s,c.time.offWorkAnchor),120);close(routineAnchor(s,c.time.sleepAnchor),150);const delayed=state(23);delayed.needs.phase='BREAKFAST';ensureTarget(delayed);assert.equal(delayed.needs.breakfastState,'STARTED');}finally{c.time.dayDuration=old;}});
test('18 boss game hour workload scales automatically sixty to one-eighty',()=>{const old=c.time.dayDuration;try{for(const duration of [60,180]){c.time.dayDuration=duration;const s=state();resolveBoss(s,true,false);close(s.todoQueue[0].workload/20,duration/24);}}finally{c.time.dayDuration=old;}});
test('19 sixteen real offline hours advances thirty-two world days',()=>{const s=state(17);sleep(s,1e6);assert.equal(settleOfflineMinutes(s,960),32);close(s.world.totalWorldTime,1937);assert.equal(s.runStatistics.offlineDays,32);});
test('20 fractional offline anti-age expiry protects only the effective segment',()=>{const s=state(59);buy(s,'agecare');s.products.agecare.nextBillingWorldTime=74;s.player.money=0;sleep(s,1e6);settleOfflineMinutes(s,960);close(s.player.ageProgressDays,32-.125);close(s.products.agecare.contributionStats.offlineAgeDaysProtected!,.125);assert.equal(s.products.agecare.active,false);});
test('21 context blocks eye and wound during sleep and tired is not random',()=>{const s=state();sleep(s,100);assert.equal(triggerEvent(s,'eyes'),null);assert.equal(triggerEvent(s,'wound'),null);assert.equal(eventEligible(s,c.events.definitions.find(e=>e.id==='itch')!),true);assert.equal(c.events.definitions.find(e=>e.id==='tired')!.randomEnabled,false);});
test('22 breakfast project boss are not repeated by repeated ensure in one routine',()=>{const old=c.ranks[0].projectChance;try{c.ranks[0].projectChance=1;const s=state();s.needs.phase='BREAKFAST';s.needs.projectRollProcessedRoutineId=null;for(let i=0;i<10;i++)ensureTarget(s);assert.equal(s.eventLog.filter(n=>n.text.startsWith('早餐：')).length,1);advance(s,4);for(let i=0;i<10;i++)ensureTarget(s);assert.equal(s.projects.length,1);s.currentTarget=null;s.needs.phase='AFTERNOON';s.world.totalWorldTime=40;syncWorld(s);for(let i=0;i<10;i++)ensureTarget(s);assert.equal(s.eventLog.filter(n=>n.text==='老闆正在找人……').length,1);}finally{c.ranks[0].projectChance=old;}});
test('23 load recomputes incorrect derived day and time from authority',()=>{const s=state(63);s.world.dayIndex=999;s.world.timeOfDay=999;const m=store();saveGame(s,m,0);const loaded=loadGame(m,0);assert.equal(loaded.error,null);assert.equal(loaded.state.world.dayIndex,1);close(loaded.state.world.timeOfDay,3);});
test('24 offline summary income spending money age todo projects product diffs reconcile',()=>{const s=state(19);buy(s,'eyes');s.products.eyes.nextBillingWorldTime=20;work(s,1,100);const before=structuredClone(s);settleOfflineMinutes(s,30);const x=s.offline.lastOfflineSummary!;assert.equal(x.realOfflineMinutes,30);assert.equal(x.gameDays,1);close(x.grossIncome,s.runStatistics.earned-before.runStatistics.earned);close(x.netMoneyChange,s.player.money-before.player.money);close(x.productSpending,Object.values(s.products).reduce((n,p)=>n+p.contributionStats.totalSpent-before.products[p.id].contributionStats.totalSpent,0));close(x.ageBefore,before.player.age);close(x.ageAfter,s.player.age);assert.equal(x.todoBefore,before.todoQueue.length);assert.equal(x.todoAfter,s.todoQueue.length);assert.ok(x.products.some(p=>p.id==='eyes'&&p.billingSpend===85));});
test('25 problem exact expiry and failed renewal still completes before cancellation',()=>{const s=state();buy(s,'wound');s.products.wound.nextBillingWorldTime=4;s.player.money=0;const t=work(s,20);triggerEvent(s,'wound',true);ensureTarget(s);advance(s,4);assert.equal(s.products.wound.contributionStats.problemResolvedCount,1);assert.equal(s.products.wound.active,false);assert.equal(s.currentTarget?.id,t.id);});
test('26 started quick FOOD survives product expiry while suspended',()=>{const s=state();buy(s,'quick');buy(s,'wound');s.player.settings.defaultFoodId='quick';s.products.quick.nextBillingWorldTime=1;s.player.money=8;work(s,20);interruptWithFood(s);const id=s.currentTarget!.id;triggerEvent(s,'wound',true);ensureTarget(s);advance(s,4);assert.equal(s.products.quick.active,false);assert.equal(s.currentTarget?.id,id);advance(s,2/3);assert.equal(s.products.quick.contributionStats.foodUses,1);});
test('27 prestige resets correction state and retains permanent levels',()=>{const s=state();buy(s,'eyes');settleOfflineMinutes(s,30);s.prestige.levels.workEfficiency=3;prestigeReset(s,true);assert.equal(s.needs.breakfastState,'PENDING');assert.equal(s.needs.projectRollProcessedRoutineId,null);assert.equal(s.products.eyes.nextBillingWorldTime,null);assert.equal(s.offline.lastOfflineSummary,null);assert.equal(s.prestige.levels.workEfficiency,3);});
test('28 template random selection respects enabled rank and weight',()=>{const old=c.projects.templates, chance=c.ranks[0].projectChance;try{c.projects.templates=[{...structuredClone(old[0]),id:'disabled',enabled:false},{...structuredClone(old[0]),id:'locked',rankRequirement:2},{...structuredClone(old[0]),id:'eligible',weight:3}];c.ranks[0].projectChance=1;const s=state(9);s.needs.phase='BREAKFAST';s.needs.projectRollProcessedRoutineId=null;ensureTarget(s);assert.equal(s.projects[0].templateId,'eligible');}finally{c.projects.templates=old;c.ranks[0].projectChance=chance;}});
test('29 boss completion at billing timestamp pays income before renewal',()=>{const s=state(59);buy(s,'eyes');s.products.eyes.nextBillingWorldTime=60;s.player.money=0;s.needs.phase='AFTERNOON';resolveBoss(s,true,false);const todo=s.todoQueue.shift()!;todo.workload=20;todo.followUpDepth=c.followUps.maxFollowUpDepth;startWork(s,todo);advance(s,1);assert.equal(s.products.eyes.active,true);assert.ok(s.eventLog.findIndex(n=>n.text.includes('完成，+$180'))<s.eventLog.findIndex(n=>n.text.includes('已續購')));});
test('30 exact debuff expiry permits already-completed problem first',()=>{const s=state();buy(s,'wound');work(s,20);const d=triggerEvent(s,'wound',true)!;d.expiresAt=4;ensureTarget(s);advance(s,4);assert.equal(s.products.wound.contributionStats.problemResolvedCount,1);close(s.products.wound.contributionStats.debuffSecondsSaved!,0);assert.ok(s.buffs.some(b=>b.protectionTag==='wound'));});
test('31 additive V2 migration preserves run and permanent data',()=>{const s=state(10);s.player.money=543;s.prestige.levels.workEfficiency=3;const raw=JSON.parse(JSON.stringify(s));delete raw.needs.breakfastState;delete raw.needs.projectRollProcessedRoutineId;delete raw.offline.lastOfflineSummary;delete raw.offline.summaryDismissed;for(const p of Object.values(raw.products) as any[]){delete p.nextBillingWorldTime;p.paidDaysRemaining=10;p.contributionStats={uses:2,savedSeconds:6,avoidedImpact:0,offlineAgeDaysProtected:0,totalSpent:80};}raw.products.quick.active=true;const m=store();m.setItem(c.save.key,JSON.stringify(raw));const loaded=loadGame(m,0);assert.equal(loaded.error,null);assert.equal(loaded.state.player.money,543);assert.equal(loaded.state.prestige.levels.workEfficiency,3);assert.equal(loaded.state.products.quick.nextBillingWorldTime,610);assert.equal(loaded.state.products.quick.contributionStats.foodUses,2);});
test('32 event context overrides and rank time tag restrictions are data-driven',()=>{const e=c.events.definitions.find(e=>e.id==='itch')!,old=structuredClone(e);try{e.contextModifiers={SLEEP:{lifeSpeed:-.2}};e.allowedRanks=[0];e.allowedTimeRanges=[{start:10,end:20}];const s=state(12);sleep(s,100);const d=triggerEvent(s,'itch')!;assert.equal(d.modifiers.lifeSpeed,-.2);s.world.totalWorldTime=25;syncWorld(s);assert.equal(eventEligible(s,e),false);s.world.totalWorldTime=12;syncWorld(s);s.career.rank=1;assert.equal(eventEligible(s,e),false);}finally{Object.assign(e,old);}});
test('33 offline billing spending stays correct for meal already paid before offline',()=>{const s=state();buy(s,'quick');s.player.settings.defaultFoodId='quick';interruptWithFood(s);startFood(s,'EXTRA');const spent=s.products.quick.contributionStats.totalSpent;settleOfflineMinutes(s,30);const delta=s.offline.lastOfflineSummary!.products.find(p=>p.id==='quick')!;assert.equal(delta.billingSpend,0);close(delta.stats.totalSpent,s.products.quick.contributionStats.totalSpent-spent);});
test('34 routine sleep imbalance resolves with sleep product without extra random tired debuff',()=>{const s=state(59);buy(s,'sleep');sleep(s,10);advance(s,10);assert.ok(s.debuffs.some(d=>d.type==='sleep-window'));assert.ok(!s.debuffs.some(d=>d.type==='tired'));assert.equal(s.currentTarget?.type,'PROBLEM');advance(s,4);assert.ok(!s.debuffs.some(d=>d.type==='sleep-window'));assert.equal(s.products.sleep.contributionStats.problemResolvedCount,1);});
test('35 legacy suspended breakfast stays started after cutoff on load',()=>{const s=state(7);buy(s,'wound');s.needs.phase='BREAKFAST';startFood(s,'BREAKFAST');triggerEvent(s,'wound',true);ensureTarget(s);const raw=JSON.parse(JSON.stringify(s));delete raw.needs.breakfastState;delete raw.needs.projectRollProcessedRoutineId;const m=store();m.setItem(c.save.key,JSON.stringify(raw));const loaded=loadGame(m,0);assert.equal(loaded.error,null);assert.equal(loaded.state.needs.breakfastState,'STARTED');advance(loaded.state,8);assert.equal(loaded.state.needs.breakfastState,'COMPLETED');assert.ok(!loaded.state.eventLog.some(n=>n.text.includes('錯過早餐')));});
test('36 resolver losing matching tag invalidates pending problem without progress loss',()=>{const p=c.products.definitions.find(p=>p.id==='wound')!,tags=p.tags;try{const s=state();buy(s,'wound');const original=work(s,20);triggerEvent(s,'wound',true);ensureTarget(s);p.tags=['different'];ensureTarget(s);assert.equal(s.currentTarget?.id,original.id);assert.equal(s.suspendedTargets.length,0);close((s.currentTarget as {progress:number}).progress,0);}finally{p.tags=tags;}});

// Legacy Boss Work regression: isolate the original Work outcome.
c.meeting.bossMeetingChanceOnEscapeFail=0;

