import test from 'node:test';
import assert from 'node:assert/strict';
import {gameConfig as c} from '../src/config/gameConfig';
import {initialState} from '../src/game/state/initialState';
import {advance} from '../src/game/engine/SimulationLoop';
import {applyAction} from '../src/game/engine/actions';
import {catchChance,escapeChance,bossSeverity,resolveBoss,activeMandatoryBoss} from '../src/game/career/bossEvents';
import {effectiveWorkSpeed,effectiveWorkQuality,getLifeManagementValue,originalWorkReward} from '../src/game/work/workStats';
import {getRunUpgradeCost} from '../src/game/work/progression';
import {getPermanentMultiplier,getPrestigeUpgradeCost} from '../src/game/prestige/permanentUpgrades';
import {ensureTarget,interruptWithFood} from '../src/game/targets/targetManager';
import {sleepRatio,sleepEffect,settleSleepWindow} from '../src/game/targets/sleepWindow';
import {loadGame,saveGame} from '../src/game/save/saveGame';
import {syncWorld} from '../src/game/time/worldTime';
import {createTodo} from '../src/game/work/todoManager';
const close=(a:number,b:number)=>assert.ok(Math.abs(a-b)<1e-6,`${a} != ${b}`);
function state(now=40){const s=initialState(42,0);s.world.totalWorldTime=now;syncWorld(s);s.world.nextEventAt=1e9;s.needs.phase='AFTERNOON';s.needs.satietyUntil=1e9;s.needs.projectRollProcessedRoutineId=0;return s;}
for(const [lv,attention,income] of [[0,.1,1],[45,1,1.45],[65,1.4,1.65],[95,2,1.95],[115,2.4,2.15]])test(`flattery Lv${lv} attention and unified work income`,()=>{const s=state();s.player.upgrades.flattery=lv;close(catchChance(s),attention);resolveBoss(s,true,false);const t=s.todoQueue[0];close(originalWorkReward(s,t),Math.round(t.baseReward*income));});
for(const [attention,roll,severity] of [[1,.9,1],[1.4,.39,2],[1.4,.41,1],[2,.9,2],[2.4,.39,3],[2.4,.41,2],[.1,.11,0]])test(`severity ${attention}/${roll} = ${severity}`,()=>assert.equal(bossSeverity(attention,roll),severity));
for(const severity of [1,2,3,5])test(`boss severity${severity} workload/reward each once rank age flattery prestige`,()=>{const s=state();s.player.age=60;s.career.rank=4;s.player.upgrades.flattery=(severity-.1)/.02;s.prestige.levels.workReward=2;s.prestige.levels.bossTaskReward=1;resolveBoss(s,true,false);const t=s.todoQueue[0];assert.equal(s.todoQueue.length,1);assert.equal(t.bossSeverity,severity);close(t.workload,50*severity*3*1.7);close(originalWorkReward(s,t),Math.round(180*severity*25*(1+s.player.upgrades.flattery*.01)*1.1**2*1.1));});
for(const lv of [0,1,100,300])test(`raw linear stats Lv${lv}`,()=>{const s=state();s.player.upgrades.efficiency=lv;s.player.upgrades.quality=lv;s.player.upgrades.lifeManagement=lv;close(effectiveWorkSpeed(s),20+lv);close(effectiveWorkQuality(s),10+lv);close(getLifeManagementValue(s),lv);});
for(const level of [0,1,10,50,100,101,150,200,201,250,300,500,1000])test(`run cost Lv${level} all abilities finite integer monotonic`,()=>{for(const id of Object.keys(c.upgrades) as (keyof typeof c.upgrades)[]){const value=getRunUpgradeCost(id,level);assert.ok(Number.isFinite(value)&&Number.isInteger(value)&&value>0);assert.ok(value>=getRunUpgradeCost(id,Math.max(0,level-1)));if(level===0)assert.equal(value,c.upgrades[id].baseCost);}});
test('run upgrades beyond1000 have no gameplay cap',()=>{const s=state();s.player.upgrades.efficiency=1000;s.player.money=getRunUpgradeCost('efficiency',1000)*2;assert.equal(applyAction(s,{type:'upgrade',id:'efficiency'}),true);assert.equal(s.player.upgrades.efficiency,1001);});
for(const level of [0,1,5,10,25])test(`permanent formula Lv${level}`,()=>{const multiplier=getPermanentMultiplier('workEfficiency',level),cost=getPrestigeUpgradeCost('workEfficiency',level);assert.ok(Number.isFinite(multiplier)&&Number.isFinite(cost)&&Number.isInteger(cost));close(multiplier,1.1**level);if(level>0){assert.ok(multiplier>getPermanentMultiplier('workEfficiency',level-1));assert.ok(cost>getPrestigeUpgradeCost('workEfficiency',level-1));}});
test('slacking increases success at any rank and rank reduces success without clamp',()=>{for(const rank of [0,1,2,3,4]){const s=state();s.career.rank=rank;let previous=0;for(const lv of [0,100,500,1000]){s.player.upgrades.slacking=lv;assert.ok(escapeChance(s)>previous&&escapeChance(s)<1);previous=escapeChance(s);}}for(const lv of [0,100,500,1000]){const s=state();s.player.upgrades.slacking=lv;let previous=1;for(const rank of [0,1,2,3,4]){s.career.rank=rank;assert.ok(escapeChance(s)<previous);previous=escapeChance(s);}}close(escapeChance(state()),.15);});
for(const [caught,escaped] of [[false,false],[true,true],[true,false]])test(`evening order ${caught}/${escaped} dinner first`,()=>{const s=state();resolveBoss(s,caught,escaped);ensureTarget(s);assert.equal(s.currentTarget?.type,'FOOD');advance(s,4);if(caught&&!escaped){assert.equal(s.currentTarget?.type,'WORK');assert.ok(activeMandatoryBoss(s));}else {assert.equal(s.needs.phase,'WAIT');advance(s,6);assert.equal(s.currentTarget?.type,'SLEEP');}});
test('mandatory overtime crosses sleep and next workStart with same identity progress and zero sleep; no second boss',()=>{const s=state();resolveBoss(s,true,false);const todo=s.todoQueue[0];todo.workload=10000;ensureTarget(s);advance(s,60);assert.equal(s.currentTarget?.type==='WORK'?s.currentTarget.todo.id:null,todo.id);assert.ok(s.currentTarget&&'progress' in s.currentTarget&&s.currentTarget.progress>0);assert.equal(s.needs.sleep.lastRatio,0);assert.ok(s.debuffs.some(d=>d.type==='sleep-window'));resolveBoss(s,true,false);assert.equal(s.todoQueue.filter(t=>t.mandatoryOvertime).length,0);assert.equal(activeMandatoryBoss(s)?.id,todo.id);});
test('mandatory work preserves progress through extra food interruption',()=>{const s=state();resolveBoss(s,true,false);ensureTarget(s);advance(s,4.5);const t=s.currentTarget!;const progress='progress' in t?t.progress:0;interruptWithFood(s);advance(s,4);assert.equal(s.currentTarget?.id,t.id);close('progress' in s.currentTarget!?s.currentTarget.progress:0,progress);});
for(const ratio of [1,.75,.5,0])test(`sleep ratio${ratio} duration output and workStart termination`,()=>{const s=state(68-18*ratio);s.needs.phase='SLEEP';s.needs.sleep.windowStart=50;s.needs.sleep.windowEnd=68;ensureTarget(s);if(ratio>0)advance(s,18*ratio);else ensureTarget(s);close(s.needs.sleep.lastRatio,ratio);assert.notEqual(s.currentTarget?.type,'SLEEP');assert.equal('oversleepSeconds' in s.needs,false);const e=sleepEffect(ratio);close(s.needs.sleep.speedModifier,e.speedModifier);});
test('sleep curve interpolates continuously and caps above recovery',()=>{close(sleepEffect(.75).speedModifier,-.075);assert.ok(sleepEffect(.751).speedModifier>sleepEffect(.75).speedModifier);close(sleepEffect(20).speedModifier,.05);});
test('sleep rate deliberately independent from life management',()=>{const a=state(50),b=state(50);a.needs.phase=b.needs.phase='SLEEP';b.player.upgrades.lifeManagement=1000;advance(a,9);advance(b,9);close(sleepRatio(a),sleepRatio(b));});
test('all formal work sources use one flattery reward pipeline',()=>{for(const source of ['NORMAL','FOLLOW_UP','PROJECT','BOSS','EVENT'] as const){const s=state();s.player.upgrades.flattery=65;const t=createTodo(s,{...c.work.templates[0],reward:100},source);assert.equal(originalWorkReward(s,t),165);}});
test('normal evening with enough time entertains then sleeps in window',()=>{const s=state();s.player.upgrades.lifeManagement=10;resolveBoss(s,false,false);ensureTarget(s);advance(s,4);assert.equal(s.currentTarget?.type,'ENTERTAINMENT');advance(s,3);assert.equal(s.currentTarget?.type,'SLEEP');assert.equal(s.needs.sleep.duration,0);advance(s,3);assert.equal(s.needs.sleep.duration,0);advance(s,1);close(s.needs.sleep.duration,1);});
test('unfinished entertainment cannot postpone workStart',()=>{const s=state(67);s.needs.phase='ENTERTAINMENT';s.currentTarget={id:'old-ent',name:'ent',type:'ENTERTAINMENT',requirement:100,progress:0,createdAt:67};advance(s,1);assert.notEqual(s.currentTarget?.type,'ENTERTAINMENT');assert.ok(!s.buffs.some(b=>b.id==='relaxed'));});
test('overtime finishing next morning returns to daytime rather than repeating dinner',()=>{const s=state();resolveBoss(s,true,false);const todo=s.todoQueue[0];todo.workload=520;todo.followUpDepth=2;ensureTarget(s);advance(s,4);s.needs.satietyUntil=1e9;advance(s,24);assert.equal(activeMandatoryBoss(s)?.id,todo.id);advance(s,3);assert.equal(activeMandatoryBoss(s),undefined);assert.equal(s.needs.phase,'BREAKFAST');assert.equal(s.needs.breakfastState,'STARTED');assert.ok(!s.eventLog.some(n=>n.type==='娛樂'));});
test('sleep with Problem interruption counts only actual sleeping time and drops suspended sleep at workStart',()=>{const s=state(50);s.needs.phase='SLEEP';ensureTarget(s);const sleep=s.currentTarget!;s.suspendedTargets.push({target:sleep,phase:'SLEEP'});s.currentTarget={id:'food',type:'FOOD',name:'normal',foodId:'normal',meal:'EXTRA',requirement:120,progress:0,createdAt:50};advance(s,18);close(s.needs.sleep.lastRatio,14/18);assert.ok(!s.suspendedTargets.some(x=>x.target.type==='SLEEP'));});
test('overflowing run cost stays finite and does not reduce price',()=>{for(const level of [100000,1000000]){const cost=getRunUpgradeCost('efficiency',level);assert.equal(cost,Number.MAX_VALUE);assert.ok(cost>=getRunUpgradeCost('efficiency',level-1));}});
test('legacy sleep already beyond old workStart is cancelled without losing levels',()=>{const s=state(80);s.needs.phase='SLEEP';s.currentTarget={id:'old-sleep',type:'SLEEP',name:'sleep',requirement:100,progress:20,createdAt:50};s.prestige.levels.workQuality=10;const raw=JSON.parse(JSON.stringify(s));delete raw.needs.sleep;raw.needs.oversleepSeconds=20;const storage={getItem:()=>JSON.stringify(raw),setItem:()=>{},removeItem:()=>{}};const loaded=loadGame(storage,0);assert.equal(loaded.error,null);assert.notEqual(loaded.state.currentTarget?.type,'SLEEP');assert.equal(loaded.state.prestige.levels.workQuality,10);assert.equal(loaded.state.needs.routineDay,1);});
test('unfinished old sleep before workStart migrates to fixed window rather than original requirement',()=>{const s=state(63);s.needs.phase='SLEEP';s.currentTarget={id:'old-sleep',type:'SLEEP',name:'sleep',requirement:100,progress:10,createdAt:50};const raw=JSON.parse(JSON.stringify(s));delete raw.needs.sleep;raw.needs.oversleepSeconds=3;const storage={getItem:()=>JSON.stringify(raw),setItem:()=>{},removeItem:()=>{}};const loaded=loadGame(storage,0);assert.equal(loaded.error,null);assert.equal(loaded.state.needs.sleep.windowEnd,68);advance(loaded.state,5);assert.notEqual(loaded.state.currentTarget?.type,'SLEEP');});
test('high permanent levels survive save/reload; legacy boss/sleep migration retains money levels work progress',()=>{const s=state(59);resolveBoss(s,true,false);s.prestige.levels.workEfficiency=25;s.player.upgrades.efficiency=500;s.player.money=1234;const t=s.todoQueue.shift()!;s.currentTarget={id:'old-work',name:t.name,type:'WORK',todo:t,requirement:t.workload,progress:10,createdAt:58};const raw=JSON.parse(JSON.stringify(s));delete raw.needs.sleep;raw.needs.oversleepSeconds=3;delete raw.currentTarget.todo.bossSeverity;delete raw.currentTarget.todo.mandatoryOvertime;const m=new Map<string,string>();const storage={getItem:(k:string)=>m.get(k)??null,setItem:(k:string,v:string)=>{m.set(k,v)},removeItem:(k:string)=>{m.delete(k)}};storage.setItem(c.save.key,JSON.stringify(raw));const loaded=loadGame(storage,0);assert.equal(loaded.error,null);assert.equal(loaded.state.player.money,1234);assert.equal(loaded.state.prestige.levels.workEfficiency,25);assert.equal(loaded.state.player.upgrades.efficiency,500);assert.equal(loaded.state.currentTarget?.type==='WORK'?loaded.state.currentTarget.progress:null,10);assert.equal(activeMandatoryBoss(loaded.state)?.bossSeverity,1);saveGame(loaded.state,storage,0);assert.equal(loadGame(storage,0).state.prestige.levels.workEfficiency,25);});

// Legacy Boss Work regression: Meeting outcome disabled only in this test process.
c.meeting.bossMeetingChanceOnEscapeFail=0;

