import {createTodo} from '../src/game/work/todoManager';
import test,{afterEach} from 'node:test';
import assert from 'node:assert/strict';
import {gameConfig as c} from '../src/config/gameConfig';
import {initialState} from '../src/game/state/initialState';
import {advance} from '../src/game/engine/SimulationLoop';
import {ensureTarget,targetRate,startWork} from '../src/game/targets/targetManager';
import {checkPromotionWorkStart,getPromotionQualificationStats,promotionEligible,startPromotionAssignment} from '../src/game/career/promotionAssignment';
import {effectiveWorkSpeed} from '../src/game/work/workStats';
import {syncWorld} from '../src/game/time/worldTime';
import {saveGame,loadGame,validateSave} from '../src/game/save/saveGame';
import {prestigeReset} from '../src/game/prestige/prestigeManager';
import {applyAction} from '../src/game/engine/actions';
import type {State,PromotionTarget} from '../src/game/types';
const config=structuredClone(c);afterEach(()=>Object.assign(c,structuredClone(config)));
const close=(a:number,b:number)=>assert.ok(Math.abs(a-b)<1e-7,`${a} != ${b}`);
function quiet(rank=0){c.meeting.normalChanceByRank=[0,0,0,0,0];const s=initialState(42,0);s.career.rank=rank;s.player.money=1e6;s.world.totalWorldTime=8;syncWorld(s);s.world.nextEventAt=1e9;s.needs.satietyUntil=1e9;s.needs.phase='MORNING';s.needs.breakfastAnchorEligible=false;s.needs.projectRollProcessedRoutineId=0;const q=c.promotionQualification.requirements[rank];if(q){s.player.upgrades.efficiency=q.efficiency-c.economy.baseWorkSpeed;s.player.upgrades.quality=q.quality-c.economy.baseQuality;}return s;}
function active(s=quiet()){checkPromotionWorkStart(s);s.promotion.pending=true;s.world.totalWorldTime=44;syncWorld(s);assert.ok(startPromotionAssignment(s));return s;}
function target(s:State){assert.equal(s.currentTarget?.type,'PROMOTION');return s.currentTarget as PromotionTarget;}
function memory(){const values=new Map<string,string>();return {getItem:(k:string)=>values.get(k)??null,setItem:(k:string,v:string)=>{values.set(k,v);},removeItem:(k:string)=>{values.delete(k);}};}
for(let rank=0;rank<4;rank++)test(`A/B exact thresholds rank${rank}, below E or Q rejected`,()=>{for(const field of ['efficiency','quality'] as const){const s=quiet(rank);s.player.upgrades[field]--;checkPromotionWorkStart(s);assert.equal(s.promotion.status,'NOT_ELIGIBLE');}const s=quiet(rank),rng=s.world.rng;checkPromotionWorkStart(s);assert.equal(s.promotion.status,'SCHEDULED');assert.equal(s.world.rng,rng);});
test('Qualification includes Permanent, excludes transient/age/product/sleep/target/slacking/flattery',()=>{const s=quiet();s.prestige.levels.workEfficiency=1;s.prestige.levels.workQuality=2;const before=getPromotionQualificationStats(s);s.player.age=60;s.player.upgrades.flattery=500;s.player.upgrades.slacking=500;s.buffs.push({id:'x',name:'x',expiresAt:1e9,modifiers:{workSpeed:5,quality:5}});s.needs.sleep.speedModifier=-.3;s.needs.sleep.qualityModifier=-.3;assert.deepEqual(getPromotionQualificationStats(s),before);assert.ok(before.efficiency>26&&before.quality>16);});
test('C/D E60 ×0.8 =48 fails E50 without changing actual work speed',()=>{const s=quiet();s.player.upgrades.efficiency=40;s.player.upgrades.quality=100;c.promotionQualification.requirements[0].efficiency=50;applyAction(s,{type:'lowProfile',value:true});close(getPromotionQualificationStats(s).evaluatedEfficiency,48);close(effectiveWorkSpeed(s),60);assert.equal(promotionEligible(s),false);checkPromotionWorkStart(s);assert.equal(s.promotion.status,'NOT_ELIGIBLE');});
test('E/F toggle mid-day does not create assessment; OFF applies next WorkStart',()=>{const s=quiet();s.promotion.lowProfileEnabled=true;checkPromotionWorkStart(s);s.world.totalWorldTime=12;syncWorld(s);applyAction(s,{type:'lowProfile',value:false});checkPromotionWorkStart(s);assert.equal(s.promotion.status,'NOT_ELIGIBLE');s.world.totalWorldTime=68;syncWorld(s);checkPromotionWorkStart(s);assert.equal(s.promotion.status,'SCHEDULED');});
test('G/H scheduled/active cannot be cancelled or slowed by Low Profile',()=>{const s=quiet();checkPromotionWorkStart(s);applyAction(s,{type:'lowProfile',value:true});assert.equal(s.promotion.status,'SCHEDULED');s.promotion.pending=true;s.world.totalWorldTime=44;startPromotionAssignment(s);const t=target(s),speed=targetRate(s,t),req=t.requirement;applyAction(s,{type:'lowProfile',value:false});close(targetRate(s,t),speed);close(t.requirement,req);assert.equal(s.promotion.status,'ACTIVE');});
test('I/J/K replaces Boss check before Dinner, starts only after Dinner, Normal Meeting config unchanged',()=>{const s=quiet();s.player.upgrades.flattery=500;c.meeting.bossMeetingChanceOnEscapeFail=1;checkPromotionWorkStart(s);s.world.totalWorldTime=40;syncWorld(s);s.needs.phase='AFTERNOON';const rng=s.world.rng;ensureTarget(s);assert.equal(s.currentTarget?.type,'FOOD');assert.equal(s.promotion.status,'SCHEDULED');assert.equal(s.promotion.pending,true);assert.equal(s.needs.bossChecked,true);assert.equal(s.world.rng,rng);advance(s,4);target(s);assert.equal(s.meetings.pendingBoss,null);assert.equal(s.todoQueue.filter(t=>t.mandatoryOvertime).length,0);});
for(let rank=0;rank<4;rank++)test(`L/M fixed workload rank${rank} independent of Age and Rank scaling`,()=>{const s=quiet(rank);s.player.age=60;active(s);close(target(s).requirement,[130,209,330,507][rank]);});
test('N/O/P/Q success no Todo/FU/Project/ordinary reward; preserves existing arrays and charges existing cost',()=>{const s=active(),money=s.player.money,earned=s.runStatistics.earned,completed=s.runStatistics.completedWork,projects=structuredClone(s.projects),pending=structuredClone(s.pendingFollowUps);advance(s,5);assert.equal(s.career.rank,1);close(s.player.money,money-c.ranks[1].promotionCost);close(s.runStatistics.earned,earned);assert.equal(s.runStatistics.completedWork,completed);assert.deepEqual(s.projects,projects);assert.deepEqual(s.pendingFollowUps,pending);assert.equal(s.todoQueue.length,0);});
test('R higher actual Efficiency completes same workload faster',()=>{for(const scale of [1,1.2,1.5]){const s=active();s.buffs.push({id:'speed',name:'speed',expiresAt:1e9,modifiers:{workSpeed:scale-1}});const duration=130/(26*scale);advance(s,duration-0.001);target(s);advance(s,.001);assert.equal(s.career.rank,1);close(s.world.totalWorldTime,44+duration);}});
test('S exact WorkStart completion succeeds before failure',()=>{const s=active();s.world.totalWorldTime=67;syncWorld(s);target(s).progress=104;s.promotion.progress=104;advance(s,1);assert.equal(s.career.rank,1);assert.equal(s.promotion.retryAvailableWorkday,null);});
test('T/U deadline incomplete fails without fine or preserved progress; cooldown3 workdays',()=>{const s=active();target(s).requirement=1e6;s.promotion.requirement=1e6;const money=s.player.money;advance(s,24);assert.equal(s.career.rank,0);assert.equal(s.promotion.status,'COOLDOWN');assert.equal(s.promotion.retryAvailableWorkday,4);assert.equal(s.promotion.progress,0);close(s.player.money,money);assert.notEqual(s.currentTarget?.type,'PROMOTION');assert.equal(s.pendingFollowUps.length,0);});
test('V cooldown expires at third subsequent WorkStart and identical workload retry',()=>{const s=active();target(s).requirement=1e6;advance(s,24);for(const now of [128,188]){s.world.totalWorldTime=now;syncWorld(s);checkPromotionWorkStart(s);assert.equal(s.promotion.status,'COOLDOWN');}s.world.totalWorldTime=248;syncWorld(s);checkPromotionWorkStart(s);assert.equal(s.promotion.status,'SCHEDULED');s.promotion.pending=true;s.world.totalWorldTime=284;syncWorld(s);startPromotionAssignment(s);close(target(s).requirement,130);});
test('completed but spent money: FAILED_REQUIREMENT, no negative money or rank-up',()=>{const s=active();s.player.money=0;advance(s,5);assert.equal(s.career.rank,0);assert.equal(s.player.money,0);assert.equal(s.promotion.status,'FAILED_REQUIREMENT');assert.ok(s.promotion.failureReason);});
test('W save/reload preserves assessment progress/deadline/metadata',()=>{const s=active();advance(s,2);const store=memory();saveGame(s,store,0);assert.ok(validateSave(s));const r=loadGame(store,0);assert.equal(r.error,null);assert.deepEqual(r.state.promotion,s.promotion);assert.deepEqual(r.state.currentTarget,s.currentTarget);advance(r.state,3);assert.equal(r.state.career.rank,1);});
test('old Save additive migration does not change existing gameplay data',()=>{const s=quiet(),store=memory();const old=structuredClone(s) as any;delete old.promotion;store.setItem(c.save.key,JSON.stringify(old));const r=loadGame(store,0);assert.equal(r.error,null);assert.equal(r.state.promotion.lowProfileEnabled,false);for(const field of ['player','career','todoQueue','currentTarget','projects','meetings','needs','products'] as const)assert.deepEqual(r.state[field],s[field]);});
test('X Prestige clears all assessment/low profile/cooldown',()=>{const s=active();s.promotion.lowProfileEnabled=true;s.promotion.retryAvailableWorkday=7;prestigeReset(s,true);assert.equal(s.promotion.lowProfileEnabled,false);assert.equal(s.promotion.assignmentId,null);assert.equal(s.promotion.retryAvailableWorkday,null);assert.equal(s.career.rank,0);});
test('Y max Rank never generates assessment',()=>{const s=quiet(4);checkPromotionWorkStart(s);assert.equal(s.promotion.status,'MAX_RANK');assert.equal(s.promotion.scheduledWorkday,null);});
test('offline pauses active assessment progress and deadline, no rank-up; resumes online',()=>{const s=active();advance(s,2);const t=structuredClone(target(s));advance(s,60,{offline:true});assert.equal(s.career.rank,0);close(target(s).progress,t.progress);close(target(s).deadlineWorldTime,t.deadlineWorldTime+60);assert.equal(s.promotion.status,'ACTIVE');advance(s,3);assert.equal(s.career.rank,1);});
test('offline never schedules a new assessment for qualified player',()=>{const s=quiet();advance(s,120,{offline:true});assert.equal(s.career.rank,0);assert.equal(s.promotion.assignmentId,null);assert.equal(s.promotion.status,'NOT_ELIGIBLE');});
test('batch vs tiny steps same assessment progress, result and RNG',()=>{const a=active(),b=structuredClone(a);advance(a,6);for(let i=0;i<120;i++)advance(b,.05);assert.equal(a.career.rank,b.career.rank);assert.equal(a.world.rng,b.world.rng);close(a.player.money,b.player.money);close(a.world.totalWorldTime,b.world.totalWorldTime);});

test('late ordinary Work survives OffWork, notification pending then Dinner then assessment',()=>{const s=quiet();checkPromotionWorkStart(s);s.world.totalWorldTime=39;syncWorld(s);s.needs.phase='AFTERNOON';const todo=createTodo(s,{...c.work.templates[0],workload:78});startWork(s,todo);const id=s.currentTarget!.id;advance(s,1);assert.equal(s.currentTarget!.id,id);assert.equal(s.promotion.pending,true);advance(s,2);assert.equal(s.currentTarget?.type,'FOOD');advance(s,4);target(s);close(target(s).startedAt,46);});
test('pending notification survives midnight and WorkStart until current work done',()=>{const s=quiet();checkPromotionWorkStart(s);s.world.totalWorldTime=39;syncWorld(s);s.needs.phase='AFTERNOON';startWork(s,createTodo(s,{...c.work.templates[0],workload:3000}));advance(s,30);assert.equal(s.promotion.pending,true);assert.equal(s.currentTarget?.type,'WORK');assert.equal(s.needs.bossChecked,true);});
test('suspended assessment deadline fails while other target is processing',()=>{const s=active(),t=target(s);s.suspendedTargets.push({target:t,phase:s.needs.phase});s.currentTarget={id:'food-pause',type:'FOOD',name:'Food',createdAt:44,requirement:100000,progress:0,foodId:'normal',meal:'EXTRA'};advance(s,24);assert.equal(s.promotion.status,'COOLDOWN');assert.equal(s.suspendedTargets.some(x=>x.target.type==='PROMOTION'),false);assert.equal(s.career.rank,0);});
test('completion after new overdue work exceeds limit fails existing transaction',()=>{const s=active();for(let i=0;i<4;i++){const todo=createTodo(s,c.work.templates[0]);todo.assignmentWorkdayIndex=-1;todo.deadlineWorkdays=0;todo.dueWorkdayIndex=-1;s.todoQueue.push(todo);}advance(s,5);assert.equal(s.promotion.status,'FAILED_REQUIREMENT');assert.equal(s.career.rank,0);});
test('offline scheduled event stays scheduled without assignment or rank-up',()=>{const s=quiet();checkPromotionWorkStart(s);advance(s,120,{offline:true});assert.equal(s.career.rank,0);assert.equal(s.promotion.status,'SCHEDULED');assert.equal(s.promotion.assignmentId,null);assert.equal(s.promotion.scheduledWorkday,2);assert.equal(s.promotion.lastCheckedWorkday,2);});
test('zero/invalid offline delta never changes State',()=>{for(const delta of [0,-1,NaN,Infinity]){const s=active(),before=structuredClone(s);advance(s,delta,{offline:true});assert.deepEqual(s,before);}});
test('Debug cannot inject ordinary Boss outcome into scheduled/active assessment evening',()=>{const s=active();for(const command of ['bossCatch','bossMeeting','escapeSuccess','escapeFail'])assert.equal(applyAction(s,{type:'debug',command}),false);assert.equal(s.meetings.pendingBoss,null);assert.equal(s.todoQueue.length,0);});
