import test,{afterEach} from 'node:test';
import assert from 'node:assert/strict';
import {gameConfig as c} from '../src/config/gameConfig';
import {initialState} from '../src/game/state/initialState';
import {advance,advanceOnline} from '../src/game/engine/SimulationLoop';
import {ensureTarget,startWork,targetRate} from '../src/game/targets/targetManager';
import {checkPromotionWorkStart,getPromotionQualificationStats,promotionWorkload,failExpiredPromotion} from '../src/game/career/promotionAssignment';
import {effectiveWorkSpeed,rawWorkSpeed,rawWorkQuality} from '../src/game/work/workStats';
import {syncWorld,scaledSeconds} from '../src/game/time/worldTime';
import {saveGame,loadGame,validateSave} from '../src/game/save/saveGame';
import {createTodo} from '../src/game/work/todoManager';
import {createFollowUp} from '../src/game/work/followUpManager';
import {createProject} from '../src/game/projects/projectManager';
import {resolveBoss} from '../src/game/career/bossEvents';
import {applyAction} from '../src/game/engine/actions';
import type {State,PromotionTarget} from '../src/game/types';
const config=structuredClone(c);afterEach(()=>Object.assign(c,structuredClone(config)));
const close=(a:number,b:number)=>assert.ok(Math.abs(a-b)<1e-6,`${a} != ${b}`);
function quiet(rank=0,multiplier=1){c.meeting.normalChanceByRank=[0,0,0,0,0];const s=initialState(42,0);s.career.rank=rank;s.player.money=1e6;s.world.totalWorldTime=scaledSeconds(c.time.workStartAnchor);syncWorld(s);s.world.nextEventAt=1e9;s.needs.satietyUntil=1e9;s.needs.phase='MORNING';s.needs.breakfastState='COMPLETED';s.needs.projectRollProcessedRoutineId=0;const q=c.promotionQualification.requirements[rank];if(q){s.player.upgrades.efficiency=q.efficiency*multiplier-c.economy.baseWorkSpeed;s.player.upgrades.quality=q.quality*multiplier-c.economy.baseQuality;}return s;}
function active(rank=0,multiplier=1){const s=quiet(rank,multiplier);checkPromotionWorkStart(s);assert.equal(s.currentTarget?.type,'PROMOTION');return s;}
const target=(s:State)=>s.currentTarget as PromotionTarget;
for(let rank=0;rank<4;rank++)test(`rank${rank} deprecated cost is never read by assignment or settlement`,()=>{
 const s=quiet(rank,2);s.player.money=0;
 Object.defineProperty(c.ranks[rank+1],'promotionCost',{configurable:true,get(){throw Error('Deprecated promotion cost read');}});
 checkPromotionWorkStart(s);assert.equal(s.currentTarget?.type,'PROMOTION');
 const t=target(s);t.progress=t.requirement;s.promotion.progress=t.progress;s.promotion.status='COMPLETED_PENDING_DINNER';s.world.totalWorldTime=t.deadlineWorldTime;syncWorld(s);
 // The normal Dinner transaction, including its repeated eligibility check.
 failExpiredPromotion(s);assert.equal(s.career.rank,rank+1);assert.equal(s.player.money,0);
});
test('WorkStart telemetry covers blocked and assigned checks without affecting State or RNG',()=>{
 const a=quiet(),b=structuredClone(a),rows:any[]=[];a.player.money=0;b.player.money=0;
 advanceOnline(a,.25,{onPromotionWorkStart:r=>rows.push(r)});advanceOnline(b,.25);assert.deepEqual(a,b);
 assert.equal(rows.length,1);assert.equal(rows[0].assigned,true);assert.equal(rows[0].eqQualified,true);assert.equal(rows[0].overdueQualified,true);assert.deepEqual(rows[0].blockingReasons,[]);assert.ok(!Object.keys(rows[0]).some(k=>/money|cost/i.test(k)));
 const blocked=quiet();blocked.player.upgrades.efficiency--;const seen:any[]=[];advanceOnline(blocked,361,{onPromotionWorkStart:r=>seen.push(r)});assert.equal(seen.length,3);assert.ok(seen.every(r=>!r.assigned&&r.blockingReasons.includes('EQ')));
});
function memory(){const values=new Map<string,string>();return {getItem:(k:string)=>values.get(k)??null,setItem:(k:string,v:string)=>{values.set(k,v);},removeItem:(k:string)=>{values.delete(k);}};}
test('official 180-second world day and anchors; starting stats are base, all levels zero',()=>{const s=initialState(42,0);assert.equal(c.time.dayDuration,180);assert.deepEqual([c.time.workStartAnchor,c.time.lunchStart,c.time.lunchStart+c.time.lunchDuration,c.time.offWorkAnchor,c.time.sleepAnchor].map(scaledSeconds),[24,60,84,120,150]);assert.equal(rawWorkSpeed(s),10);assert.equal(rawWorkQuality(s),6);assert.ok(Object.values(s.player.upgrades).every(v=>v===0));advance(s,180);assert.equal(s.world.dayIndex,1);close(s.world.timeOfDay,0);});
for(let rank=0;rank<4;rank++)test(`rank${rank} WorkStart immediate, fixed threshold workload, independent of actual speed/age`,()=>{const a=active(rank),b=active(rank,2);close(target(a).requirement,promotionWorkload(rank));close(target(a).requirement,[2304,4608,9216,18432][rank]);close(target(b).requirement,target(a).requirement);assert.equal(a.promotion.deadlineWorldTime,120);const id=target(a).id;a.player.age=60;a.player.upgrades.efficiency+=300;ensureTarget(a);assert.equal(target(a).id,id);close(target(a).requirement,promotionWorkload(rank));});
test('below E or Q does not receive assignment; zero money permits assignment',()=>{for(const field of ['efficiency','quality'] as const){const s=quiet();s.player.upgrades[field]--;checkPromotionWorkStart(s);assert.equal(s.promotion.status,'NOT_ELIGIBLE');}const s=quiet();s.player.money=0;checkPromotionWorkStart(s);assert.equal(s.promotion.status,'ACTIVE');});
test('low profile changes only evaluated E/Q; high actual ability can succeed first try',()=>{const s=quiet(0,2),speed=effectiveWorkSpeed(s);s.promotion.lowProfileEnabled=true;const q=getPromotionQualificationStats(s);close(q.evaluatedEfficiency,q.efficiency*.8);close(effectiveWorkSpeed(s),speed);checkPromotionWorkStart(s);close(targetRate(s,target(s)),speed);advance(s,96);assert.equal(s.career.rank,1);assert.equal(s.promotion.failureReason,null);});
test('Low Profile delays threshold entry to E25/Q15 and creates clean assessment headroom',()=>{
 const early=active();advance(early,96);assert.equal(early.promotion.status,'FAILED_OVERTIME');
 const held=quiet();held.promotion.lowProfileEnabled=true;checkPromotionWorkStart(held);assert.equal(held.promotion.status,'NOT_ELIGIBLE');
 const prepared=quiet(0,1.25);prepared.promotion.lowProfileEnabled=true;checkPromotionWorkStart(prepared);assert.equal(prepared.currentTarget?.type,'PROMOTION');close(getPromotionQualificationStats(prepared).evaluatedEfficiency,20);close(effectiveWorkSpeed(prepared),25);advance(prepared,96);assert.equal(prepared.career.rank,1);
});
test('active Promotion Day crosses lunch without FOOD/LUNCH, Buff or Debuff',()=>{const s=active(),seen:string[]=[];advance(s,65,{onTargetInterval:t=>{if(t)seen.push(t.type);}});assert.ok(seen.every(t=>t==='PROMOTION'));assert.equal(s.needs.lunchRest,0);assert.equal(s.buffs.some(b=>b.id==='lunch'),false);assert.equal(s.debuffs.some(d=>/午餐|午休/.test(d.name)),false);assert.ok(s.needs.lunchSettled);});
test('ordinary day still FOOD then LUNCH and gets rest benefits',()=>{const s=quiet();s.promotion.lastCheckedWorkday=0;s.world.totalWorldTime=60;syncWorld(s);s.needs.phase='MORNING';ensureTarget(s);assert.equal(s.currentTarget?.type,'FOOD');advance(s,24);assert.ok(s.needs.lunchRest>0);assert.ok(s.buffs.some(b=>b.id==='lunch'));});
for(const offset of [-1,0])test(`completion ${offset} seconds relative Dinner succeeds, no ordinary pipeline`,()=>{const s=active(),t=target(s);t.requirement=effectiveWorkSpeed(s)*(96+offset);s.promotion.requirement=t.requirement;const money=s.player.money;advance(s,96+offset);if(offset<0){assert.equal(s.promotion.status,'COMPLETED_PENDING_DINNER');assert.equal(s.career.rank,0);advance(s,-offset);}assert.equal(s.career.rank,1);close(s.player.money,money);assert.equal(s.runStatistics.earned,0);assert.equal(s.runStatistics.completedWork,0);assert.equal(s.pendingFollowUps.length,0);assert.equal(s.projects.length,0);if(offset===0)assert.equal(s.currentTarget?.type,'FOOD');});
test('one unit left at Dinner fails, keeps identity/progress, Dinner then same overtime, no late promotion',()=>{const s=active(),t=target(s),id=t.id,req=t.requirement,money=s.player.money;advance(s,96);assert.equal(s.promotion.status,'FAILED_OVERTIME');assert.equal(s.currentTarget?.type,'FOOD');assert.equal((s.currentTarget as any).meal,'DINNER');assert.equal(s.promotion.assignmentId,id);close(s.promotion.progress,1920);assert.equal(s.suspendedTargets.find(x=>x.target.id===id)?.target,t);const store=memory();saveGame(s,store,0);const r=loadGame(store,0);assert.equal(r.error,null);assert.equal(r.state.promotion.status,'FAILED_OVERTIME');advance(r.state,4);assert.equal(r.state.currentTarget?.id,id);close(target(r.state).progress,1920);advance(r.state,(req-1920)/20);assert.equal(r.state.career.rank,0);assert.equal(r.state.promotion.status,'COOLDOWN');assert.equal(r.state.promotion.progress,req);close(r.state.player.money,money);assert.equal(r.state.runStatistics.earned,c.promotionAssignment.failedCompletionReward);assert.equal(r.state.promotion.retryAvailableWorkday,3);assert.ok(validateSave(r.state));});
test('Money does not block settlement; Overdue still revalidated',()=>{for(const kind of ['money','overdue']){const s=active(0,2);advance(s,57.6);startWork(s,createTodo(s,{...c.work.templates[0],workload:100000},'EVENT'));if(kind==='money')s.player.money=0;else for(let i=0;i<4;i++){const todo=createTodo(s,c.work.templates[0]);Object.assign(todo,{assignmentWorkdayIndex:-1,deadlineWorkdays:0,dueWorkdayIndex:-1});s.todoQueue.push(todo);}advance(s,38.4);assert.equal(s.career.rank,kind==='money'?1:0);assert.equal(s.promotion.status,kind==='money'?'NOT_ELIGIBLE':'FAILED_REQUIREMENT');assert.ok(s.player.money>=0);}});
test('active save/reload preserves progress, snapshot, deadline and low profile',()=>{const s=active();advance(s,10);s.promotion.lowProfileEnabled=true;const store=memory();saveGame(s,store,0);const r=loadGame(store,0);assert.equal(r.error,null);assert.deepEqual(r.state.promotion,s.promotion);assert.deepEqual(r.state.currentTarget,s.currentTarget);});
test('offline pauses assessment and deadline, no automatic promotion or acceleration',()=>{const s=active();advance(s,10);const progress=s.promotion.progress,deadline=s.promotion.deadlineWorldTime!;advance(s,180,{offline:true});assert.equal(s.career.rank,0);close(s.promotion.progress,progress);close(s.promotion.deadlineWorldTime!,deadline+180);close(s.world.totalWorldTime,214);assert.equal(s.runStatistics.activeSeconds,0);});
test('sleep60x consumes 0.9 real seconds for54world seconds then leftover returns1x',()=>{const s=initialState(42,0);s.world.totalWorldTime=150;syncWorld(s);s.world.nextEventAt=1e9;s.needs.phase='SLEEP';s.currentTarget={id:'sleep',type:'SLEEP',name:'Sleep',createdAt:150,requirement:54,progress:0};advanceOnline(s,1);close(s.world.totalWorldTime,204.1);close(s.needs.sleep.lastRatio,1);assert.equal(s.needs.breakfastState,'STARTED');assert.equal(s.currentTarget?.type,'FOOD');close(s.runStatistics.activeSeconds,1);});
test('sleep batches match a large real tick without skipping workstart',()=>{const a=initialState(42,0);a.world.totalWorldTime=150;syncWorld(a);a.world.nextEventAt=1e9;a.needs.phase='SLEEP';a.currentTarget={id:'sleep',type:'SLEEP',name:'Sleep',createdAt:150,requirement:54,progress:0};const b=structuredClone(a);advanceOnline(a,1);for(let i=0;i<20;i++)advanceOnline(b,.05);close(a.world.totalWorldTime,b.world.totalWorldTime);close(a.needs.sleep.lastRatio,b.needs.sleep.lastRatio);assert.deepEqual(a.currentTarget,b.currentTarget);close(a.runStatistics.activeSeconds,b.runStatistics.activeSeconds);});
test('sleep reload resumes fast; debug world skip does not add Active Time',()=>{const s=initialState(42,0);s.world.totalWorldTime=150;syncWorld(s);s.world.nextEventAt=1e9;s.needs.phase='SLEEP';ensureTarget(s);advanceOnline(s,.3);const store=memory();saveGame(s,store,0);const r=loadGame(store,0);assert.equal(r.error,null);advanceOnline(r.state,.6);close(r.state.world.totalWorldTime,204);close(r.state.runStatistics.activeSeconds,.9);const before=r.state.runStatistics.activeSeconds;advance(r.state,180);close(r.state.runStatistics.activeSeconds,before);});
for(const type of ['WORK','PROMOTION','MEETING','FOOD'] as const)test(`${type} never receives sleep acceleration`,()=>{const s=type==='PROMOTION'?active():quiet();s.promotion.lastCheckedWorkday=0;if(type==='WORK')startWork(s,createTodo(s,{...c.work.templates[0],workload:100000}));if(type==='MEETING')applyAction(s,{type:'debug',command:'normalMeeting'});if(type==='FOOD')s.currentTarget={id:'food',type:'FOOD',name:'Food',requirement:120,progress:0,createdAt:24,foodId:'normal',meal:'EXTRA'};const now=s.world.totalWorldTime;advanceOnline(s,.5);close(s.world.totalWorldTime,now+.5);close(s.runStatistics.activeSeconds,.5);});
for(let rank=0;rank<5;rank++)test(`Rank${rank} normal workload tier applied once, 5-10sec recommendation, old work faster at higher E`,()=>{const s=initialState(42,0);s.career.rank=rank;const t=createTodo(s,{...c.work.templates[0],workload:100});close(t.workload,[70,140,280,560,1120][rank]);close(t.rankWorkloadMultiplierAtCreation,1);const e=c.ranks[rank].recommendedSpeed;close(t.workload/e,7);for(const template of c.work.templates){const x=createTodo(s,template);assert.ok(x.workload/e>=5&&x.workload/e<=10);}s.player.upgrades.efficiency=100-c.economy.baseWorkSpeed;close(t.workload/effectiveWorkSpeed(s),t.workload/100);s.career.rank=Math.min(4,rank+1);assert.equal(t.workload,[70,140,280,560,1120][rank]);});
test('Boss, Project, Follow-up keep rank/age snapshot exactly once and no boss flags on follow-up',()=>{const s=quiet(2);s.player.age=60;c.meeting.bossMeetingChanceOnEscapeFail=0;resolveBoss(s,true,false);const boss=s.todoQueue.find(t=>t.mandatoryOvertime)!;close(boss.workload,10*7.5*c.ranks[2].workloadMultiplier*1.7);const [fu]=createFollowUp(s,boss,'REWORK',1,0);close(fu.workload,boss.workload*.65);assert.equal(fu.mandatoryOvertime,undefined);const p=createProject(s)!;const sub=s.todoQueue.find(t=>t.projectId===p.id)!;close(sub.workload,140*c.ranks[2].workloadMultiplier*1.7);});
test('60→180 save migration preserves day/phase, old workload/levels/money and active seconds',()=>{const s=initialState(42,0);s.world.dayDurationAtSave=60;s.world.totalWorldTime=55;s.needs.sleep.windowStart=50;s.needs.sleep.windowEnd=68;s.needs.sleep.duration=5;s.needs.sleep.output=5;s.needs.phase='SLEEP';s.currentTarget={id:'sleep',type:'SLEEP',name:'sleep',createdAt:50,requirement:18,progress:5};const store=memory();saveGame(s,store,0);const r=loadGame(store,0);assert.equal(r.error,null);close(r.state.world.totalWorldTime,165);close(r.state.needs.sleep.output,15);close(r.state.needs.sleep.windowEnd,204);assert.equal(r.state.player.money,s.player.money);assert.deepEqual(r.state.player.upgrades,s.player.upgrades);advanceOnline(r.state,.65);close(r.state.world.totalWorldTime,204);});
test('failed assessment suspended by a Problem is preserved across exact Dinner',()=>{const s=active(),t=target(s);s.suspendedTargets.push({target:t,phase:'AFTERNOON'});s.currentTarget={id:'food',type:'FOOD',name:'Food',createdAt:24,requirement:100000,progress:0,foodId:'normal',meal:'EXTRA'};advance(s,96);assert.equal(s.promotion.status,'FAILED_OVERTIME');assert.equal(s.currentTarget?.type,'FOOD');assert.equal((s.currentTarget as any).meal,'DINNER');assert.ok(s.suspendedTargets.some(x=>x.target.id===t.id));advance(s,4);assert.equal(s.currentTarget?.id,t.id);});

test('cooldown unchanged3 workday indices, refuses day1/2, day3 receives fixed retry',()=>{const s=active();advance(s,96);advance(s,4);advance(s,(target(s).requirement-target(s).progress)/20);for(const day of [1,2]){s.world.totalWorldTime=day*180+24;syncWorld(s);checkPromotionWorkStart(s);assert.equal(s.promotion.status,'COOLDOWN');}s.world.totalWorldTime=564;syncWorld(s);checkPromotionWorkStart(s);assert.equal(s.promotion.status,'ACTIVE');close(target(s).requirement,2304);});
test('batched promotion outcome/progress/RNG matches small world intervals',()=>{const a=active(),b=structuredClone(a);advance(a,120);for(let i=0;i<2400;i++)advance(b,.05);assert.equal(a.career.rank,b.career.rank);assert.equal(a.promotion.status,b.promotion.status);close(a.promotion.progress,b.promotion.progress);assert.equal(a.world.rng,b.world.rng);close(a.player.money,b.player.money);});
test('world-based offline sleep does not apply60x and preserves Active Play Time',()=>{const s=initialState(42,0);s.world.totalWorldTime=150;syncWorld(s);s.world.nextEventAt=1e9;s.needs.phase='SLEEP';ensureTarget(s);advance(s,54,{offline:true});close(s.world.totalWorldTime,204);close(s.needs.sleep.lastRatio,1);close(s.runStatistics.activeSeconds,0);});
test('WorkStart promotion preempts existing target, preserving suspended identity/progress',()=>{const s=quiet(),todo=createTodo(s,c.work.templates[0]);startWork(s,todo);const old=s.currentTarget!;(old as {progress:number}).progress=7;checkPromotionWorkStart(s);assert.equal(s.currentTarget?.type,'PROMOTION');assert.equal(s.suspendedTargets[0].target.id,old.id);close((s.suspendedTargets[0].target as {progress:number}).progress,7);});
test('sleep interrupted by Problem changes rate within the same real tick',()=>{const s=initialState(42,0);s.world.totalWorldTime=150;syncWorld(s);s.world.nextEventAt=150.6;s.needs.phase='SLEEP';ensureTarget(s);const original=s.currentTarget!;let inserted=false;advanceOnline(s,.1,{onBoundary:state=>{if(!inserted&&state.world.totalWorldTime>=150.6-1e-8){inserted=true;state.suspendedTargets.push({target:original,phase:'SLEEP'});state.currentTarget={id:'food-test',type:'FOOD',name:'Food',requirement:120,progress:0,createdAt:state.world.totalWorldTime,foodId:'normal',meal:'EXTRA'};}}});close(s.world.totalWorldTime,150.69);close(s.needs.sleep.duration,.6);close(s.runStatistics.activeSeconds,.1);});

test('new formal config multiple working days retains valid state and generated normal variety',()=>{const s=initialState(42,0),seen=new Set<number>();advanceOnline(s,900,{onBoundary:state=>{assert.ok(validateSave(state));for(const todo of state.todoQueue)if(todo.sourceType==='NORMAL')seen.add(todo.workload);}});assert.ok(seen.size>1);assert.ok(s.world.dayIndex>=5);assert.ok(s.runStatistics.completedWork>0);close(s.runStatistics.activeSeconds,900);});

test('early completed assessment reload waits for Dinner transaction; offline does not grant rank',()=>{const s=active(0,2);advance(s,57.6);assert.equal(s.promotion.status,'COMPLETED_PENDING_DINNER');assert.equal(s.career.rank,0);const store=memory();saveGame(s,store,0);const r=loadGame(store,0);assert.equal(r.error,null);advance(r.state,180,{offline:true});assert.equal(r.state.career.rank,0);assert.equal(r.state.promotion.status,'COMPLETED_PENDING_DINNER');advance(r.state,38.4);assert.equal(r.state.career.rank,1);});

test('Promotion Dinner happens once even when it suspends an already-started ordinary target',()=>{const s=quiet(0,2);startWork(s,createTodo(s,{...c.work.templates[0],workload:2000},'EVENT'));checkPromotionWorkStart(s);const dinners=new Set<string>();advance(s,116,{onTargetInterval:t=>{if(t?.type==='FOOD'&&t.meal==='DINNER')dinners.add(t.id);}});assert.equal(s.career.rank,1);assert.equal(dinners.size,1);});
