import test from 'node:test';
import assert from 'node:assert/strict';
import { gameConfig as c } from '../src/config/gameConfig';
import { initialState } from '../src/game/state/initialState';
import { advance } from '../src/game/engine/SimulationLoop';
import { applyAction } from '../src/game/engine/actions';
import { syncWorld } from '../src/game/time/worldTime';
import { ensureTarget, startFood, startWork, interruptWithFood, targetRate } from '../src/game/targets/targetManager';
import { createTodo, refillTodos, generateDailyWork } from '../src/game/work/todoManager';
import { selectNextWork } from '../src/game/work/workSelector';
import { createFollowUp, releasePending, generateFollowUps } from '../src/game/work/followUpManager';
import { followUpChance } from '../src/game/work/workQuality';
import { effectiveWorkSpeed, effectiveWorkQuality } from '../src/game/work/workStats';
import { createProject, completeProjectSubtask } from '../src/game/projects/projectManager';
import { catchChance, escapeChance, resolveBoss } from '../src/game/career/bossEvents';
import { remainingProductDays, toggleProduct } from '../src/game/products/productManager';
import { processBilling } from '../src/game/products/billingManager';
import { triggerEvent } from '../src/game/events/eventManager';
import { settleOfflineMinutes } from '../src/game/time/offlineSimulation';
import { permanentMultiplier, buyPermanent } from '../src/game/prestige/permanentUpgrades';
import { prestigeReset, calculateClarityReward } from '../src/game/prestige/prestigeManager';
import { loadGame, saveGame, validateSave } from '../src/game/save/saveGame';
import type { State, Target } from '../src/game/types';
const close = (a: number, b: number) => assert.ok(Math.abs(a-b)<1e-6, `${a} != ${b}`);
function state(time = 0) { const s = initialState(5, 0); s.world.totalWorldTime = time; syncWorld(s); s.world.nextEventAt = 100000; s.needs.phase = 'MORNING'; s.needs.satietyUntil=100000; s.needs.projectRollProcessedRoutineId=0; return s; }
function running(s: State, workload: number) { const todo = createTodo(s, c.work.templates[0]); todo.workload = workload; startWork(s,todo); return s.currentTarget!; }
function memory() { const map = new Map<string,string>(); return { map, getItem: (k: string)=>map.get(k)??null, setItem:(k:string,v:string)=>{map.set(k,v);}, removeItem:(k:string)=>{map.delete(k);} }; }

test('fixed day boundary never interrupts active sleep',()=>{ const s=state(59); s.needs.phase='SLEEP'; s.currentTarget={id:'sleep',type:'SLEEP',name:'sleep',requirement:4,progress:0,createdAt:59}; advance(s,1); assert.equal(s.world.dayIndex,1); close(s.world.timeOfDay,0); assert.equal(s.currentTarget?.id,'sleep'); close((s.currentTarget as Extract<Target,{type:'SLEEP'|'ENTERTAINMENT'}>).progress,1); });
test('sleep at 63 continues only until next workStart 68',()=>{const s=state(59);s.needs.phase='SLEEP';s.currentTarget={id:'sleep',type:'SLEEP',name:'sleep',requirement:4,progress:0,createdAt:59};advance(s,4);close(s.world.totalWorldTime,63);assert.equal(s.world.dayIndex,1);assert.equal(s.currentTarget?.type,'SLEEP');advance(s,5);assert.notEqual(s.currentTarget?.type,'SLEEP');assert.equal('oversleepSeconds' in s.needs,false);});
test('work through lunchStart keeps progress; finishing24 and eating4 leaves zero rest',()=>{const s=state(18); const t=running(s,120); advance(s,4); assert.equal(s.currentTarget?.id,t.id); advance(s,2); assert.equal(s.needs.phase,'LUNCH_FOOD'); advance(s,4); close(s.world.totalWorldTime,28); close(s.needs.lunchRest,0); assert.equal(s.needs.lunchSettled,true); assert.ok(!s.buffs.some(b=>b.id==='lunch'));});
test('normal lunch food consumes4 of fixed8sec window; LUNCH has no requirement',()=>{const s=state(20); ensureTarget(s); advance(s,4); assert.equal(s.currentTarget?.type,'LUNCH'); assert.ok(!('requirement' in s.currentTarget!)); advance(s,4); close(s.needs.lunchRest,120); assert.equal(s.needs.phase,'AFTERNOON'); assert.ok(s.buffs.some(b=>b.id==='lunch'));});
test('quick food retains more rest; life management increases output rather than extending window',()=>{const s=state(20); s.player.money=1000; toggleProduct(s,'quick'); s.player.settings.defaultFoodId='quick'; s.player.upgrades.lifeManagement=1; ensureTarget(s); advance(s,8); close(s.world.totalWorldTime,28); assert.ok(s.needs.lunchRest>240); assert.ok(s.products.quick.contributionStats.foodSecondsSaved!>3);});
test('low watermark refills toward target, never fills an already-busy queue',()=>{const s=state(); refillTodos(s); assert.equal(s.todoQueue.length,4); const ids=s.todoQueue.map(t=>t.id); refillTodos(s); assert.deepEqual(s.todoQueue.map(t=>t.id),ids); s.todoQueue.splice(0,3); refillTodos(s); assert.equal(s.todoQueue.length,4); generateDailyWork(s,10); refillTodos(s); assert.equal(s.todoQueue.length,14);});
test('selector only removes a queued todo and respects priority, no direct generation',()=>{const s=state(); assert.equal(selectNextWork(s),null); generateDailyWork(s,2); s.todoQueue[1].priority=99; const id=s.todoQueue[1].id; assert.equal(selectNextWork(s)?.id,id); assert.equal(s.todoQueue.length,1);});
test('immediate follow-up adds multiple todos and retains source metadata',()=>{const s=state();const root=createTodo(s,c.work.templates[0]);createFollowUp(s,root,'REWORK',3,0);assert.equal(s.todoQueue.length,3);assert.equal(s.todoQueue[0].followUpDepth,1);assert.equal(s.todoQueue[0].sourceId,root.id);assert.ok(s.todoQueue[0].baseReward<root.baseReward);});
test('missing info can be zero reward',()=>{const s=state();createFollowUp(s,createTodo(s,c.work.templates[0]),'MISSING_INFO',1,0);assert.equal(s.todoQueue[0].baseReward,0);});
test('delayed follow-ups are not queued early, release at world deadline',()=>{const s=state();createFollowUp(s,createTodo(s,c.work.templates[0]),'CLIENT_REPLY',2,20);assert.equal(s.todoQueue.length,0);assert.equal(s.pendingFollowUps.length,1);s.world.totalWorldTime=19;releasePending(s);assert.equal(s.todoQueue.length,0);s.world.totalWorldTime=20;releasePending(s);assert.equal(s.todoQueue.length,2);assert.equal(s.pendingFollowUps.length,0);});
test('follow-up depth and root reservation caps include delayed tasks',()=>{const s=state();const root=createTodo(s,c.work.templates[0]);createFollowUp(s,root,'CLIENT_REPLY',100,20);assert.equal(s.pendingFollowUps[0].tasksToCreate.length,c.followUps.maxExtraTasksPerRootWork);createFollowUp(s,root,'REWORK',10,0);assert.equal(s.todoQueue.length,0);const deep={...root,followUpDepth:c.followUps.maxFollowUpDepth,rootId:'other'};assert.equal(createFollowUp(s,deep,'REWORK',2,0).length,0);});
test('quality reduces avoidable rework without changing speed or business reply chance',()=>{const low=state();const high=structuredClone(low);high.player.upgrades.quality=50;const work=createTodo(low,c.work.templates[0]);const bad=c.followUps.types.find(f=>f.type==='REWORK')!;const reply=c.followUps.types.find(f=>f.type==='CLIENT_REPLY')!;assert.ok(followUpChance(high,work,bad)<followUpChance(low,work,bad));assert.equal(followUpChance(high,work,reply),followUpChance(low,work,reply));assert.equal(effectiveWorkSpeed(high),effectiveWorkSpeed(low));});
test('sampled high quality produces fewer rework todos, business follow-ups remain',()=>{let low=0,high=0,replies=0;for(let seed=1;seed<=300;seed++){const a=state(),b=state();a.world.rng=b.world.rng=seed;b.player.upgrades.quality=50;const root=createTodo(a,c.work.templates[0]);generateFollowUps(a,root);generateFollowUps(b,root);const count=(s:State)=>[...s.todoQueue,...s.pendingFollowUps.flatMap(p=>p.tasksToCreate)].filter(t=>t.followUpType==='REWORK').length;low+=count(a);high+=count(b);replies+=b.pendingFollowUps.filter(p=>p.followUpType==='CLIENT_REPLY').length;}assert.ok(high<low);assert.ok(replies>0);});
test('project dependencies unlock only ready nodes and pay parent bonus',()=>{const s=state();const p=createProject(s)!;assert.equal(s.todoQueue.length,1);const first=s.todoQueue.shift()!;completeProjectSubtask(s,first);assert.equal(s.todoQueue.filter(t=>t.projectId===p.id).length,2);assert.equal(p.completedSubtasks,1);while(p.status==='ACTIVE'){const t=s.todoQueue.find(t=>t.projectId===p.id&&t.subtaskId)!;s.todoQueue=s.todoQueue.filter(x=>x.id!==t.id);completeProjectSubtask(s,t);}assert.equal(p.completedSubtasks,p.subtasks.length);assert.equal(s.runStatistics.projectsCompleted,1);assert.ok(s.player.money>=c.economy.startingMoney+p.reward);});
test('project follow-up differs from unlocking next required subtask',()=>{const s=state();const p=createProject(s)!;const t=s.todoQueue[0];createFollowUp(s,t,'NEW_REQUEST',2,10);completeProjectSubtask(s,t);assert.equal(p.completedSubtasks,1);assert.ok(s.pendingFollowUps[0].tasksToCreate.every(t=>t.projectId===p.id&&!t.subtaskId));});
test('boss catch and escape formulas are independent and require two rolls',()=>{const s=state();const caught=catchChance(s),escape=escapeChance(s);s.player.upgrades.slacking=5;assert.equal(catchChance(s),caught);assert.ok(escapeChance(s)>escape);const escaped=escapeChance(s);s.player.upgrades.flattery=5;assert.ok(catchChance(s)>caught);assert.equal(escapeChance(s),escaped);assert.equal(resolveBoss(s,true,true).escaped,true);assert.equal(s.todoQueue.length,0);resolveBoss(s,true,false);assert.equal(s.todoQueue[0].sourceType,'BOSS');close(s.todoQueue[0].workload/c.economy.baseWorkSpeed,c.time.dayDuration/c.time.hoursPerDay);});
test('product activates with run money, charges again after exactly30full days',()=>{const s=state();s.player.money=10000;const money=s.player.money;toggleProduct(s,'eyes');assert.equal(s.player.money,money-c.products.definitions.find(p=>p.id==='eyes')!.price);s.world.totalWorldTime=29*c.time.dayDuration;syncWorld(s);processBilling(s);close(remainingProductDays(s,'eyes'),1);const before=s.player.money;s.world.totalWorldTime+=c.time.dayDuration;syncWorld(s);processBilling(s);close(remainingProductDays(s,'eyes'),30);assert.equal(s.player.money,before-s.products.eyes.pricePerBillingPeriod);});
test('failed renewal disables product without negative balance',()=>{const s=state();toggleProduct(s,'eyes');s.products.eyes.nextBillingWorldTime=s.world.totalWorldTime+c.time.dayDuration;s.player.money=0;s.world.totalWorldTime+=c.time.dayDuration;syncWorld(s);processBilling(s);assert.equal(s.products.eyes.active,false);assert.equal(s.player.money,0);assert.ok(s.eventLog.some(n=>n.text.includes('續購失敗')));});
test('manual disable preserves paid time but calendar still consumes it',()=>{const s=state();toggleProduct(s,'eyes');toggleProduct(s,'eyes');s.world.totalWorldTime+=c.time.dayDuration;syncWorld(s);processBilling(s);close(remainingProductDays(s,'eyes'),29);const money=s.player.money;toggleProduct(s,'eyes');assert.equal(s.player.money,money);});
test('without product debuff expires naturally and creates no problem',()=>{const s=state();s.needs.phase='WAIT';triggerEvent(s,'eyes',true);advance(s,40);assert.equal(s.debuffs.length,0);assert.ok(!s.eventLog.some(n=>n.type==='產品'));});
test('product creates problem, clears original debuff early and records protection',()=>{const s=state();toggleProduct(s,'eyes');triggerEvent(s,'eyes',true);ensureTarget(s);assert.equal(s.currentTarget?.type,'PROBLEM');advance(s,4);assert.equal(s.debuffs.length,0);assert.equal(s.products.eyes.contributionStats.problemResolvedCount,1);close(s.products.eyes.contributionStats.debuffSecondsSaved!,36);assert.ok(s.buffs.some(b=>b.protectionTag==='eyes'));assert.equal(triggerEvent(s,'eyes'),null);});
test('immediate wound interrupts work then restores exact remaining progress',()=>{const s=state();s.player.money=1000;toggleProduct(s,'wound');const t=running(s,200);advance(s,1);const progress=(t as Extract<Target,{type:'WORK'}>).progress;triggerEvent(s,'wound',true);ensureTarget(s);assert.equal(s.currentTarget?.type,'PROBLEM');assert.equal(s.suspendedTargets[0].target.id,t.id);advance(s,4);assert.equal(s.currentTarget?.id,t.id);close((s.currentTarget as {progress:number}).progress,progress);});
test('non-interrupting eye problem waits until active work completes',()=>{const s=state();s.player.money=1000;toggleProduct(s,'eyes');const t=running(s,80);triggerEvent(s,'eyes',true);ensureTarget(s);assert.equal(s.currentTarget?.id,t.id);advance(s,5);assert.equal(s.currentTarget?.type,'PROBLEM');});
test('explicit food insertion suspends and restores work without resetting progress',()=>{const s=state();const t=running(s,200);advance(s,1);interruptWithFood(s);assert.equal(s.currentTarget?.type,'FOOD');advance(s,4);assert.equal(s.currentTarget?.id,t.id);close((s.currentTarget as {progress:number}).progress,20);});
test('permanent level3 follows exponential total formula',()=>{const s=state();s.prestige.clarity=100;for(let i=0;i<3;i++)assert.ok(buyPermanent(s,'workEfficiency'));close(permanentMultiplier(s,'workEfficiency'),1.1**3);close(effectiveWorkSpeed(s),20*1.1**3);});
test('prestige resets all run systems and subscriptions while preserving permanent stats',()=>{const s=state();s.player.money=1000;toggleProduct(s,'eyes');generateDailyWork(s,3);createProject(s);s.player.upgrades.efficiency=5;s.career.rank=s.career.highestRank=2;s.runStatistics.earned=3000;s.runStatistics.activeSeconds=1800;s.runStatistics.peakIncome=30;s.prestige.levels.workEfficiency=3;s.prestige.clarity=9;const reward=calculateClarityReward(s);assert.ok(prestigeReset(s));assert.equal(s.player.upgrades.efficiency,0);assert.equal(s.career.rank,0);assert.equal(s.todoQueue.length,0);assert.equal(s.projects.length,0);assert.equal(s.products.eyes.active,false);assert.equal(s.prestige.levels.workEfficiency,3);assert.equal(s.prestige.clarity,9+reward);assert.equal(s.permanentStatistics.runs,1);close(effectiveWorkSpeed(s),20*1.1**3);});
test('offline30min=1day;16hours=32days, income and age advance without player decisions',()=>{const s=state();const rank=s.career.rank,levels={...s.player.upgrades};assert.equal(settleOfflineMinutes(s,30),1);assert.equal(s.world.dayIndex,1);assert.equal(settleOfflineMinutes(s,960),32);assert.equal(s.world.dayIndex,33);assert.ok(s.runStatistics.earned>0);close(s.player.ageProgressDays,33);assert.equal(s.career.rank,rank);assert.deepEqual(s.player.upgrades,levels);assert.equal(s.permanentStatistics.runs,0);});
test('offline20+15min yields1day and5min carry',()=>{const s=state();assert.equal(settleOfflineMinutes(s,20),0);assert.equal(s.offline.offlineCarryMinutes,20);assert.equal(settleOfflineMinutes(s,15),1);close(s.offline.offlineCarryMinutes,5);});
test('offline billing can stop product mid-settlement and age protection stops too',()=>{const s=state();s.player.money=1000;toggleProduct(s,'agecare');s.products.agecare.nextBillingWorldTime=s.world.totalWorldTime+c.time.dayDuration;s.player.money=0;s.needs.phase='SLEEP';s.currentTarget={id:'longsleep',type:'SLEEP',name:'longsleep',progress:0,requirement:100000,createdAt:0};settleOfflineMinutes(s,960);assert.equal(s.products.agecare.active,false);close(s.player.ageProgressDays,31.5);close(s.products.agecare.contributionStats.offlineAgeDaysProtected!,.5);});
test('offline subscriptions renew with sufficient funds',()=>{const s=state();s.player.money=100000;toggleProduct(s,'eyes');s.products.eyes.nextBillingWorldTime=s.world.totalWorldTime+10*c.time.dayDuration;const spent=s.products.eyes.contributionStats.totalSpent;settleOfflineMinutes(s,960);assert.ok(s.products.eyes.active);close(remainingProductDays(s,'eyes'),8);assert.equal(s.products.eyes.contributionStats.totalSpent,spent+s.products.eyes.pricePerBillingPeriod);});
test('save resumes V2 and preserves offline carry; incompatible legacy backs up',()=>{const store=memory();const s=state();saveGame(s,store,0);const loaded=loadGame(store,20*60000);assert.equal(loaded.error,null);close(loaded.state.offline.offlineCarryMinutes,20);assert.ok(validateSave(loaded.state));store.removeItem(c.save.key);store.setItem(c.save.legacyKey,'{"version":2,"money":500}');const legacy=loadGame(store,0);assert.ok(legacy.error?.includes('測試資料需要重置'));assert.ok(store.getItem(c.save.key+':legacy-backup'));});
test('event-driven speed batching is deterministic across1x2x5x10x',()=>{const a=initialState(42,0);advance(a,180);for(const speed of c.time.speeds){const b=initialState(42,0);for(let i=0;i<1800/speed;i++)advance(b,.1*speed);assert.equal(b.world.dayIndex,a.world.dayIndex);close(b.player.money,a.player.money);assert.equal(b.runStatistics.completedWork,a.runStatistics.completedWork);assert.equal(b.todoQueue.length,a.todoQueue.length);}});
test('dayDuration180 scales anchors and preserves day rules without hardcoded60',()=>{const old=c.time.dayDuration;try{c.time.dayDuration=180;const s=state(60);ensureTarget(s);assert.equal(s.needs.phase,'LUNCH_FOOD');advance(s,24);assert.equal(s.needs.phase,'AFTERNOON');close(s.world.totalWorldTime,84);advance(s,96);assert.equal(s.world.dayIndex,1);}finally{c.time.dayDuration=old;}});

test('problem interruption during lunch cannot extend the world lunch window',()=>{const s=state(24);s.player.money=1000;toggleProduct(s,'wound');s.needs.phase='LUNCH';s.currentTarget={id:'lunch',type:'LUNCH',name:'rest',windowStart:20,windowEnd:28,accumulatedRestOutput:0,createdAt:24};triggerEvent(s,'wound',true);advance(s,4);close(s.world.totalWorldTime,28);close(s.needs.lunchRest,0);assert.equal(s.needs.phase,'AFTERNOON');assert.ok(s.needs.lunchSettled);});
test('nested immediate problems preserve the original work beneath interruption stack',()=>{const s=state();s.player.money=1000;toggleProduct(s,'itch');toggleProduct(s,'wound');const work=running(s,200);triggerEvent(s,'itch',true);ensureTarget(s);const itch=s.currentTarget!.id;triggerEvent(s,'wound',true);ensureTarget(s);assert.equal(s.suspendedTargets.length,2);advance(s,4);assert.equal(s.currentTarget?.id,itch);advance(s,3);assert.equal(s.currentTarget?.id,work.id);assert.equal(s.suspendedTargets.length,0);});
test('expired original debuff cancels pending problem and resumes target',()=>{const s=state();s.player.money=1000;toggleProduct(s,'wound');const work=running(s,200);const d=triggerEvent(s,'wound',true)!;d.expiresAt=1;ensureTarget(s);advance(s,1);assert.equal(s.debuffs.length,0);assert.equal(s.currentTarget?.id,work.id);assert.equal(s.products.wound.contributionStats.problemResolvedCount,0);});
test('subscription stops at billing boundary even while a problem is processing',()=>{const s=state(59);s.player.money=1000;toggleProduct(s,'wound');s.products.wound.nextBillingWorldTime=60;s.player.money=0;const work=running(s,200);triggerEvent(s,'wound',true);advance(s,1);assert.equal(s.products.wound.active,false);assert.equal(s.currentTarget?.id,work.id);assert.ok(s.debuffs.some(d=>d.type==='wound'));});
test('save resumes same active problem and suspended work without settling twice',()=>{const s=state();s.player.money=1000;toggleProduct(s,'wound');const work=running(s,200);triggerEvent(s,'wound',true);advance(s,1);const store=memory();saveGame(s,store,1000);const loaded=loadGame(store,1000);assert.equal(loaded.error,null);assert.deepEqual(loaded.state.currentTarget,s.currentTarget);assert.equal(loaded.state.suspendedTargets[0].target.id,work.id);});
test('corrupted effects recover to V2 rather than crashing simulation',()=>{const s=state();const store=memory();store.setItem(c.save.key,JSON.stringify({...s,debuffs:[null]}));const loaded=loadGame(store,0);assert.ok(loaded.error);assert.ok(store.getItem(c.save.key+':recovery'));assert.ok(validateSave(loaded.state));});

// Legacy Boss Work regression: Meeting outcome disabled only in this test process.
c.meeting.bossMeetingChanceOnEscapeFail=0;

