import { deadlineLabel, getDeadlineStatus } from '../game/work/deadline';
import { OfflineSummaryCard } from '../components/OfflineSummaryCard';
import { workReward, originalWorkReward } from '../game/work/workStats';
import { useState } from 'react';
import { gameConfig as c } from '../config/gameConfig';
import type { Action, NoticeType, State } from '../game/types';
import { decimal, money } from '../utils/format';
export const noticeIcons: Record<NoticeType, string> = { 工作: '▤', 飲食: '🍵', 老闆: '💬', 娛樂: '🎮', 睡眠: '☾', Buff: '↗', Debuff: '↘', 產品: '✧', 升職: '↗', Prestige: '✦', 專案: '🗂️', 離線: '◷', 開會: '👥' };
export function History({ s, dispatch }: { s: State; dispatch: (a: Action) => boolean }) {
  const [filter, setFilter] = useState('全部');
  return <><div className="page-heading"><span className="eyebrow">LIFE, BETWEEN THE LINES</span><h2>今天又發生了什麼？</h2><p>本輪收入 ${money(s.runStatistics.earned)} · 巔峰 ${decimal(s.runStatistics.peakIncome)}／秒</p></div><section className="run-stats"><div><span>完成工作</span><b>{s.runStatistics.completedWork}</b></div><div><span>返工</span><b>{s.runStatistics.reworkCount}</b></div><div><span>最高職級</span><b>{c.ranks[s.career.highestRank].name}</b></div><div><span>已醒來</span><b>{s.permanentStatistics.runs} 次</b></div></section>
  <details className="history-details"><summary>待辦 {s.todoQueue.length} · 延遲後續 {s.pendingFollowUps.length}</summary>{s.todoQueue.slice(0, 40).map(t => { const bad = t.followUpType && ['REWORK','CORRECTION','MISSING_INFO'].includes(t.followUpType); const label = bad ? '🔁 返工' : t.sourceType === 'PROJECT' ? '📁 專案' : t.sourceType === 'BOSS' ? '👔 老闆' : t.sourceType === 'FOLLOW_UP' ? '↪ 後續' : '▤ 普通'; const source = t.projectId ? s.projects.find(p => p.id === t.projectId)?.name : t.sourceType === 'BOSS' ? '老闆' : t.sourceType === 'FOLLOW_UP' ? t.name.split(' · ').at(-1) : '日常工作池'; return <p key={t.id}><b>{label} · {t.name}</b><br /><span className={`deadline-status ${getDeadlineStatus(t,s.world.totalWorldTime).toLowerCase()}`}>{deadlineLabel(t,s.world.totalWorldTime)}</span><br />{getDeadlineStatus(t,s.world.totalWorldTime) === 'OVERDUE' ? `原 $${money(originalWorkReward(s,t))} → 實收 $${money(workReward(s,t))}` : `$${money(workReward(s,t))}`} · 來源：{source} · 品質要求 {decimal(t.qualityRequirement)}</p>; })}{s.pendingFollowUps.map(p => <p key={p.id}>◷ {p.followUpType} · {p.tasksToCreate.length} 份 · {decimal(Math.max(0, p.triggerAtWorldTime - s.world.totalWorldTime))} 秒後</p>)}</details>
  <details><summary>專案進度</summary>{s.projects.map(p => <p key={p.id}>{p.name} · {p.completedSubtasks}／{p.subtasks.length} · {p.status === 'CLOSED' ? '專案已結案' : p.status === 'DELIVERED' ? '主要交付完成，仍有後續事項' : '進行中'}</p>)}</details>
  {s.offline.lastOfflineSummary && <OfflineSummaryCard summary={s.offline.lastOfflineSummary} />}
  <div className="settings-row"><label htmlFor="motion">減少動畫</label><input id="motion" type="checkbox" checked={s.player.settings.reducedMotion} onChange={e => dispatch({ type: 'motion', value: e.target.checked })} /></div><p className="muted">清醒值 {s.prestige.clarity} · 離線累積餘數 {decimal(s.offline.offlineCarryMinutes)} 分鐘 · v{c.version}</p>
  <label className="history-filter">事件篩選<select value={filter} onChange={e => setFilter(e.target.value)}><option>全部</option>{Object.keys(noticeIcons).map(k => <option key={k}>{k}</option>)}</select></label><div className="history-list">{s.eventLog.filter(n => filter === '全部' || n.type === filter).slice().reverse().map(n => <article key={n.id}><span className={`history-icon ${n.type === 'Debuff' ? 'negative' : ''}`}>{noticeIcons[n.type]}</span><div><small>DAY {n.day} · {decimal(n.time)}s · {n.type}</small><p>{n.text}</p></div></article>)}</div><p className="muted">最多保留最近 {c.notifications.historyLimit} 條紀錄。</p></>;
}
