import { getPromotionQualificationStats } from '../game/career/promotionAssignment';
import { getUnresolvedOverdueWorkCount } from '../game/career/promotion';
import { useState } from 'react';
import type { Action, State, UpgradeId } from '../game/types';
import { gameConfig as c } from '../config/gameConfig';
import { rawWorkSpeed, rawWorkQuality, getLifeManagementValue, upgradeCost } from '../game/work/workStats';
import { catchChance, escapeChance } from '../game/career/bossEvents';
import { permanentMultiplier, getPermanentMultiplier, getPrestigeUpgradeCost } from '../game/prestige/permanentUpgrades';
import { decimal, money } from '../utils/format';
function effects(s: State, id: UpgradeId) {
  const next = structuredClone(s); next.player.upgrades[id]++;
  if (id === 'efficiency') return `基礎速度 ${rawWorkSpeed(s)} → ${rawWorkSpeed(next)} 工作量／秒`;
  if (id === 'quality') return `基礎品質 ${rawWorkQuality(s)} → ${rawWorkQuality(next)}；減少品質敏感返工`;
  if (id === 'lifeManagement') return `生活管理值 ${getLifeManagementValue(s)} → ${getLifeManagementValue(next)}`;
  if (id === 'flattery') return `收入 +${decimal(s.player.upgrades.flattery * c.upgrades.flattery.increment * 100)}% → +${decimal(next.player.upgrades.flattery * c.upgrades.flattery.increment * 100)}%；老闆注意度 ${decimal(catchChance(s) * 100)}% → ${decimal(catchChance(next) * 100)}%${catchChance(s)>=1 ? `；必定被老闆找上，急件至少 ×${Math.floor(catchChance(s))}，另有 ${decimal((catchChance(s)%1)*100)}% 機率 ×${Math.floor(catchChance(s))+1}` : ''}`;
  return `成功值 ${c.boss.baseEscapeValue+s.player.upgrades.slacking}；目前逃跑成功率 ${decimal(escapeChance(s) * 100)}% → ${decimal(escapeChance(next) * 100)}%；不影響老闆找到率`;
}
export function Upgrades({ s, dispatch }: { s: State; dispatch: (a: Action) => boolean }) {
  const q=getPromotionQualificationStats(s), requirement=c.promotionQualification.requirements[s.career.rank]; const overdue = getUnresolvedOverdueWorkCount(s); const [tab, setTab] = useState('run'); const next = c.ranks[s.career.rank + 1];
  return <><div className="page-heading"><span className="eyebrow">GROW, AT YOUR OWN PACE</span><h2>把自己練強一點。</h2><p>效率清待辦，品質少留爛攤子。</p></div><div className="button-row"><button aria-pressed={tab === 'run'} onClick={() => setTab('run')}>當輪升級</button><button aria-pressed={tab === 'permanent'} onClick={() => setTab('permanent')}>永久升級 · ✦ {s.prestige.clarity}</button></div>
  {tab === 'run' ? <><div className="upgrade-list">{(Object.keys(c.upgrades) as UpgradeId[]).map(id => { const u = c.upgrades[id]; const cost = upgradeCost(s, id); return <section className="upgrade-card" aria-label={u.name} key={id}><div className="upgrade-icon">{u.icon}</div><div className="upgrade-info"><h3>{u.name} <small>Lv.{s.player.upgrades[id]}</small></h3><p>{u.description}</p><p className="upgrade-effect">{effects(s, id)}</p></div><button className="primary" disabled={s.player.money < cost} onClick={() => dispatch({ type: 'upgrade', id })}>升級 ${money(cost)}</button></section>; })}</div>
  <section className="promotion-card"><span className="eyebrow">PROMOTION ASSIGNMENT</span><h3>{next ? `下一階段：${next.name}` : '已到最高職級'}</h3><p>考核狀態：{{NOT_ELIGIBLE:'尚未符合',ELIGIBLE:'已符合資格',SCHEDULED:'準備開始',ACTIVE:'考核中',COOLDOWN:'重試冷卻中',MAX_RANK:'最高職級',FAILED_REQUIREMENT:'完成時資格失效',FAILED_OVERTIME:'考核失敗・仍須加班完成',COMPLETED_PENDING_DINNER:'已完成・等待下班結算'}[s.promotion.status]}</p>{next && requirement && <><p>穩定效率 {decimal(q.efficiency)} / 需求 {requirement.efficiency} · 穩定品質 {decimal(q.quality)} / 需求 {requirement.quality}</p><p>資格判定效率 {decimal(q.evaluatedEfficiency)} · 品質 {decimal(q.evaluatedQuality)}</p><p>需要資金：${money(s.player.money)} / ${money(next.promotionCost)}</p><p>已逾期工作：{overdue} / 最多 {next.maxOverdueAllowed}</p>{overdue>next.maxOverdueAllowed&&<p role="status">目前仍有過多逾期工作，請先處理工作後再升職。</p>}<p>每次上班評估並立即考核；下班前完成，晚餐錨點再驗證交易條件並扣款升職。</p>{s.promotion.retryAvailableWorkday!==null && <p>可重試工作日：{s.promotion.retryAvailableWorkday+1}</p>}{s.promotion.failureReason&&<p role="status">{s.promotion.failureReason}</p>}</>}<label><input type="checkbox" checked={s.promotion.lowProfileEnabled} onChange={e=>dispatch({type:'lowProfile',value:e.target.checked})}/> 低調摸魚</label><p>僅將升職資格效率／品質乘以 {c.promotionLowProfile.multiplier}，不影響實際工作；下次上班生效，已安排考核不會取消。</p></section></> : <div className="upgrade-list">{c.prestige.upgrades.map(u => { const level = s.prestige.levels[u.id]; const cost = getPrestigeUpgradeCost(u.id,level); return <section key={u.id} className="upgrade-card" aria-label={`永久${u.name}`}><div className="upgrade-info"><h3>{u.name} · Lv.{level}</h3><p>總倍率 ×{permanentMultiplier(s, u.id).toFixed(2)}{` → ×${getPermanentMultiplier(u.id,level+1).toFixed(2)}`}</p><p>醒來後保留，採總倍率而非逐級相乘。</p></div><button disabled={s.prestige.clarity < cost} onClick={() => dispatch({ type: 'permanent', id: u.id })}>{`升級 ✦ ${cost}`}</button></section>; })}</div>}</>;
}
