import fs from 'node:fs';
const output=new URL('../reports/promotion-cost-removal-v1/',import.meta.url);
const seeds=Array.from({length:30},(_,i)=>42+i*7919);
const median=(v:number[])=>quantile(v,.5);
function quantile(v:number[],p:number){if(!v.length)return null;const a=[...v].sort((x,y)=>x-y),i=(a.length-1)*p;return a[Math.floor(i)]+(a[Math.ceil(i)]-a[Math.floor(i)])*(i%1);}
const tables:Record<string,any[]>={workstarts:[],promotions:[],purchases:[],etas:[],ranks:[]};
async function api(prefix:string){const [config,state,loop,actions,stats,promotion]=await Promise.all([import(`${prefix}/config/gameConfig.ts`),import(`${prefix}/game/state/initialState.ts`),import(`${prefix}/game/engine/SimulationLoop.ts`),import(`${prefix}/game/engine/actions.ts`),import(`${prefix}/game/work/workStats.ts`),import(`${prefix}/game/career/promotionAssignment.ts`)]);return {c:config.gameConfig,...state,...loop,...actions,...stats,...promotion};}
async function run(a:any,seed:number,version:string){
 const s=a.initialState(seed,0),ids=Object.keys(a.c.upgrades),income:any[]=[],attempts:any[]=[],rankTimes:any[]=[0,null,null,null,null],firstEQ:any[]=Array(4).fill(null),firstAssigned:any[]=Array(4).fill(null),gaps:any[][]=Array.from({length:5},()=>[]),etaSamples:any[][]=Array.from({length:5},()=>[]);
 let real=0,lastBuy:number|null=null,lastEarned=0,lastRank=0,active:any=null;
 const qualification=()=>{const q=a.getPromotionQualificationStats(s),r=a.c.promotionQualification.requirements[s.career.rank];if(r&&q.evaluatedEfficiency>=r.efficiency&&q.evaluatedQuality>=r.quality)firstEQ[s.career.rank]??=s.runStatistics.activeSeconds;};
 const observe=()=>{
  qualification();const p=s.promotion;
  if(p.assignmentId&&(!active||active.id!==p.assignmentId)){const q=a.getPromotionQualificationStats(s),threshold=a.c.promotionQualification.requirements[s.career.rank].efficiency;active={version,seed,id:p.assignmentId,rank:s.career.rank,start:s.runStatistics.activeSeconds,worldStart:s.world.totalWorldTime,deadline:p.deadlineWorldTime,requirement:p.requirement,...q,actualEfficiency:a.effectiveWorkSpeed(s),thresholdEfficiency:threshold,efficiencyOvershootPercent:(a.effectiveWorkSpeed(s)/threshold-1)*100,dinnerCompletionPercent:null,result:null,overtimeWorld:0,overtimeElapsedReal:0};attempts.push(active);firstAssigned[s.career.rank]??=active.start;}
  if(active&&active.result===null&&s.world.totalWorldTime>=active.deadline-1e-8){active.dinnerCompletionPercent??=Math.min(100,p.progress/active.requirement*100);if(s.career.rank>active.rank){active.result='SUCCESS';active.dinnerCompletionPercent=100;}else if(p.status==='FAILED_OVERTIME'||p.status==='FAILED_REQUIREMENT'){active.result=p.status;active.failureRealSeconds=s.runStatistics.activeSeconds;}}
  if(active?.result==='FAILED_OVERTIME'&&!p.assignmentId&&active.overtimeFinished===undefined){active.overtimeFinished=s.runStatistics.activeSeconds;active.overtimeElapsedReal=active.overtimeFinished-active.failureRealSeconds;}
  if(s.career.rank!==lastRank){lastRank=s.career.rank;rankTimes[lastRank]=s.runStatistics.activeSeconds;tables.ranks.push({version,seed,rank:lastRank,realSeconds:rankTimes[lastRank]});}
 };
 tables.ranks.push({version,seed,rank:0,realSeconds:0});
 while(real<3600-1e-8){
  a.advanceOnline(s,Math.min(.25,3600-real),{onBoundary:observe,onPromotionWorkStart:(row:any)=>{tables.workstarts.push({version,seed,...row,blockingReasons:row.blockingReasons.join('|'),...(version==='BEFORE'?{legacyMoneyQualified:s.player.money>=(a.c.ranks[row.rank+1]?.promotionCost??0)}:{})});},onTargetInterval:(t:any,start:number,seconds:number)=>{if(active&&start+seconds>=active.deadline-1e-8&&start<active.deadline&&active.result===null){active.dinnerCompletionPercent=Math.min(100,s.promotion.progress/active.requirement*100);}if(t?.type==='PROMOTION'&&s.promotion.status==='FAILED_OVERTIME'&&active)active.overtimeWorld+=seconds;}});
  real=s.runStatistics.activeSeconds;
  const earned=s.runStatistics.earned-lastEarned;lastEarned=s.runStatistics.earned;if(earned)income.push({time:real,amount:earned});while(income.length&&income[0].time<real-60)income.shift();
  const rate=income.reduce((n,x)=>n+x.amount,0)/Math.max(.25,Math.min(60,real)),next=ids.map(id=>rate>0?Math.max(0,a.upgradeCost(s,id)-s.player.money)/rate:null);
  if(Math.abs(real-Math.round(real))<1e-6){const value=median(next.filter((x):x is number=>x!==null));if(value!==null)etaSamples[s.career.rank].push(value);tables.etas.push({version,seed,realSeconds:real,rank:s.career.rank,medianNextUpgradeETA:value});}
  for(;;){const affordable=ids.filter(id=>s.player.money>=a.upgradeCost(s,id)).sort((x,y)=>a.upgradeCost(s,x)-a.upgradeCost(s,y)||ids.indexOf(x)-ids.indexOf(y));if(!affordable.length)break;const id=affordable[0],cost=a.upgradeCost(s,id),gap=lastBuy===null?null:real-lastBuy;if(!a.applyAction(s,{type:'upgrade',id}))throw Error('BUY_ALL rejected');if(gap!==null)gaps[s.career.rank].push(gap);tables.purchases.push({version,seed,id,level:s.player.upgrades[id],rank:s.career.rank,realSeconds:real,cost,interval:gap});lastBuy=real;qualification();}
 }
 tables.promotions.push(...attempts);
 return {version,seed,rank:s.career.rank,worldTime:s.world.totalWorldTime,firstEQQualifiedTime:firstEQ,firstPromotionAssignedTime:firstAssigned,qualificationToAssignmentDelay:firstEQ.map((t,i)=>t!==null&&firstAssigned[i]!==null?firstAssigned[i]-t:null),rankTimes,rankDwellSeconds:rankTimes.map((t,i)=>t===null?null:(rankTimes[i+1]??3600)-t),attempts,upgradeIntervalP50ByRank:gaps.map(median),medianNextUpgradeETAByRank:etaSamples.map(median),finalQualification:a.promotionWorkStartTelemetry(s),netMoney:s.player.money,grossIncome:s.runStatistics.earned,levels:s.player.upgrades};
}
const beforeAPI=await api('../reports/promotion-cost-removal-v1/baseline-runtime/src'),afterAPI=await api('../src');
const before:any[]=[],after:any[]=[];
for(const seed of seeds.slice(0,3)){before.push(await run(beforeAPI,seed,'BEFORE'));after.push(await run(afterAPI,seed,'AFTER'));console.log('paired',seed,before.at(-1)?.firstPromotionAssignedTime,after.at(-1)?.firstPromotionAssignedTime);}
const prior=JSON.parse(fs.readFileSync(new URL('../reports/first-company-incremental-v1/buy-all-summary.json',import.meta.url),'utf8'));
const baselineVerified=before.every(r=>{const old=prior.runs.find((x:any)=>x.seed===r.seed);return Math.abs(r.firstPromotionAssignedTime[0]-old.firstPromotionRealSeconds)<1e-7&&Math.abs(r.worldTime-old.worldTime)<1e-7&&Math.abs(r.netMoney-old.netMoney)<1e-7&&JSON.stringify(r.levels)===JSON.stringify(old.levels);});
if(!baselineVerified)throw Error('Previous exact baseline reproduction failed');
const moneyMainCause=before.every((r,i)=>r.firstPromotionAssignedTime[0]>after[i].firstPromotionAssignedTime[0]&&tables.workstarts.some(x=>x.version==='BEFORE'&&x.seed===r.seed&&!x.blockingReasons&&!x.legacyMoneyQualified));
if(moneyMainCause)for(const seed of seeds.slice(3)){after.push(await run(afterAPI,seed,'AFTER'));console.log('expanded',seed,after.at(-1)?.rankTimes);}
const censoredQuantile=(v:(number|null)[],p:number)=>{const a=v.map(x=>x??Infinity).sort((x,y)=>x-y),index=(a.length-1)*p,lo=a[Math.floor(index)],hi=a[Math.ceil(index)];return !Number.isFinite(lo)||!Number.isFinite(hi)?'>60 minutes':(lo+(hi-lo)*(index%1))/60;};
const aggregate={rankTimesMinutes:[1,2,3,4].map(rank=>({rank,reached:after.filter(r=>r.rankTimes[rank]!==null).length,P10:censoredQuantile(after.map(r=>r.rankTimes[rank]),.1),P50:censoredQuantile(after.map(r=>r.rankTimes[rank]),.5),P90:censoredQuantile(after.map(r=>r.rankTimes[rank]),.9)})),byRank:[0,1,2,3,4].map(rank=>{const attempts=after.flatMap(r=>r.attempts.filter((x:any)=>x.rank===rank)),first=after.flatMap(r=>r.attempts.filter((x:any)=>x.rank===rank).slice(0,1));return {rank,attempts:attempts.length,firstSuccessRate:first.length?first.filter(x=>x.result==='SUCCESS').length/first.length:null,firstFailureRate:first.length?first.filter(x=>x.result?.startsWith('FAILED')).length/first.length:null,dinnerObservedCount:attempts.filter(x=>x.dinnerCompletionPercent!==null).length,firstCensoredRate:first.length?first.filter(x=>x.result===null).length/first.length:null,meanDinnerCompletionPercent:attempts.some(x=>x.dinnerCompletionPercent!==null)?attempts.filter(x=>x.dinnerCompletionPercent!==null).reduce((n,x)=>n+x.dinnerCompletionPercent,0)/attempts.filter(x=>x.dinnerCompletionPercent!==null).length:null,meanOvertimeWorldSeconds:attempts.length?attempts.reduce((n,x)=>n+x.overtimeWorld,0)/attempts.length:null,meanOvertimeElapsedRealSeconds:attempts.length?attempts.reduce((n,x)=>n+x.overtimeElapsedReal,0)/attempts.length:null,meanRetries:after.reduce((n,r)=>n+Math.max(0,r.attempts.filter((x:any)=>x.rank===rank).length-1),0)/after.length,upgradeIntervalP50:median(tables.purchases.filter(x=>x.version==='AFTER'&&x.rank===rank&&x.interval!==null).map(x=>x.interval)),medianNextUpgradeETA:median(tables.etas.filter(x=>x.version==='AFTER'&&x.rank===rank&&x.medianNextUpgradeETA!==null).map(x=>x.medianNextUpgradeETA))};})};
const csv=(rows:any[])=>{const keys=[...new Set(rows.flatMap(Object.keys))];return [keys.join(','),...rows.map(r=>keys.map(k=>JSON.stringify(r[k]??'')).join(','))].join('\n')+'\n';};
for(const [name,rows] of Object.entries(tables))fs.writeFileSync(new URL(`${name}.csv`,output),csv(rows));
const result={seeds,horizonRealSeconds:3600,products:'OFF',prestige:'OFF',lowProfile:'OFF',speed:1,purchaseInterval:.25,reserve:0,autoTune:false,baselineVerified,moneyMainCause,before,after,aggregate};
fs.writeFileSync(new URL('results.json',output),JSON.stringify(result,null,2));console.log(JSON.stringify(aggregate,null,2));
