import { writeFile } from 'node:fs/promises';
import { mean,stats } from './balanceMetrics';
import type { Row } from './test-rank-balance';
type Data={settings:Record<string,unknown>;runs:Row[];summaries:Row[];economy:Row[];ageRows:Row[];paired:Row[];flags:Row[];scenarios:Row[]};
export async function writeBalanceReport(dir:string,d:Data){
 const {runs,economy,ageRows,paired,flags,scenarios}=d,m=(g:Row[],k:string)=>mean(g.map(r=>Number(r[k]))),f=(n:number)=>n.toFixed(2);
 const recommended=(days:number,phase:string)=>runs.filter(r=>r.phase===phase&&r.workdays===days&&r.efficiencyBand==='RECOMMENDED'&&r.qualityBand==='RECOMMENDED');
 const rec100=recommended(100,'LONG'),rec30=recommended(30,'MATRIX');
 const rankMean=(rank:number,key:string)=>m(rec100.filter(r=>r.rank===rank),key);
 const worst=(key:string)=>economy.map(r=>Number(r.rank)).sort((a,b)=>rankMean(b,key)-rankMean(a,key))[0];
 const classify=(g:Row[])=>g.filter(r=>r.stability==='UNSTABLE').length/g.length>=.5?'UNSTABLE':m(g,'overdueWorkdaysPercent')>=20||m(g,'projectCapWorkdaysPercent')>=20||g.filter(r=>r.runawayBacklog).length/g.length>=.2?'PRESSURED':'STABLE';
 let text='# Rank 難度／工作壓力／經濟平衡報告\n\n';
 text+=`基準日期：2026-10-06。Config hash：${d.settings.configHash}。全程未改正式 Runtime、Config、玩家 Save／localStorage，未購買、升職、Prestige 或啟用產品。沿用正式引擎，只在臨時 source 副本注入無 RNG、無狀態寫入的計數觀測；Rank0／4 各 30 日與原引擎完整狀態及 RNG deepEqual。正式 source＋Excel＋generated JSON 前後 hash 一致。\n\n`;
 text+='## 1–6. 檔案、Build 與樣本\n\n新增 scripts/test-rank-balance.ts、balanceInstrumentation.ts、balanceMetrics.ts、rankBalanceReport.ts、finalize-rank-balance.ts、tests/balance-metrics.test.ts。沒有修改正式 Runtime，也沒有修改 scripts/test-ranks.ts／reports/rank-tests。\n\n';
 text+='| Rank | 推薦 Level／Value（效率、品質） | LOW Level／Value | HIGH Level／Value |\n|---|---|---|---|\n';
 for(let rank=0;rank<5;rank++){const g=rec30.find(r=>r.rank===rank)!,el=Number(g.efficiencyLevel),ql=Number(g.qualityLevel),c=(d.settings.configSnapshot as typeof import('../src/config/gameConfig').gameConfig);const e=(l:number)=>c.economy.baseWorkSpeed+l*c.upgrades.efficiency.increment,q=(l:number)=>c.economy.baseQuality+l*c.upgrades.quality.increment;text+=`| ${rank} | E${el}/${e(el)}；Q${ql}/${q(ql)} | E${Math.max(0,el-3)}/${e(Math.max(0,el-3))}；Q${Math.max(0,ql-3)}/${q(Math.max(0,ql-3))} | E${el+3}/${e(el+3)}；Q${ql+3}/${q(ql+3)} |\n`;}
 text+=`\n30 日 Matrix：${scenarios.filter(r=>r.phase==='MATRIX'&&r.status==='RUN').length} 個去重 Scenario、${runs.filter(r=>r.phase==='MATRIX').length} Runs。100 日：${scenarios.filter(r=>r.phase==='LONG'&&r.status==='RUN').length} 個去重 Scenario、${runs.filter(r=>r.phase==='LONG'&&r.workdays===100).length} Runs（Day30／60／100 各 checkpoint）。Age cross：15 Scenario、450 邏輯 Runs，其中 Age22 150 筆完全重用 Matrix，新增300條；物理總數 ${d.settings.physicalRuns}，每日快照 ${d.settings.dailyCount}。所有 Matrix 用相同30 seeds，Long用同組前50 seeds，Cross用前30 seeds。Rank0 LOW=RECOMMENDED 的重複組合列入 scenarios.csv 的 DUPLICATE，不額外跑、不重複計入統計。\n\n`;
 text+='## 7–8. 推薦 Build 主表\n\n';
 for(const [days,g]of [[30,rec30],[100,rec100]] as const){text+=`### ${days} 工作日（各 Rank Mean，完整 Median／P10／P90 在 summary.csv）\n\n| Rank | Avg Todo | Final Todo | Peak Todo | Avg Due | Avg Overdue | Peak Overdue | Overdue days % | Generated/day | Processed/day | Ratio | Outstanding slope | Income/day | Loss % | Cap days % | Promotion eligible % |\n|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|\n`;for(let rank=0;rank<5;rank++){const group=g.filter(r=>r.rank===rank);text+=`| ${rank} | ${['averageTodo','finalTodo','peakTodo','averageDueToday','averageOverdue','peakOverdue','overdueWorkdaysPercent','generatedWorkloadPerDay','processedWorkloadPerDay','processedGeneratedWorkloadRatio','outstandingWorkloadTrendSlope','grossIncomePerWorkday','overdueLossPercent','projectCapWorkdaysPercent'].map(k=>f(m(group,k))).join(' | ')} | ${rank===4?'N/A':f(m(group,'fullyPromotionEligibleDaysPercent'))} |\n`;}text+='\n';}
 text+='## 9–12. 長期穩定性與主要壓力\n\n';
 for(let rank=0;rank<5;rank++){const g=rec100.filter(r=>r.rank===rank);text+=`- Rank${rank}：**${classify(g)}**；UNSTABLE seeds ${g.filter(r=>r.stability==='UNSTABLE').length}/50，RUNAWAY flags ${g.filter(r=>r.runawayBacklog).length}/50；期末 outstanding 均值 ${f(m(g,'outstandingWorkloadEnd'))}，最終20日 slope ${f(m(g,'outstandingWorkloadTrendSlope'))}，前10日 outstanding 均值 ${f(m(g,'first10AverageOutstandingWorkload'))}。\n`;}
 text+=`\n推薦100日平均 backlog（Todo）最大 Rank${worst('averageTodo')}；Overdue 最大 Rank${worst('averageOverdue')}；Project cap 最常達上限 Rank${worst('projectCapWorkdaysPercent')}。最大平均不表示所有種子皆失控，請搭配 P90／Max。\n\n`;
 text+='## 13–16. Efficiency／Quality paired comparison\n\n相同初始 seed，不代表完全相同外生事件；速度、品質與完成順序會改變後續 RNG call order。下表 HIGH−RECOMMENDED 固定另一能力在推薦；兩側30 seeds。LOW 的全部配對在 CSV。\n\n| Rank | Axis | Δ Processed Workload | Δ Ratio | Δ Avg Todo | Δ Avg Overdue | Δ Avoidable/source ratio | Δ Gross Income |\n|---|---|---:|---:|---:|---:|---:|---:|\n';
 for(let rank=0;rank<5;rank++)for(const axis of ['efficiency','quality']){const g=paired.filter(r=>r.rank===rank&&r.axis===axis&&r.comparison==='HIGH_MINUS_RECOMMENDED'&&r[axis==='efficiency'?'qualityBand':'efficiencyBand']==='RECOMMENDED');text+=`| ${rank} | ${axis} | ${['delta_processedWorkload','delta_processedGeneratedWorkloadRatio','delta_averageTodo','delta_averageOverdue','delta_avoidableFollowUpRatio','delta_grossIncome'].map(k=>f(m(g,k))).join(' | ')} |\n`;}
 const highQ=paired.filter(r=>r.axis==='quality'&&r.comparison==='HIGH_MINUS_RECOMMENDED'),highE=paired.filter(r=>r.axis==='efficiency'&&r.comparison==='HIGH_MINUS_RECOMMENDED');
 text+=`\nQuality 配對中 Avoidable/source ratio 上升的種子 ${highQ.filter(r=>Number(r.delta_avoidableFollowUpRatio)>0).length}/${highQ.length}；這是觀測異常候選，單一 seed 可能因路徑或工作組成改變，不直接當 Bug。Efficiency 提高但平均 Todo 上升的種子 ${highE.filter(r=>Number(r.delta_averageTodo)>0).length}/${highE.length}；不以件數 alone 認定更難。\n\n`;
 text+='結構來源：正式補單依 Todo 水位，效率提高可讓普通補單更頻繁、專案步驟更快解鎖，完成更多來源工作也可產生更多後續。請看 paired 的 ΔGeneratedWorkload、ΔProcessedWorkload、ΔFollowUpsGenerated、ΔAvoidableRatio 和長期 slope；相同 seed 分歧並不能完全分離 RNG noise 與結構因果。本輪沒有做更改外生事件的干預實驗。\n\n';
 text+='## 17–21. Rank Economy（推薦100日）\n\n| Rank | Gross/day | Income/processed workload | Loss/Potential % | Parent bonus % | Boss income % | Follow-up income % | Promotion overdue-block-after-money % | Income growth % | Generated workload growth % | Promotion cost/gross days |\n|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|\n';
 for(const r of economy){text+=`| ${r.rank} | ${['grossIncomePerWorkday','incomePerProcessedWorkload','overdueLossPercent','parentBonusPercent','bossIncomePercent','followUpIncomePercent'].map(k=>f(Number(r[k]))).join(' | ')} | ${r.rank===4?'N/A':f(rankMean(Number(r.rank),'promotionBlockedAfterMoneyPercent'))} | ${r.incomeGrowthPercent===null?'N/A':f(Number(r.incomeGrowthPercent))} | ${r.workloadGrowthPercent===null?'N/A':f(Number(r.workloadGrowthPercent))} | ${r.promotionCostInGrossIncomeDays===null?'N/A':f(Number(r.promotionCostInGrossIncomeDays))} |\n`;}
 text+='\n這是免費設定既有能力後的運作狀態，不扣不存在的 Upgrade 購買費；Products 全OFF。Promotion cost/gross days 只是毛收入參考，不包含升級、產品或其他消費，不能視為實際升職時間。收入成長超過工作量成長本身不能證明經濟合理。Full Potential=已完成 Work 原報酬＋實際 Parent Bonus，不包含未完成工作的假收入。\n\n';
 text+='## 22. Age Crosscheck（推薦30日，Products 全OFF）\n\n| Rank | Age | Avg Todo | Avg Overdue | Final outstanding | Outstanding slope | Overdue days % | Income/day |\n|---|---|---:|---:|---:|---:|---:|---:|\n';
 for(let rank=0;rank<5;rank++)for(const age of [22,50,60]){const g=ageRows.filter(r=>r.rank===rank&&r.ageStart===age);text+=`| ${rank} | ${age} | ${['averageTodo','averageOverdue','outstandingWorkloadEnd','outstandingWorkloadTrendSlope','overdueWorkdaysPercent','grossIncomePerWorkday'].map(k=>f(m(g,k))).join(' | ')} |\n`;}
 text+='\n30日年齡交叉只識別新壓力候選，不能證明100日崩潰。Age50/60 壓力增加時需另跑同 Rank×Age 長期測試；本次不混入 Agecare。\n\n';
 text+='## 23. Diagnostic flags 與判斷門檻\n\n全部 seed／checkpoint flags 在 rank-balance-flags.csv，都是觀測標記，不是自動調值門檻。\n\n- RUNAWAY：最後20日 outstanding slope > max(1單位/日、前10日均值1%/日)，且期末 > max(前10日均值×2、前10日均值＋一日平均生成量)。\n- PERSISTENT_OVERDUE：每日上班取樣有逾期的日數 ≥50%。\n- PROMOTION_OVERDUE_BLOCK：資金達標取樣日中，被逾期擋住 ≥25%。Rank4 N/A。\n- PROJECT_CAP_SATURATION：每日上班取樣 ACTIVE=cap ≥20%，且 chance成功後被cap阻擋 ≥20%。\n- ECONOMY_LOSS_HIGH：Loss% 超過五 Rank 推薦100日均值的 Q3+1.5 IQR，或超過同 Rank 推薦均值2倍且高至少2百分點。\n\nSTABLE／PRESSURED／UNSTABLE 都是有限100日診斷。seed若同時有 RUNAWAY＋Todo／Overdue 正 slope 則 UNSTABLE；其他若有RUNAWAY或逾期／cap日≥20%則PRESSURED。Rank判斷需至少50% seeds UNSTABLE才稱UNSTABLE；若有≥20% runaway seeds或平均逾期／cap≥20%則PRESSURED。門檻公開可重分析，無法從有限樣本宣稱「必然不可逆」。\n\n| Flag | Records（跨 checkpoints，不等於独立 runs） |\n|---|---:|\n';
 for(const flag of ['RUNAWAY_BACKLOG','PERSISTENT_OVERDUE','PROMOTION_OVERDUE_BLOCK','PROJECT_CAP_SATURATION','ECONOMY_LOSS_HIGH'])text+=`| ${flag} | ${flags.filter(r=>r.flag===flag).length} |\n`;
 text+='\n## 24. Runner sanity\n\n通過：所有數字有限；count/workload/income非負；實際 Progress 增量計 processed；每工作日 generated−processed=remaining，未發現合法 work removal（Removed=0，有移除將直接使守恆 fail，不隱藏）；source income＋Parent Bonus=Gross；Loss≤Potential；Rank固定；產品OFF；無Prestige；指定初始Age；所有seed列表一致；臨時觀測與原引擎完整state/RNG一致；正式source/config hash不變。\n\n';
 text+=`最大工作量守恆誤差 ${d.settings.maxConservationError}（容許 1e-5，浮點误差）；初始Outstanding=0。Closed Project close time 只統計已CLOSED的專案，未結案樣本為右設限、不能視為0天，另有 closed sample count。\n\n`;
 text+='## 25–26. 只選五個人工試玩候選\n\n';
 const ageWorstRank=[0,1,2,3,4].sort((a,b)=>m(ageRows.filter(r=>r.rank===b&&r.ageStart===60),'averageOverdue')-m(ageRows.filter(r=>r.rank===a&&r.ageStart===60),'averageOverdue'))[0];
 const candidates=[{rank:0,e:'RECOMMENDED',q:'RECOMMENDED',age:22,reason:'新人基準，確認補單／返工循環是否清楚'}, {rank:4,e:'RECOMMENDED',q:'RECOMMENDED',age:22,reason:'經理推薦Build的Project上限與收入節奏'}, {rank:4,e:'LOW',q:'HIGH',age:22,reason:'隔離低處理速度與較低可避免返工的不同感受'}, {rank:3,e:'HIGH',q:'LOW',age:22,reason:'觀察完成加快是否帶來更多後續工作，對照100日期末積壓反例'}, {rank:ageWorstRank,e:'RECOMMENDED',q:'RECOMMENDED',age:60,reason:'Age60 平均逾期最高的交叉情境'}];
 for(const t of candidates)text+=`- Rank${t.rank}／Efficiency ${t.e}／Quality ${t.q}／Age${t.age}／Products OFF：${t.reason}。實際 Lv 請查 Build 表，不新增負 Lv。\n`;
 text+='\n## 27. 本輪判斷與後續\n\n';
 const unstableRanks=[0,1,2,3,4].filter(rank=>classify(rec100.filter(r=>r.rank===rank))==='UNSTABLE'),pressured=[0,1,2,3,4].filter(rank=>classify(rec100.filter(r=>r.rank===rank))==='PRESSURED');
 text+=`${unstableRanks.length?'C：存在明顯長期失衡候選，需先針對該 Rank 驗證。':pressured.length?'B：推薦Build大致可運作，但有壓力職級／情境需後續調查；尚不能從本輪直接指定哪個參數要調。':'A：Age22推薦Build在100日測試可接受，暫無明確需要調值證據。'} UNSTABLE Rank：${unstableRanks.join('、')||'無'}；PRESSURED Rank：${pressured.join('、')||'無'}。年齡或低能力結果不可替代推薦Build判斷。沒有修改任何平衡數值。\n\n`; 
 text+='建議下一輪先用壓力來源CSV拆出 Project／Follow-up／Boss 的工作量與收入占比，再針對少數異常長期重跑更多種子；不要用完成件數或單次期末推定崩潰。效率／品質配對反例需檢查工作組成與返工比率，不直接認定公式Bug。\n\n## 指標／匯出與重跑\n\nAverage/Median/P10/P90/Peak Todo、Due、Overdue 使用每日上班錨點快照（不是事件時間加權）；100日每checkpoint的trend用其最後20日OLS。統計摘要跨seed列Mean/Median/P10/P90/Min/Max/N與近似t 95%CI（30 seeds t=2.045，50 seeds≈2.01），未校正多重比較。收益source包含EVENT，未分類差額要求為0；Project Parent Bonus獨立計入。\n\n每日第一區間含Day1早餐，期末取Day(N+1)上班錨點；workdayIndex由正式Deadline helper決定。Age22 reused無重複daily行，可用scenario manifest追到MATRIX基準。Source Overdue Count分列逾期完成與期末尚未完成；CloseTime以遊戲工作日單位，樣本僅已closed。\n\n執行 npx tsx scripts/test-rank-balance.ts。輸出目錄 reports/rank-balance；JSON保留完整設定、種子、runs、summary與flags，largest daily僅CSV（JSON有路徑說明）。文件不覆寫Rank Content測試結果。\n';
 await writeFile(`${dir}/RANK_BALANCE_REPORT.md`,text);
}
