import { mkdir,writeFile,appendFile,readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';
import assert from 'node:assert/strict';
import { gameConfig as c } from '../src/config/gameConfig';
import { initialState } from '../src/game/state/initialState';
import { getDeadlineStatus,getDeadlineWorkdayIndex } from '../src/game/work/deadline';
import { canPromote,getUnresolvedOverdueWorkCount } from '../src/game/career/promotion';
import { effectiveWorkSpeed,effectiveWorkQuality } from '../src/game/work/workStats';
import { validateSave } from '../src/game/save/saveGame';
import type { State,Todo } from '../src/game/state/gameState';
import { instrument,setBalanceHooks,sourceHash } from './balanceInstrumentation';
import { mean,quantile,slope,longest,stats } from './balanceMetrics';
import { writeBalanceReport } from './rankBalanceReport';
import { finalizeBalance } from './finalize-rank-balance';
export type Row=Record<string,string|number|boolean|null>;
const dir=fileURLToPath(new URL('../reports/rank-balance/',import.meta.url));await mkdir(dir,{recursive:true});
const originalHash=await sourceHash(),configHash=createHash('sha256').update(await readFile(new URL('../config/generated/game_config.json',import.meta.url))).digest('hex');
const engine=await instrument(),seeds=Array.from({length:50},(_,i)=>42+i*7919),bands=['LOW','RECOMMENDED','HIGH'] as const;
const scenarios:Row[]=[],runs:Row[]=[],sourceRows:Row[]=[],followRows:Row[]=[],projectRows:Row[]=[],promotionRows:Row[]=[],bossRows:Row[]=[],ageRows:Row[]=[],flags:Row[]=[];
const cachedRecommended=new Map<string,Row>();let dailyHeaders:string[]=[],physicalRuns=0,dailyCount=0,maxConservationError=0;
function csvText(rows:Row[],keys=Object.keys(rows[0])){const escape=(v:unknown)=>{const s=v==null?'N/A':String(v);return /[",\n]/.test(s)?'"'+s.replaceAll('"','""')+'"':s;};return rows.map(r=>keys.map(k=>escape(r[k])).join(',')).join('\n')+'\n';}
async function csv(name:string,rows:Row[]){if(!rows.length)return;const keys=[...new Set(rows.flatMap(r=>Object.keys(r)))];await writeFile(`${dir}/${name}.csv`,'\uFEFF'+keys.join(',')+'\n'+csvText(rows,keys));}
function live(s:State){return [...new Map([...s.todoQueue,...(s.currentTarget?.type==='WORK'?[s.currentTarget.todo]:[]),...s.suspendedTargets.flatMap(x=>x.target.type==='WORK'?[x.target.todo]:[])].map(t=>[t.id,t])).values()];}
function outstanding(s:State){const progress=new Map([s.currentTarget,...s.suspendedTargets.map(x=>x.target)].flatMap(t=>t?.type==='WORK'?[[t.todo.id,t.progress] as const]:[]));return live(s).reduce((n,t)=>n+t.workload-(progress.get(t.id)??0),0);}
function levels(rank:number){const efficiency=Math.max(0,Math.round((c.ranks[rank].recommendedSpeed-c.economy.baseWorkSpeed)/c.upgrades.efficiency.increment)),quality=Math.max(0,Math.round((c.ranks[rank].recommendedQuality-c.economy.baseQuality)/c.upgrades.quality.increment));return {efficiency,quality};}
const bandLevel=(level:number,band:string)=>band==='LOW'?Math.max(0,level-3):band==='HIGH'?level+3:level;
function sanity(row:Row){for(const [key,value]of Object.entries(row))if(typeof value==='number'){assert.ok(Number.isFinite(value),key);if(!/Trend|Slope|Delta|Change|Error/.test(key))assert.ok(value>=-1e-7,key);}}
async function run(phase:string,rank:number,eBand:string,qBand:string,age:number,seed:number,days:number,aliases:string){
 physicalRuns++;const rec=levels(rank),efficiencyLevel=bandLevel(rec.efficiency,eBand),qualityLevel=bandLevel(rec.quality,qBand),scenarioId=`${phase}-r${rank}-e${efficiencyLevel}-q${qualityLevel}-a${age}`;
 const s=initialState(seed,0);s.career.rank=rank;s.career.highestRank=rank;s.player.upgrades.efficiency=efficiencyLevel;s.player.upgrades.quality=qualityLevel;s.player.age=age;s.player.ageProgressDays=(age-c.age.start)*c.age.daysPerYear;
 assert.equal(s.player.age,age);
 const meta:Row={configHash,scenarioId,phase,seed,rank,rankName:c.ranks[rank].name,ageStart:age,workdays:days,efficiencyLevel,efficiencyValue:effectiveWorkSpeed(s),efficiencyBand:eBand,qualityLevel,qualityValue:effectiveWorkQuality(s),qualityBand:qBand,aliases,recommendedEfficiencyLevel:rec.efficiency,recommendedEfficiencyValue:c.economy.baseWorkSpeed+rec.efficiency*c.upgrades.efficiency.increment,recommendedQualityLevel:rec.quality,recommendedQualityValue:c.economy.baseQuality+rec.quality*c.upgrades.quality.increment};
 const counters:Record<string,number>={generatedWorkCount:0,generatedWorkload:0,processedWorkload:0,completedWork:0,grossWorkIncome:0,fullPotentialWorkIncome:0,overdueRevenueLoss:0,followUpsGenerated:0,reworkGenerated:0,projectsStarted:0,projectsDelivered:0,projectsClosed:0,projectSpawnAttempts:0,projectChancePassed:0,projectSpawnBlockedByMaximumActive:0,bossChecks:0,bossCaught:0,bossEscaped:0,bossTasksGenerated:0};
 const sources=new Map<string,Record<string,number>>(),followTypes=new Map<string,number>();
 const getSource=(id:string)=>{if(!sources.has(id))sources.set(id,{generatedCount:0,generatedWorkload:0,processedWorkload:0,completedCount:0,grossIncome:0,overdueCompletedCount:0,overdueRevenueLoss:0});return sources.get(id)!;};
 const seen=new Set<string>(),followSeen=new Set<string>(),projectSeen=new Set<string>(),delivered=new Set<string>(),closed=new Set<string>(),closeTimes:number[]=[];
 let activeTodo:Todo|undefined,peakActive=0;const snapshots:Row[]=[],first10:number[]=[];let previousCounters={...counters},previousGross=0,previousPotential=0,previousParent=0,previousCompletedProjects=0;
 setBalanceHooks({projectAttempt:()=>counters.projectSpawnAttempts++,projectPassed:blocked=>{counters.projectChancePassed++;if(blocked)counters.projectSpawnBlockedByMaximumActive++;},boss:(caught,escaped)=>{counters.bossChecks++;if(caught)counters.bossCaught++;if(escaped)counters.bossEscaped++;}});
 const observe={onWorkProgress:(amount:number)=>{assert.ok(amount>=-1e-8);counters.processedWorkload+=amount;assert.ok(activeTodo);getSource(activeTodo.sourceType).processedWorkload+=amount;},onWorkCompleted:(todo:Todo,overdue:boolean,loss:number)=>{
  const potential=engine.reward.originalWorkReward(s,todo),actual=potential-loss,src=getSource(todo.sourceType);counters.completedWork++;counters.fullPotentialWorkIncome+=potential;counters.grossWorkIncome+=actual;counters.overdueRevenueLoss+=loss;src.completedCount++;src.grossIncome+=actual;src.overdueRevenueLoss+=loss;if(overdue)src.overdueCompletedCount++;
 },onBoundary:()=>{
  const ts=live(s);activeTodo=s.currentTarget?.type==='WORK'?s.currentTarget.todo:undefined;
  for(const t of ts)if(!seen.has(t.id)){seen.add(t.id);counters.generatedWorkCount++;counters.generatedWorkload+=t.workload;const src=getSource(t.sourceType);src.generatedCount++;src.generatedWorkload+=t.workload;if(t.sourceType==='BOSS')counters.bossTasksGenerated++;}
  for(const t of [...ts,...s.pendingFollowUps.flatMap(p=>p.tasksToCreate)])if(t.followUpType&&!followSeen.has(t.id)){followSeen.add(t.id);counters.followUpsGenerated++;followTypes.set(t.followUpType,(followTypes.get(t.followUpType)??0)+1);if(['REWORK','CORRECTION','MISSING_INFO'].includes(t.followUpType))counters.reworkGenerated++;}
  for(const p of s.projects){if(!projectSeen.has(p.id)){projectSeen.add(p.id);counters.projectsStarted++;}if(p.completedSubtasks===p.subtasks.length&&!delivered.has(p.id)){delivered.add(p.id);counters.projectsDelivered++;}if(p.status==='CLOSED'&&!closed.has(p.id)){closed.add(p.id);counters.projectsClosed++;closeTimes.push((s.world.totalWorldTime-p.createdAt)/c.time.dayDuration);}}
  peakActive=Math.max(peakActive,s.projects.filter(p=>p.status==='ACTIVE').length);
 }};
 for(let day=1;day<=days;day++){
  const end=day*c.time.dayDuration+c.time.workStartAnchor*c.time.dayDuration/c.time.referenceDayDuration;engine.advance(s,end-s.world.totalWorldTime,observe);
  const ts=live(s),todo=ts.length,due=ts.filter(t=>getDeadlineStatus(t,s)==='DUE_TODAY').length,overdue=getUnresolvedOverdueWorkCount(s),remaining=outstanding(s),error=counters.generatedWorkload-counters.processedWorkload-remaining;
  maxConservationError=Math.max(maxConservationError,Math.abs(error));assert.ok(Math.abs(error)<1e-5,'workload conservation');assert.ok(validateSave(s));assert.equal(s.career.rank,rank);assert.ok(Object.values(s.products).every(p=>!p.active));assert.equal(s.permanentStatistics.runs,0);assert.equal(s.runStatistics.completedWork,counters.completedWork);
  const sourceIncome=[...sources.values()].reduce((n,x)=>n+x.grossIncome,0);assert.ok(Math.abs(sourceIncome-counters.grossWorkIncome)<1e-5);
  const parentBonus=s.runStatistics.earned-counters.grossWorkIncome,potentialIncome=s.runStatistics.earned+counters.overdueRevenueLoss;assert.ok(parentBonus>=0);assert.ok(counters.overdueRevenueLoss<=potentialIncome);
  const next=c.ranks[rank+1],moneyOK=next?s.player.money>=next.promotionCost:null,overdueOK=next?overdue<=next.maxOverdueAllowed:null;
  const snapshot:Row={...meta,day,workdayIndex:getDeadlineWorkdayIndex(s.world.totalWorldTime),efficiencyValue:s.stats.workSpeed,qualityValue:s.stats.workQuality,totalMoney:s.player.money,todoCount:todo,dueTodayCount:due,overdueCount:overdue,outstandingWorkload:remaining,
   generatedWorkCountToday:counters.generatedWorkCount-previousCounters.generatedWorkCount,generatedWorkloadToday:counters.generatedWorkload-previousCounters.generatedWorkload,processedWorkloadToday:counters.processedWorkload-previousCounters.processedWorkload,completedWorkToday:counters.completedWork-previousCounters.completedWork,grossIncomeToday:s.runStatistics.earned-previousGross,fullPotentialIncomeToday:potentialIncome-previousPotential,overdueRevenueLossToday:counters.overdueRevenueLoss-previousCounters.overdueRevenueLoss,
   followUpsGeneratedToday:counters.followUpsGenerated-previousCounters.followUpsGenerated,reworkGeneratedToday:counters.reworkGenerated-previousCounters.reworkGenerated,projectsStartedToday:counters.projectsStarted-previousCounters.projectsStarted,projectsCompletedToday:s.runStatistics.projectsCompleted-previousCompletedProjects,activeProjectCount:s.projects.filter(p=>p.status==='ACTIVE').length,bossTasksGeneratedToday:counters.bossTasksGenerated-previousCounters.bossTasksGenerated,promotionMoneyRequirementMet:moneyOK,promotionOverdueRequirementMet:overdueOK,promotionEligible:next?canPromote(s):null,promotionBlockedByOverdue:next?Boolean(moneyOK&&!overdueOK):null,projectParentBonusToday:parentBonus-previousParent,removedWorkloadToday:0,conservationError:error};
  sanity(snapshot);snapshots.push(snapshot);if(day<=10)first10.push(remaining);previousCounters={...counters};previousGross=s.runStatistics.earned;previousPotential=potentialIncome;previousParent=parentBonus;previousCompletedProjects=s.runStatistics.projectsCompleted;
  if((phase==='LONG'&&[30,60,100].includes(day))||(phase!=='LONG'&&day===days)){
   const values=(key:string)=>snapshots.map(r=>Number(r[key])),row:Row={...meta,workdays:day,...counters,removedWorkload:0,outstandingWorkloadStart:0,outstandingWorkloadEnd:remaining,netWorkloadDelta:counters.generatedWorkload-counters.processedWorkload,processedGeneratedWorkloadRatio:counters.processedWorkload/counters.generatedWorkload,grossIncome:s.runStatistics.earned,fullPotentialIncome:potentialIncome,overdueLossPercent:counters.overdueRevenueLoss/potentialIncome*100,grossIncomePerWorkday:s.runStatistics.earned/day,incomePerProcessedWorkload:s.runStatistics.earned/counters.processedWorkload,projectParentBonusIncome:parentBonus,projectParentBonusPercent:parentBonus/s.runStatistics.earned*100,generatedWorkloadPerDay:counters.generatedWorkload/day,processedWorkloadPerDay:counters.processedWorkload/day,first10AverageOutstandingWorkload:mean(first10),outstandingWorkloadTrendSlope:slope(values('outstandingWorkload').slice(-20)),avoidableFollowUpRatio:counters.reworkGenerated/counters.completedWork,overdueWorkdaysPercent:values('overdueCount').filter(n=>n>0).length/day*100,longestConsecutiveOverdueDays:longest(values('overdueCount').map(n=>n>0)),averageActiveProjects:mean(values('activeProjectCount')),peakActiveProjects:peakActive,projectCapWorkdaysPercent:values('activeProjectCount').filter(n=>n>=c.projects.maximumActive).length/day*100,averageProjectCloseTime:mean(closeTimes),medianProjectCloseTime:quantile(closeTimes,.5),bossCatchPercent:counters.bossCaught/counters.bossChecks*100,bossEscapeSuccessPercent:counters.bossCaught?counters.bossEscaped/counters.bossCaught*100:0,moneyEligibleDaysPercent:next?snapshots.filter(r=>r.promotionMoneyRequirementMet).length/day*100:null,fullyPromotionEligibleDaysPercent:next?snapshots.filter(r=>r.promotionEligible).length/day*100:null,overdueBlockedDaysAfterMoneyMet:next?snapshots.filter(r=>r.promotionBlockedByOverdue).length:null,promotionBlockedAfterMoneyPercent:next?snapshots.filter(r=>r.promotionBlockedByOverdue).length/Math.max(1,snapshots.filter(r=>r.promotionMoneyRequirementMet).length)*100:null,longestPromotionBlockedDays:next?longest(snapshots.map(r=>r.promotionEligible===false)):null};
   for(const [name,key]of [['Todo','todoCount'],['DueToday','dueTodayCount'],['Overdue','overdueCount']] as const){const xs=values(key);row[`average${name}`]=mean(xs);row[`median${name}`]=quantile(xs,.5);row[`final${name}`]=xs.at(-1)!;row[`peak${name}`]=Math.max(...xs);row[`p10${name}`]=quantile(xs,.1);row[`p90${name}`]=quantile(xs,.9);row[`${name.toLowerCase()}TrendSlope`]=slope(xs.slice(-20));}
   for(const name of ['NORMAL','BOSS','PROJECT','FOLLOW_UP','EVENT']){const src=getSource(name);sourceRows.push({...meta,workdays:day,source:name,...src,finalOverdueCount:ts.filter(t=>t.sourceType===name&&getDeadlineStatus(t,s)==='OVERDUE').length});row[`${name.toLowerCase()}Income`]=src.grossIncome;}
   for(const type of c.followUps.types)followRows.push({...meta,workdays:day,followUpType:type.type,generatedCount:followTypes.get(type.type)??0,percentage:counters.followUpsGenerated?(followTypes.get(type.type)??0)/counters.followUpsGenerated*100:0});
   const tail=snapshots.slice(-20),trend=Number(row.outstandingWorkloadTrendSlope),first=Number(row.first10AverageOutstandingWorkload),runaway=trend>Math.max(1,first*.01)&&remaining>Math.max(first*2,first+Number(row.generatedWorkloadPerDay));
   row.runawayBacklog=runaway;row.stability=runaway&&Number(row.overdueTrendSlope)>0&&Number(row.todoTrendSlope)>0?'UNSTABLE':Number(row.overdueWorkdaysPercent)>20||Number(row.projectCapWorkdaysPercent)>20||runaway?'PRESSURED':'STABLE';
   sanity(row);runs.push(row);
   for(const [flag,yes]of [['RUNAWAY_BACKLOG',runaway],['PERSISTENT_OVERDUE',Number(row.overdueWorkdaysPercent)>=50],['PROMOTION_OVERDUE_BLOCK',next&&Number(row.promotionBlockedAfterMoneyPercent)>=25],['PROJECT_CAP_SATURATION',Number(row.projectCapWorkdaysPercent)>=20&&counters.projectSpawnBlockedByMaximumActive/Math.max(1,counters.projectChancePassed)>=20/100]] as const)if(yes)flags.push({...meta,workdays:day,flag,evidence:JSON.stringify({trend,first10Mean:first,final:remaining,overdueDaysPercent:row.overdueWorkdaysPercent,promotionBlockPercent:row.promotionBlockedAfterMoneyPercent,capDaysPercent:row.projectCapWorkdaysPercent,blocked:counters.projectSpawnBlockedByMaximumActive,passed:counters.projectChancePassed})});
   projectRows.push({...meta,workdays:day,spawnAttempts:counters.projectSpawnAttempts,chancePassed:counters.projectChancePassed,spawnSuccess:counters.projectsStarted,blockedByMaximumActive:counters.projectSpawnBlockedByMaximumActive,projectsStarted:counters.projectsStarted,projectsDelivered:counters.projectsDelivered,projectsClosed:counters.projectsClosed,averageActiveProjects:row.averageActiveProjects,peakActiveProjects:peakActive,workdaysAtMaximumActivePercent:row.projectCapWorkdaysPercent,averageProjectCloseTime:row.averageProjectCloseTime,medianProjectCloseTime:row.medianProjectCloseTime,closedProjectsSampleCount:closeTimes.length,subtaskGeneratedWorkload:getSource('PROJECT').generatedWorkload,subtaskCompletedCount:getSource('PROJECT').completedCount,parentBonusIncome:parentBonus,projectWorkIncome:getSource('PROJECT').grossIncome});
   promotionRows.push({...meta,workdays:day,moneyEligibleDaysPercent:row.moneyEligibleDaysPercent,fullyEligibleDaysPercent:row.fullyPromotionEligibleDaysPercent,overdueBlockedDaysAfterMoneyMet:row.overdueBlockedDaysAfterMoneyMet,promotionBlockedAfterMoneyPercent:row.promotionBlockedAfterMoneyPercent,longestBlockedDays:row.longestPromotionBlockedDays});
   bossRows.push({...meta,workdays:day,checks:counters.bossChecks,caught:counters.bossCaught,catchPercent:row.bossCatchPercent,escaped:counters.bossEscaped,escapeSuccessPercent:row.bossEscapeSuccessPercent,...getSource('BOSS')});
   if(phase==='MATRIX'&&eBand==='RECOMMENDED'&&qBand==='RECOMMENDED')cachedRecommended.set(`${rank}:${seed}`,row);
   if(phase==='AGE')ageRows.push(row);
  }
 }
 setBalanceHooks();if(!dailyHeaders.length){dailyHeaders=Object.keys(snapshots[0]);await writeFile(`${dir}/rank-balance-daily.csv`,'\uFEFF'+dailyHeaders.join(',')+'\n');}await appendFile(`${dir}/rank-balance-daily.csv`,csvText(snapshots,dailyHeaders));dailyCount+=snapshots.length;
}
function uniqueBuilds(rank:number,pairs:[string,string][]){const rec=levels(rank),map=new Map<string,{e:string;q:string;aliases:string[]}>();for(const [e,q]of pairs){const key=`${bandLevel(rec.efficiency,e)}:${bandLevel(rec.quality,q)}`,old=map.get(key);if(old){old.aliases.push(`${e}/${q}`);if(e==='RECOMMENDED'&&q==='RECOMMENDED'){old.e=e;old.q=q;}scenarios.push({configHash,rank,rankName:c.ranks[rank].name,seed:'ALL',ageStart:22,workdays:0,efficiencyBand:e,qualityBand:q,status:'DUPLICATE',canonicalLevels:key});}else map.set(key,{e,q,aliases:[`${e}/${q}`]});}return [...map.values()];}
for(const phase of ['MATRIX','LONG'])for(let rank=0;rank<5;rank++){
 const pairs:[string,string][]=phase==='MATRIX'?bands.flatMap(e=>bands.map(q=>[e,q] as [string,string])):[['LOW','LOW'],['LOW','HIGH'],['RECOMMENDED','RECOMMENDED'],['HIGH','LOW'],['HIGH','HIGH']];
 for(const b of uniqueBuilds(rank,pairs)){const n=phase==='MATRIX'?30:50,days=phase==='MATRIX'?30:100;scenarios.push({configHash,phase,rank,rankName:c.ranks[rank].name,seed:'ALL',ageStart:22,workdays:days,efficiencyBand:b.e,qualityBand:b.q,aliases:b.aliases.join('|'),status:'RUN',seedCount:n});for(const seed of seeds.slice(0,n))await run(phase,rank,b.e,b.q,22,seed,days,b.aliases.join('|'));console.log(`${phase} Rank${rank} ${b.aliases.join('|')}：${n} seeds × ${days} days`);}
}
for(let rank=0;rank<5;rank++)for(const age of [22,50,60]){
 scenarios.push({configHash,phase:'AGE',rank,rankName:c.ranks[rank].name,seed:'ALL',ageStart:age,workdays:30,efficiencyBand:'RECOMMENDED',qualityBand:'RECOMMENDED',status:age===22?'REUSED_MATRIX':'RUN',seedCount:30});
 if(age===22){for(const seed of seeds.slice(0,30)){const r=cachedRecommended.get(`${rank}:${seed}`)!;assert.ok(r);ageRows.push({...r,phase:'AGE',scenarioId:`AGE-r${rank}-e${r.efficiencyLevel}-q${r.qualityLevel}-a22`,reusedFromScenario:String(r.scenarioId)});}}
 else for(const seed of seeds.slice(0,30))await run('AGE',rank,'RECOMMENDED','RECOMMENDED',age,seed,30,'RECOMMENDED/RECOMMENDED');console.log(`AGE Rank${rank} Age${age}：30 seeds（22歲重用 MATRIX）`);
}
const resultMetrics=Object.keys(runs[0]).filter(k=>typeof runs[0][k]==='number'&&!['seed','rank','ageStart','workdays','efficiencyLevel','efficiencyValue','qualityLevel','qualityValue','recommendedEfficiencyLevel','recommendedEfficiencyValue','recommendedQualityLevel','recommendedQualityValue'].includes(k));
const summaries:Row[]=[];
for(const list of [runs,ageRows.filter(r=>r.ageStart===22)])for(const key of [...new Set(list.map(r=>`${r.scenarioId}:${r.workdays}`))]){const group=list.filter(r=>`${r.scenarioId}:${r.workdays}`===key),r=group[0];for(const metric of resultMetrics){const xs=group.map(r=>r[metric]).filter(x=>typeof x==='number') as number[];if(xs.length)summaries.push({configHash,scenarioId:r.scenarioId,phase:r.phase,seed:'AGGREGATE',rank:r.rank,rankName:r.rankName,ageStart:r.ageStart,workdays:r.workdays,efficiencyLevel:r.efficiencyLevel,efficiencyValue:r.efficiencyValue,efficiencyBand:r.efficiencyBand,qualityLevel:r.qualityLevel,qualityValue:r.qualityValue,qualityBand:r.qualityBand,metric,...stats(xs)});}}
const paired:Row[]=[];
for(const row of runs.filter(r=>r.phase==='MATRIX'))for(const axis of ['efficiency','quality']){
 const level=axis==='efficiency'?'efficiencyLevel':'qualityLevel',other=axis==='efficiency'?'qualityLevel':'efficiencyLevel',rec=levels(Number(row.rank))[axis==='efficiency'?'efficiency':'quality'];
 if(Number(row[level])===rec)continue;const base=runs.find(r=>r.phase===row.phase&&r.rank===row.rank&&r.seed===row.seed&&r.ageStart===row.ageStart&&r.workdays===row.workdays&&Number(r[level])===rec&&r[other]===row[other]);assert.ok(base);
 const p:Row={configHash,scenarioId:row.scenarioId,baselineScenarioId:base.scenarioId,phase:'MATRIX',seed:row.seed,rank:row.rank,rankName:row.rankName,ageStart:row.ageStart,workdays:row.workdays,efficiencyLevel:row.efficiencyLevel,efficiencyValue:row.efficiencyValue,efficiencyBand:row.efficiencyBand,qualityLevel:row.qualityLevel,qualityValue:row.qualityValue,qualityBand:row.qualityBand,axis,comparison:Number(row[level])>rec?'HIGH_MINUS_RECOMMENDED':'LOW_MINUS_RECOMMENDED'};for(const metric of resultMetrics)p[`delta_${metric}`]=row[metric]===null||base[metric]===null?null:Number(row[metric])-Number(base[metric]);paired.push(p);
}
const economy:Row[]=[],recommended=runs.filter(r=>r.phase==='LONG'&&r.workdays===100&&r.efficiencyBand==='RECOMMENDED'&&r.qualityBand==='RECOMMENDED');
for(let rank=0;rank<5;rank++){const g=recommended.filter(r=>r.rank===rank),m=(key:string)=>mean(g.map(r=>Number(r[key]))),prior=recommended.filter(r=>r.rank===rank-1);economy.push({configHash,seed:'AGGREGATE',rank,rankName:c.ranks[rank].name,ageStart:22,workdays:100,efficiencyLevel:g[0].efficiencyLevel,efficiencyValue:g[0].efficiencyValue,efficiencyBand:'RECOMMENDED',qualityLevel:g[0].qualityLevel,qualityValue:g[0].qualityValue,qualityBand:'RECOMMENDED',seedCount:g.length,recommendedSpeed:c.ranks[rank].recommendedSpeed,recommendedQuality:c.ranks[rank].recommendedQuality,generatedWorkloadPerDay:m('generatedWorkloadPerDay'),processedWorkloadPerDay:m('processedWorkloadPerDay'),grossIncomePerWorkday:m('grossIncomePerWorkday'),incomePerProcessedWorkload:m('incomePerProcessedWorkload'),overdueLossPercent:m('overdueLossPercent'),parentBonusPercent:m('projectParentBonusPercent'),bossIncomePercent:mean(g.map(r=>Number(r.bossIncome)/Number(r.grossIncome)*100)),followUpIncomePercent:mean(g.map(r=>Number(r.follow_upIncome)/Number(r.grossIncome)*100)),incomeGrowthPercent:prior.length?(m('grossIncomePerWorkday')/mean(prior.map(r=>Number(r.grossIncomePerWorkday)))-1)*100:null,workloadGrowthPercent:prior.length?(m('generatedWorkloadPerDay')/mean(prior.map(r=>Number(r.generatedWorkloadPerDay)))-1)*100:null,promotionCostInGrossIncomeDays:c.ranks[rank+1]?c.ranks[rank+1].promotionCost/m('grossIncomePerWorkday'):null});}
// Relative economy-loss flag: above the upper quartile + 1.5 IQR among recommended rank means, or >=2x own rank recommended baseline and >=2 percentage points above it.
const losses=economy.map(r=>Number(r.overdueLossPercent)),lossFence=quantile(losses,.75)+1.5*(quantile(losses,.75)-quantile(losses,.25));
for(const row of runs){const reference=Number(economy.find(r=>r.rank===row.rank)!.overdueLossPercent),loss=Number(row.overdueLossPercent);if(loss>lossFence||loss>reference*2&&loss>reference+2)flags.push({...row,flag:'ECONOMY_LOSS_HIGH',evidence:JSON.stringify({loss,ownRecommended100DayLoss:reference,rankIqrFence:lossFence})});}
assert.equal(await sourceHash(),originalHash,'production source/config modified');
await csv('rank-balance-scenarios',scenarios);await csv('rank-balance-runs',runs);await csv('rank-balance-summary',summaries);await csv('rank-balance-work-source',sourceRows);await csv('rank-balance-followups',followRows);await csv('rank-balance-projects',projectRows);await csv('rank-balance-boss',bossRows);await csv('rank-balance-economy',economy);await csv('rank-balance-promotion',promotionRows);await csv('rank-balance-age-crosscheck',ageRows);await csv('rank-balance-paired-differences',paired);await csv('rank-balance-flags',flags);
const settings={configHash,sourceHash:originalHash,seeds,configSnapshot:c,physicalRuns,dailyCount,maxConservationError,instrumentationDirectory:engine.dir,notes:'Daily CSV is authoritative; JSON omits daily rows to avoid duplicating the largest dataset. Age22 reuses identical matrix results.'};
await writeFile(`${dir}/rank-balance-results.json`,JSON.stringify({settings,scenarios,runs,summaries,economy,ageRows,paired,flags},null,2));
await writeBalanceReport(dir,{settings,runs,summaries,economy,ageRows,paired,flags,scenarios});await finalizeBalance(dir);console.log(`DONE ${physicalRuns} physical runs, ${dailyCount} daily snapshots, conservation max error=${maxConservationError}`);
