import { getPromotionQualificationStats } from '../game/career/promotionAssignment';
import { catchChance,escapeChance,activeMandatoryBoss } from '../game/career/bossEvents';
import { sleepRatio,sleepEffect } from '../game/targets/sleepWindow';
import { permanentMultiplier } from '../game/prestige/permanentUpgrades';
import { getAgeWorkloadMultiplier, ageProductEfficiencyBonus } from '../game/work/ageWorkload';
import { getWorkTemplateWeight,getProjectTemplateWeight } from '../game/work/templateWeights';
import { remainingProductDays } from '../game/products/productManager';
import { useState } from 'react';
import { gameConfig as c } from '../config/gameConfig';
import type { GameEngine } from '../game/engine/GameEngine';
import type { PermanentId, UpgradeId } from '../game/types';
export function DebugPanel({ engine, close }: { engine: GameEngine; close: () => void }) {
  const s = engine.state; const [day, setDay] = useState(2); const [product, setProduct] = useState('eyes'); const [permanent, setPermanent] = useState<PermanentId>('workEfficiency'); const [reset, setReset] = useState(false);
  const debug = (command: string, value?: number, id?: string) => engine.dispatch({ type: 'debug', command, value, id });
  const meetingDebug = <section className="debug-card"><h3>Meeting V1</h3><div className="debug-buttons"><button onClick={()=>debug('normalMeeting')}>Force Normal Meeting</button><button onClick={()=>debug('bossMeeting')}>Force Boss Meeting</button></div><p>完成 {s.meetings.statistics.meetingCount} 場 · 占用 {s.meetings.statistics.meetingSeconds.toFixed(2)} 秒 · 固定補貼 ${s.meetings.statistics.meetingCompensation}</p><p>Normal schedule {s.meetings.scheduledNormal?.scheduledStartWorldTime?.toFixed(2)??'—'} · Boss pending {s.meetings.pendingBoss?'YES':'NO'} · Remaining {s.currentTarget?.type==='MEETING'?s.currentTarget.remainingDuration.toFixed(2):'—'}</p></section>;
  const rankContent = <section className="debug-card" aria-label="Rank Content"><h3>職級內容與有效權重</h3><div className="debug-buttons">{c.ranks.map((rank,i)=><button key={i} onClick={()=>debug('rank',i)}>Set Rank {i}</button>)}</div><p>目前 Rank {s.career.rank} · {c.ranks[s.career.rank].name}</p><details><summary>Eligible Normal Work</summary>{c.work.templates.filter(t=>getWorkTemplateWeight(t,s.career.rank)>0).map(t=><p key={t.id}>{t.name} · Effective Weight {getWorkTemplateWeight(t,s.career.rank)}</p>)}</details><details><summary>Eligible Projects</summary>{c.projects.templates.filter(t=>getProjectTemplateWeight(t,s.career.rank)>0).map(t=><p key={t.id}>{t.name} · Effective Project Weight {getProjectTemplateWeight(t,s.career.rank)}</p>)}</details></section>;
  const number = (label: string, value: number, command: string, id?: string) => <label>{label}<input aria-label={label} type="number" min="0" defaultValue={value} key={`${label}:${id}`} onBlur={e => debug(command, Number(e.target.value), id)} /></label>;
  const promotionQ=getPromotionQualificationStats(s);
  const promotionDebug=<section className="debug-card"><h3>Promotion V1</h3><p>{s.promotion.status} · Scheduled Workday {s.promotion.scheduledWorkday??'—'} · Retry {s.promotion.retryAvailableWorkday??'—'}</p><p>Qualification E {promotionQ.efficiency.toFixed(2)} / Q {promotionQ.quality.toFixed(2)} · Evaluation E {promotionQ.evaluatedEfficiency.toFixed(2)} / Q {promotionQ.evaluatedQuality.toFixed(2)}</p><p>Progress {s.promotion.progress.toFixed(2)} / {s.promotion.requirement} · Deadline {s.promotion.deadlineWorldTime??'—'}</p></section>;
  return <>{promotionDebug}{meetingDebug}{rankContent}<div className="page-heading"><h2>V2 Debug</h2><button onClick={close}>關閉 Debug</button><p>世界 Day {s.world.dayIndex + 1} · {s.needs.phase} · Todo {s.todoQueue.length}</p></div><section className="debug-card"><h3>角色與時間</h3><p>Age Workload Multiplier ×{getAgeWorkloadMultiplier(s.player.age).toFixed(2)} · Product Age Efficiency Bonus +{(ageProductEfficiencyBonus(s)*100).toFixed(1)}%</p><div className="debug-buttons"><button onClick={() => debug('ageProductEnable')}>Enable Age Product</button><button onClick={() => debug('ageProductDisable')}>Disable Age Product</button><button onClick={() => debug('overdue5')}>Add 5 Overdue Todos</button></div><div className="debug-grid">{number('設定金錢', s.player.money, 'money')}{number('設定年齡', s.player.age, 'age')}{number('設定職級', s.career.rank, 'rank')}{(Object.keys(c.upgrades) as UpgradeId[]).map(id => <div key={id}>{number(`設定${c.upgrades[id].name}`, s.player.upgrades[id], 'upgrade', id)}</div>)}</div><div className="debug-buttons">{[22,30,40,50,60,70].map(age => <button key={age} onClick={() => debug('age', age)}>年齡 {age} 歲</button>)}<button onClick={() => debug('moneyAdd')}>金錢 +1000</button>{c.time.speeds.map(value => <button key={value} onClick={() => engine.dispatch({ type: 'speed', value })}>{value}x</button>)}</div><label>跳到 Day <input type="number" min="1" value={day} onChange={e => setDay(Number(e.target.value))} /></label><div className="debug-buttons"><button onClick={() => debug('day', day)}>推進到指定 Day</button><button onClick={() => debug('lunch')}>跳到午休</button><button onClick={() => debug('offwork')}>跳到下班</button><button onClick={() => debug('sleep')}>跳到睡眠錨點</button></div><p>時間跳轉正常模擬途中事件，不中止活動。</p></section>
  <section className="debug-card"><h3>工作、後續與專案</h3>{number('Set Deadline Workday', s.todoQueue[0]?.dueWorkdayIndex ?? 0, 'setDeadlineWorkday')}<div className="debug-buttons">{[['deadlineBoss','Add Boss Urgent Todo'],['deadlineRework','Add Rework Todo'],['deadlineProject','Add Project Todo'],['deadlineNone','Add No Deadline Todo'],['deadlineNormal','Add Normal Todo'],['deadlineToday','Add Due Today Todo'],['deadline1','Add Todo Due In 1 Workday'],['deadline3','Add Todo Due In 3 Workdays'],['nextWorkStart','Jump To Next Work Start'],['beforeWorkStart','Jump Before Work Start'],['deadlineOverdue','Add Overdue Todo'],['daily','生成日常工作'],['clearTodos','清空 Todo'],['todos10','增加 10 個 Todo'],['followImmediate','立即 Follow-up +2'],['followDelayed','延遲 Follow-up +2'],['pendingNow','立即觸發 Pending'],['project','建立 Project'],['subtask','完成 Project Subtask'],['bossCatch','強制 Boss Catch'],['escapeSuccess','強制 Escape Success'],['escapeFail','強制 Escape Fail'],['foodInterrupt','測試 FOOD 暫停工作']].map(([command,label]) => <button key={command} onClick={() => debug(command)}>{label}</button>)}</div><details><summary>Todo Deadline Profiles</summary>{[...s.todoQueue, ...(s.currentTarget?.type === 'WORK' ? [s.currentTarget.todo] : [])].map(t => <p key={t.id}>{t.name} · {t.deadlineProfileId} · 期限 {t.deadlineWorkdays ?? '無'} 工作天 · assignment {t.assignmentWorkdayIndex ?? 'pending'} · due {t.dueWorkdayIndex ?? 'null'}</p>)}</details><details><summary>Pending Follow-up（{s.pendingFollowUps.length}）</summary>{s.pendingFollowUps.map(p => <p key={p.id}>{p.followUpType} · {p.tasksToCreate.length} 份 · {Math.max(0,p.triggerAtWorldTime-s.world.totalWorldTime).toFixed(1)} 秒後</p>)}</details><details><summary>專案</summary>{s.projects.map(p => <p key={p.id}>{p.name} {p.completedSubtasks}/{p.subtasks.length}</p>)}</details></section>
  <section className="debug-card"><h3>Boss / Sleep</h3><p>Boss Attention {(catchChance(s)*100).toFixed(1)}% · Guaranteed Severity {Math.floor(catchChance(s))} · Extra Severity Chance {((catchChance(s)%1)*100).toFixed(1)}%</p><p>Current Escape Chance {(escapeChance(s)*100).toFixed(1)}% · Rank Escape Resistance {c.ranks[s.career.rank].rankEscapeResistance} PROVISIONAL</p><p>Active Mandatory Boss Overtime {activeMandatoryBoss(s)?'YES':'NO'} · Boss Severity / Workload Multiplier / Reward Multiplier ×{activeMandatoryBoss(s)?.bossSeverity??0}</p><p>Sleep Window {s.needs.sleep.windowStart}–{s.needs.sleep.windowEnd} · Actual Duration {s.needs.sleep.duration.toFixed(2)} / Output {s.needs.sleep.output.toFixed(2)} · Ratio {sleepRatio(s).toFixed(3)}</p><p>Next-day Speed {((s.needs.sleep.speedModifier)*100).toFixed(1)}% · Quality {((s.needs.sleep.qualityModifier)*100).toFixed(1)}%</p><div className="debug-buttons">{[0,10,45,65,95,100,115,200,300,500,1000].map(l=><button key={l} onClick={()=>Object.keys(c.upgrades).forEach(id=>debug('upgrade',l,id))}>全部能力 Lv{l}</button>)}</div></section><section className="debug-card"><h3>事件與訂閱</h3><div className="debug-buttons">{c.events.definitions.map(e => <button key={e.id} onClick={() => debug('event', undefined, e.id)}>強制{e.name}</button>)}</div><label>產品<select aria-label="Debug 產品" value={product} onChange={e => setProduct(e.target.value)}>{c.products.definitions.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><div className="debug-buttons"><button onClick={() => debug('product', undefined, product)}>啟用／停用產品</button><button onClick={() => debug('renew', undefined, product)}>強制產品續費</button></div>{number('產品剩餘有效日數', remainingProductDays(s, product), 'productDays', product)}</section>
  <section className="debug-card"><h3>Prestige 與離線</h3><label>永久路線<select value={permanent} onChange={e => setPermanent(e.target.value as PermanentId)}>{c.prestige.upgrades.map(u => <option key={u.id} value={u.id}>{u.name}</option>)}</select></label>{number('永久倍率表等級', s.prestige.levels[permanent], 'permanent', permanent)}<p>總倍率：{permanentMultiplier(s,permanent).toFixed(3)}</p><div className="debug-buttons"><button onClick={() => debug('clarity')}>清醒值 +30</button><button onClick={() => debug('prestigeReady')}>開啟醒來條件</button><button onClick={() => debug('prestige')}>強制 Prestige</button><button onClick={() => debug('offline30')}>模擬離線 30 分鐘</button><button onClick={() => debug('offline16h')}>模擬離線 16 小時</button></div></section>
  <section className="debug-card"><button className="danger" onClick={() => setReset(true)}>Reset V2 Save</button>{reset && <div role="dialog" aria-label="確認重置"><p>會清除 V2 當輪與永久測試資料。</p><button onClick={() => { engine.resetAll(); setReset(false); }}>確認清除全部</button><button onClick={() => setReset(false)}>取消</button></div>}</section></>;
}

